### ISSUE TITLE
Exit code of spectest-interp

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1002]
We discovered that the `wast2json` and `spectest-interp` tools in this repository were perfect for our use case of trying to execute wasm spec tests, as they did all the heavy lifting of figuring out what to do where! (and made it so we didn't have to write a wast parser)

We noticed, however, that we mistakenly thought all spec tests were passing when there were actually a number of failures. We originally thought that an exit code of zero from `spectest-interp` indicated success, but we actually needed to also check for `X/Y tests passed.` and make sure `X` equals `Y`.

Would it be possible to update the `spectest-interp` tool to exit with a nonzero exit status if any tests failed? That'd at least make the checking a bit easier on our end and hopefully more future-proof for others!

**Comment by fitzgen** [comment]
In particular, it seems like "exit code = number of failing tests" could be a good approach.

**Comment by alexcrichton** [comment]
Heh was just about to see if I could make a patch for this and was alarmed when it looked like the code was already working as expected! Turns out https://github.com/WebAssembly/wabt/pull/1003 just didn't close this by accident, so closing now. Thanks @binji!
