### ISSUE TITLE
wabt does not support the new binary format for exceptions

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#1006]
Instead it looks like it supports and old version of the proposal based on a custom section.

This makes it hard when working with llvm output which uses the latest spec proposal (i.e. a new known section '13').

I started down the road of converting it but god pretty bogged down

**Comment by binji** [comment]
Yeah, I'm not sure how much of that old code we want to keep. It might be easier to remove the old code first, depending on how much is shared with the new proposal.

**Comment by binji** [comment]
This was fixed in the following PRs: https://github.com/WebAssembly/wabt/pull/1009, https://github.com/WebAssembly/wabt/pull/1012, https://github.com/WebAssembly/wabt/pull/1013, https://github.com/WebAssembly/wabt/pull/1014, https://github.com/WebAssembly/wabt/pull/1016
