### ISSUE TITLE
`wasm-opt -O <file>` should throw an error

### ISSUE THREAD

**Issue by surma** [WebAssembly/wabt#1008]
When I run `wasm-opt -O3 myfile.wasm`, I get no error and no output, but `myfile.wasm` stays the same. This lead me to believe that these files had already been properly optimized.

Then @kripken told me that I had to specify an output file like this: `wasm-opt -O3 -o myfile2.wasm myfile.wasm`.

I think a no-op like my first command should error.

**Comment by binji** [comment]
`wasm-opt` is a binaryen tool, not a wabt tool. Can you reopen this issue on its tracker?

**Comment by surma** [comment]
Lol 🤦‍♂️

Apologies.
