### ISSUE TITLE
wat2wasm with reference types

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/wabt#1035]
I saw parser tests allow  `--enable-reference-types` but current version of wat2wasm it seems not support this flag?

Also this missing in [online version](https://webassembly.github.io/wabt/demo/wat2wasm/)

**Comment by Horcrux7** [comment]
The master version in the repo support the command line flag. The latest download version 1.0.8 does not support it. I think libwabt.js on which the online version based, also does not support the flag.

If you want try it today then you need to build it self.

**Comment by binji** [comment]
Thanks for reminding me to update this! Fix here: https://github.com/WebAssembly/wabt/pull/1036

**Comment by MaxGraey** [comment]
Thanks @binji !
