### ISSUE TITLE
Binary reader errors on local count > 0

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#1038]
Due to the way my WASM code is generated, I have code bodies that explicitly list 0 locals of a certain type. It seems the binary reader (intentionally) fails on this:

    error: local count must be > 0

Is there a reason why this restriction is there? I couldn't immediately find something in the spec that constrains this, and tools like `wasm-dis` don't seem to mind (and neither do the engines).

**Comment by binji** [comment]
You're right, this was a bug fix in wabt, but it incorrectly restricted the format. Thanks for catching! Working on a fix now.
