### ISSUE TITLE
how to run wabt VM in intel SGX

### ISSUE THREAD

**Issue by liukunyu** [WebAssembly/wabt#1040]
how to run wabt VM in intel SGX

**Comment by binji** [comment]
I don't know much about intel SGX. Is there an error produced?

**Comment by liukunyu** [comment]
i try to link the libwabt.a library to an Intel SGX enclave(a dynamic library on linux) so the VM will running in a TEE env, but many compile errs because the enclave must use stdc and stdcxx lib suplied by intel SGX SDK and can not use the IO(file/network/stdout) functionality, so i must modify the WABT source code, replacing the include files and remove the IO callings.

do you have the planning to make the wabt VM running on TEE env, like the intel SGX platform?

**Comment by liukunyu** [comment]
thank a lot
