### ISSUE TITLE
cmake error no wat2wasm binary found

### ISSUE THREAD

**Issue by rangapv** [WebAssembly/wabt#1062]
Hi,
I followed the instruction on your github and did a 
cmake ..

I got no error, but in the clang/Debug there is no binary file wat2wasm etc...
Where will the binaries reside after building using cmake ?

Regards
Ranga

**Comment by binji** [comment]
Sorry, I should clarify the instructions there. When you run `cmake ..`, it generates the build files but doesn't build the project. The format of the build files depends on what cmake generator you use. On my machine it generates makefiles, so I can run `make` afterward to build the project. On Windows it will typically generate Visual Studio project files, which you can open an build in Visual Studio. 

You can ask cmake to build it, regardless of generator, by running `cmake --build .` I'll add that to the documentation.

**Comment by rangapv** [comment]
No problem... I tried now and I was able to compile and get the binaries.
Thanks for the quick response.
Regards
Ranga
