### ISSUE TITLE
[Bugs Report] failed to compile

### ISSUE THREAD

**Issue by xieguigang** [WebAssembly/wabt#1067]
Hi,

Help needed, when i use wat2wasm for compile ``S-Expression`` text format script to WebAssembly binary, error reports:

```
base64.wast:252:22: error: type mismatch in if true branch, expected [] but got [i32]
                    (call $array_push (get_local $chars) (call $fromCharCode ...
                     ^^^^
base64.wast:258:5: error: type mismatch in if false branch, expected [] but got [i32, i32, i32]
    )
    ^
base64.wast:290:14: error: type mismatch in if true branch, expected [] but got [i32]
            (set_local $n (i32.add (get_local $n) (i32.const 1)))
             ^^^^^^^^^
base64.wast:297:5: error: type mismatch in if false branch, expected [] but got [i32]
    )
    ^
```

But after i check the input wast file, i didn't found any errors in the wast script file. I not sure there is some bugs in ``wat2wasm`` or I'm just missed something.....

Here are some necessary information for reproduce these errors:
> Demo script: [base64_wast.txt](https://github.com/WebAssembly/wabt/files/3099945/base64_wast.txt)
> Version of wat2wasm: [wabt-1.0.10-win64](https://github.com/WebAssembly/wabt/releases/tag/1.0.10)
> Command line for run the compiler:

```cmd
wat2wasm.exe base64.wast --verbose --debug-parser --output base64.wasm --debug-names
```

**Comment by Horcrux7** [comment]
> base64.wast:252:22: error: type mismatch in if true branch, expected [] but got [i32]

Your imported function `$array_push` has a return value of `i32`. You does not consume this value in the `then` block. Your `if` block is declared as void or `[]`. You need to consume the `i32` (for example with a `drop`) or change the return type of the if expression to `(result i32)`.

The same is valid for the `else` block. There you have 3 calls to `$array_push`. That there are 3 additional value on the stack.

Alternativ you can change the return of `$array_push` to void.

**Comment by xieguigang** [comment]
Hi,

Many thanks for your help, problem solved with add additional ``drop`` operator to function calls for cleanup the stack. 😀

**Comment by binji** [comment]
Yes `drop` is probably the best way to do this. That said, a `br` or `return` instruction will also clean up the stack automatically. Because `if` introduces a new label, you can always use `br 0` at the end of an if branch to clean up the stack. For example,

```wasm
(if (i32.lt_s (get_local $r) (i32.const 128))
  (then
    (call $array_push (get_local $chars) (call $fromCharCode (get_local $r)))
    (br 0)
  )
  (else
    (call $array_push (get_local $chars) (call $fromCharCode (i32.or (i32.shr_s (get_local $r) (i32.const 12)) (i32.const 224))))
    (call $array_push (get_local $chars) (call $fromCharCode (i32.or (i32.and (i32.shr_s (get_local $r) (i32.const 6)) (i32.const 63)) (i32.const 128))))
    (call $array_push (get_local $chars) (call $fromCharCode (i32.or (i32.and (get_local $r) (i32.const 63)) (i32.const 128))))
    (br 0)
  )
)
```

**Comment by Horcrux7** [comment]
@binji Nice, well to know it.
