### ISSUE TITLE
wat2wasm - type mismatch in implicit return

### ISSUE THREAD

**Issue by AlanFoster** [WebAssembly/wabt#1075]
### Input file

`hello_world.wat`

```wasm
(module
    (func $output_println (import "System::Output" "println") (param i32))
 
    (func $factorial (param $n i32) (result i32)
        (if
            (i32.eq
                (get_local $n)
                (i32.const 1)
            )
            (then
                (return
                    (i32.const 1)
                )
            )
            (else
                (return
                    (i32.mul
                        (get_local $n)
                        (call
                            $factorial
                            (i32.sub
                                (get_local $n)
                                (i32.const 1)
                            )
                        )
                    )
                )
            )
        )
    )
 
    (func $Main (export "Main")
        (call
            $output_println
            (call
                $factorial
                (i32.const 5)
            )
        )
    )
)
```

### Command run

```
wat2wasm hello_world.wat -o hello_world.wasm
```

### Output

```
hello_world.wat:29:9: error: type mismatch in implicit return, expected [i32] but got []
        )
        ^
```

### Expected output

wat2wasm infers that all code paths result in i32 being returned, and compiles to wasm sucessfully.

Adding an explicit return after the if structure within `$factorial` fixes the issue, but is an impossible code path.

**Comment by binji** [comment]
The wat format requires that you annotate any blocks that return values with their signature. If no signature is provided, it is assumed that the block has no parameters and no results. The fix here is to provide the signature to the `if` block:

```wasm
(func $factorial (param $n i32) (result i32)
  (if (result i32)
    ...
```

The error message could be clearer here.

**Comment by AlanFoster** [comment]
@binji Thanks for the quick response! I've been thinking about the semantics of this since you initially replied.

The wasm spec has:

```
The return instruction is a shortcut for an unconditional branch to the outermost block, which implicitly is the body of the current function. Taking a branch unwinds the operand stack up to the height where the targeted structured control instruction was entered.

**Comment by AlanFoster** [comment]
@binji Thanks for the quick response! I've been thinking about the semantics of this since you initially replied.

The wasm spec has:

> The return instruction is a shortcut for an unconditional branch to the outermost block, which implicitly is the body of the current function. Taking a branch unwinds the operand stack up to the height where the targeted structured control instruction was entered.

It feels like the type checking for the wat2wasm tool's type checking maybe isn't perfect here, but I can't fully articulate why

I should definitely do a better job at wasm code generation like you've shown. I was just hoping naive code generation would have worked! Thank you for looking at this 🏆

**Comment by binji** [comment]
> It feels like the type checking for the wat2wasm tool's type checking maybe isn't perfect here, but I can't fully articulate why

You can try the same program in the [reference interpreter](https://github.com/WebAssembly/spec/tree/master/interpreter), it produces a similar error:

```
test.wat:4.5-30.6: invalid module: type mismatch: operator requires [i32] but stack has []
```

This is saying essentially the same thing as wat2wasm (the line range is the entire function block).

> Adding an explicit return after the if structure within $factorial fixes the issue, but is an impossible code path.

I missed this comment before; another solution would be to use the `unreachable` instruction after the `if` block:

```wasm
    (func $factorial (param $n i32) (result i32)
        (if
          ...
        )
        (unreachable)
    )
```

Ultimately, the webassembly type-checking doesn't "drill down" into an `if` to determine whether both branches return. It analyzes the types as if it were just:

```wasm
    (func $factorial (param $n i32) (result i32)
        (if ... )
    )
```

Since the `if` doesn't return `i32`, then the function doesn't return `i32`, which is a type error.

**Comment by AlanFoster** [comment]
Thanks for the extra context! :+1: I'll close this off and pursue the generation of better web-assembly
