### ISSUE TITLE
Test suite supporting 3rd party interpreters?

### ISSUE THREAD

**Issue by xplorld** [WebAssembly/wabt#1093]
Hello, I am writing a homemade 3rd party interpreter, and wonder how to use test suite in `/test` to test my own one, instead of copying and renaming my executable to `wasm-interp` and move to `wabt/bin`.

**Comment by binji** [comment]
You probably don't want to run all of the wabt tests, there are many that are wabt-specific. Instead, you should run the spec tests: https://github.com/WebAssembly/spec/tree/master/test/core. There's a repo that includes only the tests too: https://github.com/WebAssembly/testsuite.

You can use the `wast2json` tool in wabt to convert these to a json file and a collection of `.wasm` and `.wat` files. The json file has an ad-hoc format, but it shouldn't be too hard to interpret.

**Comment by xplorld** [comment]
WebAssembly/testsuite is good, but I wonder how to run it... I did not find `assert_trap` in the spec, is that a WABT-extension?

**Comment by binji** [comment]
It's defined briefly here: https://github.com/WebAssembly/spec/tree/master/interpreter#scripts and in OCaml here: https://github.com/WebAssembly/spec/blob/master/interpreter/script/run.ml#L410.

**Comment by xplorld** [comment]
Thanks for the information!
