### ISSUE TITLE
No CMAKE_CXX_COMPILER could be found

### ISSUE THREAD

**Issue by Nosfy01** [WebAssembly/wabt#1102]
Hello,

This is more probably an error on my part than an "issue", I'm just not sure where to get help on this...

Running Ubuntu, juste after "sudo apt install cmake", then "cmake .." (in the newly created build directory, as instructed). I get this

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:18 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
```
I'm guessing the cmake version I got is not exactly the one that is expected or it is not configured the same way the developers thought it would be.

In any case, I don't know what to do... I'm as clueless as the message as to where to find this missing compiler.

Any suggestion?

**Comment by sbc100** [comment]
Looks like your missing a C++ compiler.  Do you have `g++` installed?  Perhaps run `apt-get install build-essential`?

**Comment by Nosfy01** [comment]
It worked!

Thank you very much!
