### ISSUE TITLE
bin/wasm2c --version # how to ?

### ISSUE THREAD

**Issue by drandreaskrueger** [WebAssembly/wabt#1106]
```
bin/wasm2c --version
unknown option '--version'
```

How can I do that? If it doesn't exist yet then:

**feature request:** allow me to ask the binary about its version number.

(obviously, `--version` for all of them: `bin/spectest-interp  bin/wasm2c  bin/wasm2wat  bin/wasm-interp  bin/wasm-objdump  bin/wasm-opcodecnt  bin/wasm-strip  bin/wasm-validate  bin/wast2json  bin/wat2wasm  bin/wat-desugar`)

thanks.

**Comment by binji** [comment]
Good point, these would be nice to add.

**Comment by drandreaskrueger** [comment]
thumbs up

thanks!
