### ISSUE TITLE
data segment byte coding not following spec ?

### ISSUE THREAD

**Issue by ljulliar** [WebAssembly/wabt#1107]
Hi all,

I looks like the wat2wasm tool doesn't support bytes expressed in hexadecimal as stated by the WASM 1.0 spec.

Concretely wat2wasm is fine with :
  `(data 0 (i32.const 4)  "\04\00\00\00")`
but throw an error with:
  `(data 0 (i32.const 4)  0x04 0x00 0x00 0x00)`

Is it a known problem with wat2 wasm or am I misreading the WASM spec ?

**Comment by yurydelendik** [comment]
The spec at http://webassembly.github.io/spec/core/text/modules.html#text-datastring ?

**Comment by ljulliar** [comment]
Yep! so it's definitely me misreading the specs. Sorry for the noise.
