### ISSUE TITLE
Crash disassembling file built with reference types

### ISSUE THREAD

**Issue by wingo** [WebAssembly/wabt#1124]
I am working on a branch of https://github.com/google/schism that uses reference types.  To check that my .wasm is fine, I used wasm2wat from today; however it crashes:

```
wingo@milano:~/src/schism$ ~/src/wabt/out/gcc/Debug/wasm2wat --enable-reference-types schism-stage0.wasm
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

File attached.  I'll have a poke at working up a patch.

[schism.zip](https://github.com/WebAssembly/wabt/files/3417609/schism.zip)

**Comment by wingo** [comment]
The proximate cause is that `common.h`'s GetInlineTypeVector, called by `BinaryReaderIR::SetBlockDeclaration`, doesn't handle anyref block types -- and instead of aborting, it uses WASM_UNREACHABLE which just causes UB.  Not sure what the coding standard is, but I would seriously consider converting all WASM_UNREACHABLE instances into aborts.

**Comment by binji** [comment]
> Not sure what the coding standard is, but I would seriously consider converting all WASM_UNREACHABLE instances into aborts.

Agreed, I think I thought that `__builtin_unreachable` would trap, but realized it just tells the optimizer that it can never happen so it can be optimized away. It would be good to fix these.

**Comment by binji** [comment]
See https://github.com/WebAssembly/wabt/pull/1126.
