### ISSUE TITLE
How to call a native webassembly file in c/c++ source code?

### ISSUE THREAD

**Issue by darkmoon233** [WebAssembly/wabt#1130]
In the JavaScript, you can use the `WebAssembly.instantiate` function to load a WASM file and use the various methods provided by the WASM file. I want to know if there is such a way in C++ that I can use WASM files directly.

**Comment by binji** [comment]
You'll probably want to look at https://github.com/WebAssembly/wasm-c-api. There has been work making various wasm engines support this API (not much on wabt though).

**Comment by darkmoon233** [comment]
What I want to achieve is the cross-call between c++ and wasm. This must depend on the wasm interpreter. I think it may be some help in wabt.

**Comment by binji** [comment]
Yes, this is possible in wabt, see [test-interp.cc](https://github.com/WebAssembly/wabt/blob/master/src/test-interp.cc) for example. But this uses wabt's own internal interface. The wasm-c-api has (what we hope to be) a standard interface for doing this: https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.hh#L634-L652

**Comment by binji** [comment]
OK, we can close this issue in favor of that one.
