### ISSUE TITLE
wasm2c --enable-multi-value

### ISSUE THREAD

**Issue by nomeata** [WebAssembly/wabt#1134]
I was hoping to use `wasm2c` on some WebAssembly modules that use the multi-value extension, but I get
```
wasm2c currently support only default feature flags.
```

I know that you know about this, just opening this issue to track any possible implementation.

**Comment by tlively** [comment]
Out of curiosity, how are you producing multivalue modules and what benefit does their being multivalue get you?

**Comment by nomeata** [comment]
An in-house compiler, and the benefit is that we get to ~feel cool for being at the spearhead of the Wasm ecosystem~ return multiple values from functions, even without a shadow stack or so.

**Comment by nomeata** [comment]
How good is `wasm2c` anyways? Is it good enough in order to run C-based static analysis tools on Wasm modules? (Thinking AFL)

Maybe I can write a Wasm to Wasm pass that desugars multi-value away to unblock me here.

**Comment by binji** [comment]
`wasm2c` works, but is still pretty rough to use. In particular, wiring up imports can be a bit of a pain.

That said, I have successfully used it to run benchmarks many times now, and the performance is pretty good. It also passes all the spec tests (at least on Linux+Mac).

I don't see any reason you couldn't use something like AFL with the output. Be warned that the C files it generates are often very big (~10x larger than its wasm file) and can really tax a compiler, however.

**Comment by nomeata** [comment]
First experiments with `wasm2c` (after avoiding multi-value) and AFL are great!

**Comment by SoniEx2** [comment]
this can probably be closed? as of #1686

**Comment by SoniEx2** [comment]
also #1836 which makes the `--enable-` and `--disable-` flags usable

**Comment by keithw** [comment]
Done in #1686.
