### ISSUE TITLE
spurious type in wat2wasm then wasm2wat and loosing `$start`

### ISSUE THREAD

**Issue by amirouche** [WebAssembly/wabt#1135]
I am not sure it is a bug, here is it:

```scheme
$ cat in.scm 
(module
 (func $start (result i32)
       (i32.const 42)))
$ wat2wasm in.scm -o out.wasm
$ wasm2wat out.wasm -f --generate-names
(module
  (type $t0 (func (result i32)))
  (func $f0 (type $t0) (result i32)
    (i32.const 42)))
```

The `start` function loose its `$start` symbol and get the type information two times: `(type $t0) (result i32)`.

Feel free to close the issue if it is expected behaviour.

**Comment by binji** [comment]
By default, `wat2wasm` doesn't write a `name` section, which is needed to keep the `$start` name. You can write it by passing the `--debug-names` flag.

```wasm
$ cat test.wat
(func $start (result i32) i32.const 42)
$ wat2wasm test.wat -o test.wasm --debug-names
$ wasm2wat test.wasm -f
(module
  (type (;0;) (func (result i32)))
  (func $start (type 0) (result i32)
    (i32.const 42)))
```

The type section is given twice for clarity; if the type use `(type $t0)` and the explicit type `(result i32)` don't match, it's an error. Without the type use, information could be lost. See for example:

```wasm
$ cat test.wat
(type (func (result i32)))
(type (func (result i32)))
(func (type 0) i32.const 0)
(func (type 1) i32.const 1)
$ bin/wat2wasm test.wat
$ bin/wasm2wat test.wasm -f --gen
(module
  (type $t0 (func (result i32)))
  (type $t1 (func (result i32)))
  (func $f0 (type $t0) (result i32)
    (i32.const 0))
  (func $f1 (type $t1) (result i32)
    (i32.const 1)))
```

In this case, if the type uses `(type $t0)` and `(type $t1)` were omitted, it would produce a different binary.

That said, `wasm2wat` could be more clever here and only output a type use when it was needed.
