### ISSUE TITLE
use map and function pointer replace "case"

### ISSUE THREAD

**Issue by fpcfjf** [WebAssembly/wabt#1143]
in "expr-visitor.cc":
HandleDefaultState use a lot of "case":
 Result ExprVisitor::HandleDefaultState(Expr* expr) {
  switch (expr->type()) {
    case ExprType::AtomicLoad:
      CHECK_RESULT(delegate_->OnAtomicLoadExpr(cast<AtomicLoadExpr>(expr)));
      break;

    case ExprType::AtomicStore:
      CHECK_RESULT(delegate_->OnAtomicStoreExpr(cast<AtomicStoreExpr>(expr)));
      break;
......

I recommend using  std::map + std::functional replace it.EX:
.....
map_.insert(ExprType::AtomicStore,OnAtomicStoreExpr)
......

when using it :
map[abc] (pars)

thanks.

**Comment by binji** [comment]
Yes, it could work that way, but I'm not sure I see the value in it. Using a map and `std::function` would require doing an O(logn) lookup in the map, then doing an additional indirect call. It also would require allocating+deallocating the memory for the map, and initializing it on first use. That said, I haven't done any performance measurements, so if you find that this is faster, feel free to send a PR for review.

**Comment by fpcfjf** [comment]
OK，I try to test is.

**Comment by fpcfjf** [comment]
I have tested it repeatedly, and their efficiency is basically the same, but is it easier to manage and update the code using MAP?

**Comment by fpcfjf** [comment]
I respect your opinion.
