### ISSUE TITLE
Realloc is unsuccessful and will cause a crash

### ISSUE THREAD

**Issue by fpcfjf** [WebAssembly/wabt#1147]
in "wasm-rt-impl.c":
uint32_t wasm_rt_register_func_type(uint32_t param_count,
                                    uint32_t result_count,
                                    ...) {
  FuncType func_type;
......
  uint32_t idx = g_func_type_count++;
  g_func_types = **realloc**(g_func_types, g_func_type_count * sizeof(FuncType));
  g_func_types[idx] = func_type;
  return idx + 1;
}

call "realloc" fails,it will cause a crash or memleak(Especially on WINDOWS),. I think we should  check the return value.
FuncType* new_ptr =  **realloc**(g_func_types, g_func_type_count * sizeof(FuncType));
if (new_ptr == NULL)
{
......
}
g_func_types = new_ptr;

**Comment by fpcfjf** [comment]
Is there anything I need to do?

**Comment by keithw** [comment]
Fixed in #2120
