### ISSUE TITLE
wasm-interp supported features list

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/wabt#1154]
There is inconsistency between [supported features table](https://github.com/WebAssembly/wabt#supported-proposals) and [available options list](https://webassembly.github.io/wabt/doc/wasm-interp.1.html). I suppose that threads and exceptions should be added to the table and `--enable-mutable-globals` should be `--disable-mutable-globals`. I can create PR if someone can confirm that table is out of date.

**Comment by binji** [comment]
I agree with renaming to `--disable-mutable-globals`, but I'm confused about threads and exceptions. They already seem to be in the table...?

**Comment by chicoxyzzy** [comment]
Yes, but they don’t have check mark in interpreter column

**Comment by binji** [comment]
OK, I see what you mean. Thanks!
