### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1160]
Are there any plans to create a new release? The last release is 4 months old currently.

I use the latest binary release for running my unit tests on Travis. Today I am missing ref.null which is already fixed in WABT.

**Comment by binji** [comment]
Thanks for reminding me. I'll push a new release now. @aardappel is `wasm-decompile` in a reasonable state to do so?

**Comment by aardappel** [comment]
@binji it is not intended for end-user consumption yet, but it is behind a CMake flag that is by default off.

**Comment by binji** [comment]
OK cool, I'll push a new release then.

**Comment by binji** [comment]
[1.0.12](https://github.com/WebAssembly/wabt/releases/tag/1.0.12)

**Comment by Horcrux7** [comment]
Thank you very much.
