### ISSUE TITLE
Should we switch from travis + appveyor to circleci

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#1168]
circleci has proved very in emscripten and emsdk accross mac, linux and windows.

**Comment by binji** [comment]
I'm OK with it, I found CircleCI to be pretty nice to use too in [wasp](https://github.com/binji/wasp).

**Comment by syrusakbary** [comment]
I was thinking on suggesting Azure pipelines.
To run Windows or macOS in CircleCI I believe you have to pay (we recently switched in Wasmer from CircleCI to Azure Pipelines, couldn't run in macOS or Windows without paying).

If you like the idea I can create a PR moving towards Azure!

**Comment by binji** [comment]
I don't really know much about Azure pipelines. Is there any difference in functionality? I'm tempted to stick with a tool that I know other folks I work with are using, since they'll be maintaining it until I get back. But it's certainly worth considering other options.

**Comment by sbc100** [comment]
OK.. after all this I think maybe github actions is that way to go.   Under the hood I imagine its based on azure, and that is the direction wasi-libc and wasi-sdk ended up going.  wabt would be good test case for possibly switching binaryen and emscripten too.

Any objections to github actions?  I guess one concern would be that they are quite new, but they seem to be getting widespread adoption already and having them built and maintained by github directly seem advantageous.

**Comment by Horcrux7** [comment]
Nice, I have also think about to use it. A using repo will be a nice reference.

**Comment by binji** [comment]
github actions seems pretty nice to me, after having played around with it for a little bit, it seems to be faster than the others.

**Comment by sbc100** [comment]
This is all done now
