### ISSUE TITLE
wasm-decompile

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1174]
I see many commits for a tool `wasm-decompile` in the last time. I have try it and the output look very nice. But I can't find any documentation or spec. That my questions:

- Which language/syntax do you want reproduce with the output? This seems me important to see what is a bug and what is the target language.
- What is the use case for the tool? The development is too expensive only for a nice tool.

**Comment by aardappel** [comment]
Glad you like the output, but this tool is far from complete, so documentation will come later. Right now its output may still be incorrect, so I would hold off on using it.

The target language is Wasm-specific. It is intended to look familiar to C/JS/Java/etc programmers, but in the end it is more important that it represent Wasm very directly. It is intended to allow a programmer to read the contents of a Wasm module much more easily (more familiar, less verbose) than is currently possible with the .wat format.

It may eventually pull in debug information (e.g. DWARF) to recover even more about the names and types in a Wasm module.

**Comment by binji** [comment]
wasm-decompile is documented now, let's close this!

**Comment by aardappel** [comment]
Documentation currently lives here: https://github.com/WebAssembly/wabt/blob/master/docs/decompiler.md

I added it because I feel it is at a stage that it generally ready for most people to use. That said, it is still very much in flux, so expect things to change :)
