### ISSUE TITLE
We should have CMake install targets for the WABT binaries

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#118]
That will mean that we can use `make install` to do things like install into the waterfall build.

**Comment by dschuff** [comment]
Also, for dynamically-linked binaries and/or dylibs, the install process does some kind of useful rpath magic, the details of which I can't remember.

**Comment by sbc100** [comment]
Want me to take this one on?

**Comment by binji** [comment]
sure!

**Comment by binji** [comment]
Fixed in 47cd3242fee70aedef3a2d595ee23fa2fe0efc28.
