### ISSUE TITLE
UnicodeDecodeError when parsing test/regress/regress-30.txt

### ISSUE THREAD

**Issue by rathann** [WebAssembly/wabt#1180]
When running the testsuite of 1.0.12, I'm getting this exception when `run_tests.py` is processing `test/regress/regress-30.txt`:

```
$ python3 -V
Python 3.7.4
$ test/run-tests.py --timeout=20 
Traceback (most recent call last):
  File "test/run-tests.py", line 952, in <module>
    sys.exit(main(sys.argv[1:]))
  File "test/run-tests.py", line 909, in main
    infos = GetAllTestInfo(test_names, status)
  File "test/run-tests.py", line 664, in GetAllTestInfo
    info.Parse(test_name)
  File "test/run-tests.py", line 484, in Parse
    for line in f.readlines():
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 225: invalid start byte
```

**Comment by rathann** [comment]
It looks like the tests succeed with python 2.7 and I notice you're not testing with python3 at all:
https://github.com/WebAssembly/wabt/blob/master/.travis.yml#L51
```
      python: 2.7
```
That seems to be unwise given that python2 is almost EOL and most distributions have been shipping python3 for years and have switched to python3 by default or are in the process of doing so.

**Comment by yaotj** [comment]
` `
# 
## 
## ` `
# ********
# __
## 文娱

**Comment by sbc100** [comment]
I just ran into this too :(
