### ISSUE TITLE
Clarification of data segment compilation in wat2wasm

### ISSUE THREAD

**Issue by mseddon** [WebAssembly/wabt#1194]
When I ask `wat2wasm` (pulled about 4 days ago from master and built under windows) to compile the following:

`(data (i32.const 6) "Hello")`

I get a nice, well specified data segment which has a count of 1, an index of 0, and an `init_expr` with my `i32.const 6)` instruction followed by `end` (0xb) followed by a count and 6 bytes of data for my string.

However, when I write:

`(data "Hello")`

I get a count of 1, followed by an index of 1, and then a count of 6 and my data- there is no `init_expr`.

I am struggling to see where the specification defines the latter behaviour.  My disassembler currently botches this by treating memory indices that are not 0 (which are not defined in MVP) as not containing an init-expr, and assume that the data segment will be loaded at 0x0000 but this format seems undefined, and I am not happy guessing what to do here.

The [spec](https://webassembly.github.io/spec/core/binary/modules.html#data-section) seems to assume i will always have an expression, yet clearly I do not when I elide this from my data definition.

Personally I would have expected `wat2wasm` to have inserted "`(i32.const 0) (end)`" where the specification _appears to require_ an `init_expr` in the case I do not provide a const instruction myself, but I am still working through the spec so perhaps I am confused.

Certainly `wasm2wat` happily disassembles this module, and even more importantly, this module loads with no issues on all wasm platforms I have tried.

Can someone help clarify this behaviour?

**Comment by binji** [comment]
Whoops, this is allowed by the bulk memory feature, but it seems that the parser wasn't checking to see if the feature flag was enabled. I have a fix here: https://github.com/WebAssembly/wabt/pull/1203
