### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [WebAssembly/wabt#1212]
Greetings wabt developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can attach our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by Google-Autofuzz** [comment]
We can also help by starting the OSS-Fuzz integration process for you if lack of time. We just need a google email from you to send bugs to you when libfuzzer finds any.

**Comment by tlively** [comment]
Would wasm-waterfall@grotations.appspotmail.com work?

**Comment by Google-Autofuzz** [comment]
> Would [wasm-waterfall@grotations.appspotmail.com](mailto:wasm-waterfall@grotations.appspotmail.com) work?

Let me get start on it first. It should also work.

**Comment by Google-Autofuzz** [comment]
```
[ 30%] Building CXX object CMakeFiles/wabt.dir/src/option-parser.cc.o
/src/wabt/src/option-parser.cc:60:20: error: use of undeclared identifier 'WABT_VERSION_INFO'
    printf("%s\n", WABT_VERSION_INFO);
                   ^
1 error generated.
CMakeFiles/wabt.dir/build.make:686: recipe for target 'CMakeFiles/wabt.dir/src/option-parser.cc.o' failed
make[2]: *** [CMakeFiles/wabt.dir/src/option-parser.cc.o] Error 1
CMakeFiles/Makefile2:641: recipe for target 'CMakeFiles/wabt.dir/all' failed
make[1]: *** [CMakeFiles/wabt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
```
I tried to build the wabt project as suggested and got this error. Why am I getting an error that tells be there is an error in the CMakeFiles?

**Comment by sbc100** [comment]
wabt uses a slightly strange setup in that is use a top level `Makefile` to drive `cmake`-based build.   A little confusing but we find the top level Makefile helps us avoid having to remember the common cmake invocations.

The error is genrated because cmake is trying to build `CMakeFiles/wabt.dir/src/option-parser.cc.o` which itself lives in the cmake output tree (normally `out/clang/Debug/..`).   

`WABT_VERSION_INFO` should be defined in `config.h` in the cmake output tree.

**Comment by aardappel** [comment]
@sbc100 Might be good to remove that `Makefile` at some point, and stick the `cmake` invocation in the docs instead.. this will help simplifying the build in different environments (e.g. IDE's or Windows).

Also, I've seen the above error pop up on CI at some point, and was also confused where it comes from.

**Comment by sbc100** [comment]
I'm not sure, I kind of like being able to type `make` right after `git checkout`.   Its simpler than `mkdir out && cd out && cmake .. && ninja` .  Up to binji I guess.

Is it just the fact the errors ends with `Makefile:127: recipe for target 'all' failed` this is confusing?  Or something else?

**Comment by Google-Autofuzz** [comment]
````
+ for fuzzers in '$(find $SRC -name '\''*_fuzzer.cc'\'')'
++ basename -s .cc /src/wasm2wat_fuzzer.cc
+ fuzz_basename=wasm2wat_fuzzer
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I. -I../wabt/ /src/wasm2wat_fuzzer.cc -fsanitize=fuzzer ./out/clang/Debug/libwabt.a -o /out/wasm2wat_fuzzer
In file included from /src/wasm2wat_fuzzer.cc:15:
In file included from /src/wabt/src/binary-reader-ir.h:20:
./src/common.h:33:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.
````
I figured out the error above and was able to `make` the file. I am running into another error as shown above. The fuzzer we have include `src/common.h` file, which directs to `config.h` file. However, it was not able to find the `config.h` file. Where is this file? Thanks.

**Comment by sbc100** [comment]
`config.h` is generated from config.h.in by cmake in the build directory.     For example in my checkout I can see three:

```
$ find -iname config.h
./out/clang/Debug/config.h
./out/clang-i686/Debug/config.h
./out/gcc/Debug/config.h
```

**Comment by Google-Autofuzz** [comment]
````
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -Iinclude ./build/config.h /src/wasm2wat_fuzzer.cc -fsanitize=fuzzer ./build/libwabt.a -o /out/wasm2wat_fuzzer
clang-10: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang-10: error: cannot specify -o when generating multiple output files
Fuzzers build failed.
````
As what you suggested, I found the `config.h` file and included in. Then, I got the clang-10 error as shown above. Do you think I am missing any include files?  

Here is the `build.sh` I have written:
````
for fuzzers in $(find $SRC -name '*_fuzzer.cc'); do
  fuzz_basename=$(basename -s .cc $fuzzers)
  $CXX $CXXFLAGS -std=c++11 -Iinclude ./build/config.h \
  $fuzzers $LIB_FUZZING_ENGINE ./build/libwabt.a \
  -o $OUT/$fuzz_basename
done
````

**Comment by sbc100** [comment]
You don't want to pass the header directly to compiler like that.  The `-Ibuild` is probably what you want.

**Comment by Google-Autofuzz** [comment]
It is upstream to OSS-Fuzz and here is the link: https://github.com/google/oss-fuzz/pull/3035#issue-341152853. Please feel free to add more fuzzers to it and make changes. Thank you.

**Comment by sbc100** [comment]
Sweet!  Thank you

**Comment by sbc100** [comment]
I guess we can close this now?

**Comment by tlively** [comment]
Perhaps it would be a good idea to have a tracking issue for creating more fuzzers. Also, I wonder if we should add fuzzers for Binaryen as well.

**Comment by Google-Autofuzz** [comment]
If you guys would like to also upstream Binaryen to OSS-Fuzz, I am gladly to take a look when I am free and write a fuzzer for it. Are you referring to https://github.com/WebAssembly/binaryen? @tlively

**Comment by sbc100** [comment]
That sound great. I know there are already a bunch of fuzzing scripts in binaryen but running them on clusterfuzz sounds great.  @kripken what do you think?    Maybe open a separate issue there?

**Comment by kripken** [comment]
More fuzzing sounds good to me!

**Comment by tlively** [comment]
Yes, that’s the Binaryen I’m referring to. I started looking at adding a fuzzer for it during fuzz week, but I wasn’t sure how to write fuzzers in the OSS-Fuzz style that would get past the initial input validation to test more interesting code. @Google-Autofuzz, are there any good docs on how that works?

**Comment by Google-Autofuzz** [comment]
@tlively Preferably to talk about this internally and not here. I will ping you via hangout.

**Comment by dschuff** [comment]
using wasm-waterfall@grotations.appspotmail.com isn't good because when the fuzzer finds issues it CCs that address to the bugs that get created. But there's no actual Monorail user with that address. And the bug is not actually visible to anyone else. So those of us on that list get a notification, but are then unable to view the bug.

**Comment by Google-Autofuzz** [comment]
Is there another email that works the best to view the bugs? Preferably a Google email. @dschuff

**Comment by dschuff** [comment]
When @binji gets back in office, he might want to take over as the contact for wabt, but for now, let's do dschuff@chromium.org

**Comment by dschuff** [comment]
(also, would someone that actually has access to the existing bugs be able to reassign them? thanks!)

**Comment by Google-Autofuzz** [comment]
It has been merged to OSS-Fuzz. You can go on and change the contact information as you like. https://github.com/google/oss-fuzz/pull/3035#issue-341152853

**Comment by binji** [comment]
> When @binji gets back in office, he might want to take over as the contact for wabt, but for now, let's do [dschuff@chromium.org](mailto:dschuff@chromium.org)

/me :wave:
