### ISSUE TITLE
Formatting of `v8x16.shuffle` has some extraneous whitespace

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1227]
Given a module like:

```wat
(module
  (func (param v128) (result v128)
    local.get 0
    local.get 0
    v8x16.shuffle 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0))
```

I get:

```
$ wat2wasm foo.wat -o foo.wasm --enable-simd
$ wasm2wat ./foo.wasm --enable-simd
(module
  (type (;0;) (func (param v128) (result v128)))
  (func (;0;) (type 0) (param v128) (result v128)
    local.get 0
    local.get 0
    v8x16.shuffle  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 ))
```

There's two spaces between each lane in the shuffle instruction, and a trailing space afterwards. A pretty minor issue, but figured it may be worth bringing up!

**Comment by amirbawab** [comment]
I checked the code responsible for the extra space:
https://github.com/WebAssembly/wabt/blob/e098f4c22f4630dab830a032612532ab7baa9ff9/src/wat-writer.cc#L938
You can see the space preceding the `%u` in the formatted string. I tried removing this space. It works, however the output looks as follow:
```
(module
  (func (;0;) (param v128)
    local.get 0
    local.get 0
    v8x16.shuffle 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 )
  (type (;0;) (func (param v128))))
```
Notice that we still have the space following the last `0`.  
Looking into the `Writef` function:
https://github.com/WebAssembly/wabt/blob/e098f4c22f4630dab830a032612532ab7baa9ff9/src/wat-writer.cc#L238-L243
By default the current implementation adds a space by after the input string.  
I suggest that the signature for `Writef` allows configuring the next char. However, I'm afraid some refactoring is necessary (?).  
Is there another function or solution that I missed? I'm interested in learning about alternative approaches.

**Comment by binji** [comment]
I think you can use `WriteNewline(NO_FORCE_NEWLINE)` instead of `WritePutsNewline("")` in the `OnSimd*OpExpr` functions to fix it.

I don't see any tests for this though, so if you send a PR, please add one! :)
