### ISSUE TITLE
Getting errors on memory.grow and memory.size on https://webassembly.studio/

### ISSUE THREAD

**Issue by theblockstalk** [WebAssembly/wabt#1274]
I create a new Wat project in 

I edit a wat file with memory.grow and memory.size, such as the one below (just for illustration):
```
(module
  (func $add (param $lhs i32) (param $rhs i32) (result i32)
    get_local $lhs
    get_local $rhs
    memory.grow
    memory.size
    i32.add)
  (export "add" (func $add))
)
```

and on build this gets the following errors
```
test.wat:5:5: error: unexpected token memory.grow, expected ).
    memory.grow
test.wat:6:5: error: unexpected token memory.size.
    memory.size
```

These are the same errors reported in
https://github.com/WebAssembly/wabt/issues/852

Perhaps you need to update to the latest version of wabt in Studio?

**Comment by binji** [comment]
You might want to try filing an issue here: https://github.com/wasdk/WebAssemblyStudio

**Comment by theblockstalk** [comment]
done, please close
