### ISSUE TITLE
wasm2wat produces 'error: invalid section code: 12'

### ISSUE THREAD

**Issue by voadere** [WebAssembly/wabt#1292]
I am converting some c++ code to wasm with em++ as follows
   em++ -o enums.wasm -c -s WASM -s STANDALONE_WASM=1 -std=c++17 -g -O2 enums.cpp

Then I want to produce readable text as follows:
  wasm2wat enums.wasm -o enums.wat

Which results in an error:
  0000270: error: invalid section code: 12

In the doc the highest section number is 11.

How can I further investigate this?
Or is this a known problem?

**Comment by voadere** [comment]
I have boiled it down to the followingcode:

#include <vector>
std::vector<int> objects;

**Comment by voadere** [comment]
Oops, I closed it by accident.

**Comment by binji** [comment]
`wasm2wat` is conservative by default, and won't read modules that use newer features. Try running `wasm2wat --enable-all` and see if that helps.

**Comment by voadere** [comment]
Thanks!
It works now.
