### ISSUE TITLE
wasm-objdump: Missing support for i16x8.widen_low_i8x16_s et al

### ISSUE THREAD

**Issue by zeux** [WebAssembly/wabt#1300]
It looks like narrow and widen instructions aren't supported by the disassembler, so getting errors like this:

> 00009c3: error: unexpected opcode: 0xfd 0xca 0x1

[decoder_simd.zip](https://github.com/WebAssembly/wabt/files/4051426/decoder_simd.zip)

**Comment by binji** [comment]
Thanks, looks like these were added not too long ago. #1301 adds these to wabt.
