### ISSUE TITLE
WebAssembly.compile(): unexpected section <DataCount>

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1311]
With release 1.0.13 the tool wat2wasm.exe with the command line parameter "--enable-reference-types" produce ever a DataCount section with zero entries.

Is this expected? I would expected that an empty section is not written never to reduce size and prevent such problems.

Are there any workarounds with wat2wasm to prevent this? I know I can switch back to version 1.0.12.

**Comment by Horcrux7** [comment]
A workaround for me is to add `--experimental-wasm-bulk-memory` to the node command line.

**Comment by binji** [comment]
Yeah, I made `--enable-reference-types` automatically include `--enable-bulk-memory`. But you're right, it probably shouldn't include the DataCount section unless it is required, as described here: https://github.com/WebAssembly/wabt/issues/1189.

**Comment by binji** [comment]
Fixed in #1312.
