### ISSUE TITLE
wabt fails to build from source because of missing wasm.h

### ISSUE THREAD

**Issue by apoleon** [WebAssembly/wabt#1315]
When I try to build wabt 1.0.13 from source, the build fails because wasm.h is not present in the source package.

I know that wasm.h is present in binaryen, but I don't understand how 

src/interp/interp-wasm-c-api.cc

can be built from source in wabt without wasm.h.

In version 1.0.12 wasm.h was not required to compile interp-wasm-c-api.cc.

Please clarify how to build wabt from source in version 1.0.13

**Comment by sbc100** [comment]
That header comes from `third_party/wasm-c-api` which is a git submodule.  So you need to run `git submodule update --init` so equiv.

**Comment by apoleon** [comment]
Interesting. Thanks for the reply. However the files are not present in the release tarball from
https://github.com/WebAssembly/wabt/releases

Maybe someone wants to fix that.

**Comment by sbc100** [comment]
Annoying.  Github releases are simply missing this feature: https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073

**Comment by sbc100** [comment]
I guess the only solution is to create out own source code archive that will sit alongside the default source code archives (which appear to be immutable).

**Comment by rofl0r** [comment]
> I guess the only solution is to create out own source code archive

yes, indeed. i wonder why it's no problem to create binary release tarballs, but such a 
reluctance to run a 5 line shell script to create a proper source release tarball rather than relying on the broken github tarball-from-tag feature ?

**Comment by rofl0r** [comment]
btw, the build of latest tagged release 1.0.20 succeeds after downloading only the single file https://raw.githubusercontent.com/WebAssembly/wasm-c-api/d9a80099d
/include/wasm.h , no other git submodules seem to be necessary.

**Comment by sbc100** [comment]
If you would like to contribute to the CI script to automatically upload full source archives I imagine that would be welcome contribution.

**Comment by rofl0r** [comment]
@sbc100 done, see pr linked above

**Comment by apoleon** [comment]
The new release, 1.0.21, still doesn't contain the wasm.h header file. Neither https://github.com/WebAssembly/wabt/releases/download/1.0.21/wabt-1.0.21.tar.xz nor https://github.com/WebAssembly/wabt/archive/1.0.21.tar.gz ships this file.

**Comment by rofl0r** [comment]
well, in the one i just downloaded it is contained.
```
~/tmp $ wget https://github.com/WebAssembly/wabt/releases/download/1.0.21/wabt-1.0.21.tar.xz
~/tmp $ tar xf wabt-1.0.21.tar.xz 
~/tmp $ cd wabt-1.0.21/
~/tmp/wabt-1.0.21 $ find -name wasm.h
./third_party/wasm-c-api/include/wasm.h
```

**Comment by apoleon** [comment]
src/interp/interp-wasm-c-api.cc references include <wasm.h> but I need to use #include "src/interp/wasm.h"
 to make the build work on Debian systems. wasm.h should be installed into src/nterp/ and not into the third_party directory IMHO.

**Comment by rofl0r** [comment]
that's not quite the same as "the file doesnt exist".
for the record, 14 days ago when i packaged wabt for my distro i had to put the wasm.h exactly into third_party directory to get it picked up from the build system: https://github.com/sabotage-linux/sabotage/commit/c8e11fbb97c7859465ad47db37c775fa1eff0bd9#diff-e96737aab7b60dccf8152b06e9fe599dbf4b1b1129cd61cad87c19cf98c130b8R19
that's so because -Ithird_party/whatever is added to CXXFLAGS/CPPFLAGS during build.
unless you produce a build log from 1.0.21 tar.xz showing an error i'd say this is PEBKAC.

**Comment by apoleon** [comment]
This bug is not resolved in Debian, The wasm.h header file is not a global header file, so I don't understand why you include it in  src/interp/interp-wasm-c-api.cc like that: include <wasm.h>

It really should be installed into src/interp and you need to change the include to #include "src/interp/wasm.h". Everything else is plain wrong.

**Comment by rofl0r** [comment]
> why you include it in src/interp/interp-wasm-c-api.cc like that: include <wasm.h>

because there's such a thing as a compiler flags.

> It really should be installed into src/interp and you need to change the include to #include "src/interp/wasm.h". Everything else is plain wrong.

nope, **you** are wrong. how about you just try to build it from the tarball, following the build instructions ? if you do it right the build will suceed, and if you enable a verbose build (see my recipe linked above for how to do that), you will see this line in your log:

```
/bin/g++  -DWASM_API_EXTERN="__attribute__((visibility(\"default\")))" -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -Dwasm_EXPORTS -I/src/build/wabt/wabt-1.0.20 -I/src/build/wabt/wabt-1.0.20/build -I/src/build/wabt/wabt-1.0.20/third_party/wasm-c-api/include  -Os -g0 -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -fno-math-errno -mtune=generic -std=c++11 -Wold-style-cast -fno-exceptions -fPIC -fvisibility=hidden   -Wall -Wextra -Wno-unused-parameter -Wpointer-arith -g -Wuninitialized -Wno-clobbered -Wno-old-style-cast -o CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o -c /src/build/wabt/wabt-1.0.20/src/interp/interp-wasm-c-api.cc
```
the `-I/src/build/wabt/wabt-1.0.20/third_party/wasm-c-api/include` part in that command produced automatically by the build system makes it so `#include <wasm.h>` works.

**Comment by apoleon** [comment]
Linux distributions use system libraries to build packages. They don't use embedded third_party libraries. Your assumptions are wrong. wasm.h should never be a third_party header file and the package fails to build from source on a standard Debian system. I highly recommend to install the wasm.h header file into src/interp. Your assumption that -I/src/build/wabt/wabt-1.0.20/third_party/wasm-c-api/include should work on all systems is wrong. Please don't rely on embedded code copies of unrelated projects.

**Comment by rofl0r** [comment]
> Linux distributions use system libraries to build packages.

orly. you telling me, which i do maintain my own linux distro. ok, go on...

> the package fails to build from source on a standard Debian system.

so provide build logs to figure out what goes wrong

> Your assumption that -I/src/build/wabt/wabt-1.0.20/third_party/wasm-c-api/include should work on all systems is wrong.

well, as you can see CMake made the relative path absolute so naturally that specific absolute path will only work iff you extract the sources to "/src/build/wabt/wabt-1.0.20".
on your machine, it will make that another absolute path, but the point is that it's pointing to where wasm.h is. :)

**Comment by sbc100** [comment]
> Linux distributions use system libraries to build packages. They don't use embedded third_party libraries. Your assumptions are wrong. wasm.h should never be a third_party header file and the package fails to build from source on a standard Debian system. I highly recommend to install the wasm.h header file into src/interp. Your assumption that -I/src/build/wabt/wabt-1.0.20/third_party/wasm-c-api/include should work on all systems is wrong. Please don't rely on embedded code copies of unrelated projects.

wasm.h was only added to release archive in 1.0.21 (see #1615).   You also need to make sure you download `wabt-1.0.21.tar.xz` rather than auto-generated archive from github.

Regarding the embedded header:  If you would like to separately package the `wasm-c-api` project and have your wabt package depend on that I should work out.   I'm not sure its worth the effort (especially singe wasm-c-api doesn't have any releases to speak of) but that is up to you of course.
