### ISSUE TITLE
Can't decode LLVM-built i8x16.shuffle

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wabt#1339]
LLVM still builds code using the old encoding for `i8x16.shuffle`--`0xfd03`. WABT expects code to have the [new encoding](https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md)--`0xfdc1`. Over in an [emscripten issue](https://github.com/emscripten-core/emscripten/issues/9281#issuecomment-589339146), @tlively mentioned that he would prefer to wait to modify all of the LLVM-emitted encodings until after all the encodings are renumbered. In the meantime, could we modify WABT to allow both `0xfd03` and `0xfdc1` to parse as `i8x16.shuffle`? Otherwise the WABT tools can't really be used to look at LLVM Wasm SIMD code (and I like WABT!).

I took a stab at this but quickly ran into things I don't yet understand about WABT. I wouldn't mind doing the work to get this working if 1) you all agree this type of temporary hack can be allowed (similar code exists in [wasmparser.rs](https://github.com/bytecodealliance/wasmparser/blob/4789a9cadd6390579df8574b4e2bba810d428fe9/src/binary_reader.rs#L1562-L1568)), and 2) someone can help me understand what I don't understand about `infos_` (and probably other locations that need changing):

```diff
diff --git a/src/opcode-code-table.c b/src/opcode-code-table.c
index c3e06d03..dcdbc060 100644
--- a/src/opcode-code-table.c
+++ b/src/opcode-code-table.c
@@ -38,4 +38,6 @@ uint32_t WabtOpcodeCodeTable[WABT_OPCODE_CODE_TABLE_SIZE] = {
   [(prefix << 8) + code] = Name,
 #include "opcode.def"
 #undef WABT_OPCODE
+  // FIXME: alias V8X16Shuffle (currently numbered as 0xfdc1) to its previous opcode (0xfd03); remove when SIMD instructions are renumbered
+  [(0xfd << 8) + 0x03] = V8X16Shuffle,
 };
diff --git a/src/opcode.cc b/src/opcode.cc
index 5327f4b4..46d91e0b 100644
--- a/src/opcode.cc
+++ b/src/opcode.cc
@@ -30,6 +30,8 @@ Opcode::Info Opcode::infos_[] = {
 #include "src/opcode.def"
 #undef WABT_OPCODE
 
+  // FIXME: alias V8X16Shuffle (currently numbered as 0xfdc1) to its previous opcode (0xfd03); remove when SIMD instructions are renumbered
+  {"v8x16.shuffle", "", Type::V128, Type::V128, Type::V128, Type::___, 0, 0xfd, 0x03, PrefixCode(0xfd, 0x03)},
   {"<invalid>", "", Type::Void, Type::Void, Type::Void, Type::Void, 0, 0, 0, 0},
 };
```

**Comment by binji** [comment]
Seems reasonable, I'll take a look at adding support for this!

**Comment by binji** [comment]
Fixed by reverting to the old opcode.

**Comment by abrown** [comment]
Thanks!
