### ISSUE TITLE
wasm-objdump: i32x4.max_s et al are not supported

### ISSUE THREAD

**Issue by zeux** [WebAssembly/wabt#1343]
Attaching example that fails to disassemble with 

> 000023c: error: unexpected opcode: 0xfd 0x82 0x1

[decoder_simd.wasm.zip](https://github.com/WebAssembly/wabt/files/4238833/decoder_simd.wasm.zip)

**Comment by binji** [comment]
Those instructions were added here: https://github.com/WebAssembly/wabt/pull/1317

I tried your example with wabt at HEAD and it seemed to work. Can you try and see if that works for you?

**Comment by zeux** [comment]
Oh... I did try syncing with latest and building wabt, but I think I mixed up the build artifacts with ones from the prior run. After building wasm-objdump again it works fine, sorry for the false alarm!
