### ISSUE TITLE
Update to more recent test suite

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/wabt#1379]
I would be nice to get https://github.com/WebAssembly/simd/pull/197 into wabt.  Though this seems to require the proposals test suite to be updated upstream first.  @sbc100 ?

**Comment by sbc100** [comment]
Looks like big chunk landed yesterday with: https://github.com/WebAssembly/wabt/pull/1373. 

But yes it looks like the testsuite wasn't up-to-date enough.  Update is here: https://github.com/WebAssembly/testsuite/pull/24

**Comment by binji** [comment]
Yeah, sorry about that. The simd fixes were harder than I expected :)

**Comment by binji** [comment]
Updated in https://github.com/WebAssembly/wabt/pull/1381.
