### ISSUE TITLE
The "Legacy active, funcref elemexpr" element segment  not supported in wat2wasm.

### ISSUE THREAD

**Issue by libwasm** [WebAssembly/wabt#1391]
The "Legacy active, funcref elemexpr" element segment  (flag = 4) is not supported in wat2wasm.

It is however supported in wasm2wat.

**Comment by libwasm** [comment]
An example:
$cat test.wast
(module
  (func $f)
  (table 3 funcref)
  (elem (;0;) (i32.const 1) (ref.func 0) (ref.null))
)
$wat2wasm --enable-all test.wast
test.wast:4:29: error: unexpected token (, expected ).
  (elem (;0;) (i32.const 1) (ref.func 0) (ref.null))

This should create an element with flag=4

**Comment by binji** [comment]
I think this is invalid syntax; the reference interpreter also doesn't accept it:

```sh
$ ./wasm test.wat -o test.wasm
test.wat:4.29-4.30: syntax error: unexpected token
```

It needs to have the element type after the offset:

```wasm
(module
  (func $f)
  (table 3 funcref)
  (elem (;0;) (i32.const 1) funcref (ref.func 0) (ref.null))
)
```

This works in `wat2wasm` and the reference interpreter, and generates a module with flag=4:

```sh
$ wasm-objdump test.wasm -x

test.wasm:	file format wasm 0x1

Section Details:

Type[1]:
 - type[0] () -> nil
Function[1]:
 - func[0] sig=0
Table[1]:
 - table[0] type=funcref initial=3
Elem[1]:
 - segment[0] flags=4 table=0 count=2 - init i32=1
  - elem[1] = func[0]
  - elem[2] = nullref
Code[1]:
 - func[0] size=2

```

**Comment by libwasm** [comment]
Thanks for your response.

I'll implement it that way.
