### ISSUE TITLE
Can we have a wasm framework?

### ISSUE THREAD

**Issue by VBAndCs** [WebAssembly/wabt#1394]
I think wasm should have a framework that all browsers use. It should contain 
- all the common numeric, literal and date type operations and casting.
- Dom manipulation operations. 
- sending requests to the server if needs (like Ajax).

Isn't this all what we need from client code?
If this wasm framework contained in all browsers, this will targeting wasm from web technologies easier, since there will be no need to download anything to the client except a pure wasm code targeting this framework.
Without a wasm framework, it will can be a mess in the client machine, due to thousands of dlls and runtimes coming from hundreds of sites using different web technologies targeting wasm. Over time, it can consume the client storage very badly.
Web technologies like Blazer can have a wrapper to this wasm framework, that actually doesn't contain any code but the classes and method signatures, so developers can target this wrapper in manage code. This wrapper can provide the same names of .NET methods and classes can have the same names but staring with Wasm, such as WasmString, or belong to the Wasm namespace such as Wasm.String. This will make it very familiar and need zero time to learn.
If the wasm framework doesn't contain some advance or repeated functionality, we can write more classes targeting wasm framework, and download the dll to the client. this will minimal as the browser already has the common wasm framework used by all web technologies.
Is this possible and doable? Can it be better (less size and faster in development and production)?

**Comment by binji** [comment]
Yes, we definitely want to support others writing frameworks like these. We wouldn't want them to be built-in to browsers, though. Instead the idea would be to make WebAssembly better at using the existing web APIs. That's one of the primary purposes of the [interface types proposal](https://github.com/webassembly/interface-types).

You may want to take a look at the [explainer](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) in that proposal to see if it matches what you're thinking. In any case, this repo is for a suite of wasm tools, so isn't really an appropriate place for this discussion. A better general place for discussion like this would be the [design repo](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) if the interface types proposal doesn't quite match your idea.
