### ISSUE TITLE
Failing to compile GC branch

### ISSUE THREAD

**Issue by sabine** [WebAssembly/wabt#1395]
I tried to build the gc branch using CMake directly, as described in the README.

The build fails with
```
In file included from /[..]/wabt/src/shared-validator.cc:17:
/[..]/wabt/src/shared-validator.h:194:47:
error: ‘MutVector’ does not name a type; did you mean ‘VarVector’?
  194 |     StructType(const TypeVector& types, const MutVector& muts)
      |                                               ^~~~~~~~~
      |                                               VarVector
```
on Debian unstable at commit b7e318e47a2784cd09e7be1489c902c4ea562525.

Reason I'm trying to run this: experimenting with compiling to WASM+GCMVP and looking for something to run the emitted code.

**Comment by binji** [comment]
Thanks for mentioning! It seems I had it fixed locally but didn't push it upstream. I've now rebased against `master`, and force pushed that over the `gc` branch. Give it a try and tell me if it works.

**Comment by sabine** [comment]
Works perfectly fine now, thank you. Sorry about the delay.
