### ISSUE TITLE
wasm2wat crashes upon reaching SIMD instructions

### ISSUE THREAD

**Issue by GirkovArpa** [WebAssembly/wabt#1396]
I tried to decompile a Wasm file that contains SIMD instructions to Wat and got this error:

```
Error: readWasm failed:
0000039: error: expected valid local type
```

**Comment by lars-t-hansen** [comment]
Did you remember to --enable-simd?

**Comment by binji** [comment]
Yes, it seems like you're missing the `--enable-simd` flag. As a side-note, the tools should be friendlier here, and suggest feature flag when they find features. You may also want to try `wasm-objdump`, which is always run with all features enabled (it tries to be permissive as possible).

**Comment by RReverser** [comment]
> it tries to be permissive as possible

FWIW it's possible to do this in wasm2wat with `--enable-all` as well. I sometimes wonder if it should be the default.

**Comment by GirkovArpa** [comment]
I'm actually using the online demo, because I can't get it to work on my computer.  I suppose the demo doesn't support parameters?

**Comment by aardappel** [comment]
When using `wasm2wat` (or `wasm-decompile`) whoever created the `.wasm` already decided to use SIMD or not, so there's little point in these tools failing on them (or at least could be behind a `--disable-` flag.

For `wat2wasm` it makes a bit more sense, but even there the chance of accidentally using a SIMD feature you didn't intend (and then causing problems for a downstream consumer) sound somewhat hypothetical.

So I am kinda in favor of default on for all tools. If not at least for all that read existing `.wasm`.

**Comment by GirkovArpa** [comment]
I'm trying to decompile my own SIMD WASM to learn how SIMD instructions correlate to vanilla instructions so I can figure out how to write them in C++.

**Comment by GirkovArpa** [comment]
I found working binaries in the Releases.

**Comment by GirkovArpa** [comment]
I'm getting this error:
```
0000090: error: unexpected opcode: 0xfd 0x3
```
Using these flags:
```
"./wasm2wat.exe" "index.wasm" -o "index.wat" --enable-all
```
On a simple Wasm file that contains SIMD instructions.

**Comment by binji** [comment]
@aardappel One drawback is that how the binary is parsed can be slightly different with and without some features. And some features are _very_ experimental, so I wouldn't want to enable them by default generally. But yeah, in general the experience here should be nicer.

@GirkovArpa I think this is failing because the JS demo (and the Releases) haven't been updated in a while. In particular, #1342 renumbered `v8x16.shuffle` back to `0xfd 0x03`, and that was in February. This is going to change again anyway (see https://github.com/WebAssembly/simd/pull/209), but in the meantime I can update the web demo, and push a new release.

**Comment by GirkovArpa** [comment]
That would be awesome!

**Comment by aardappel** [comment]
@binji ok, then maybe have a default set which experimental features graduate to once they've reached a certain level of maturity?

**Comment by binji** [comment]
I think that's a good idea, I was actually just thinking that the features that have now become standardized (multi-value, nontrapping-float-to-int, sign-extension-ops) should probably be default now, just like mutable-globals.
