### ISSUE TITLE
`wasm2wat` may produce un-parseable WAT syntax with parameter names

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1417]
Given an input such as:

```wasm 
(module (func (param i32) (param $b i32)))
```

This round-trip through tooling fails to succeed:

```
$ wat2wasm --debug-names foo.wat -o foo.wasm
$ wasm2wat foo.wasm > bar.wat
$ wat2wasm bar.wat -o bar.wasm
bar.wat:3:35: error: unexpected token $b, expected ).
  (func (;0;) (type 0) (param i32 $b i32)))
```

I think that parameter printing needs to terminate the previous `(param ...)` group whenever it prints a parameter with a name?

**Comment by binji** [comment]
Good catch! Fix here: https://github.com/WebAssembly/wabt/pull/1418

**Comment by alexcrichton** [comment]
Fixed in https://github.com/WebAssembly/wabt/pull/1418
