### ISSUE TITLE
wasm2c: function name mangling?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#1426]
Right now compiling a wasm with a function called `main` leads to clang complaining about
```cpp
static u32 main(u32, u32);

static u32 main(u32, u32) {
  .. impl ..
}
```

```cpp
a.c:179:1: warning: 'main' should not be declared static [-Wmain]
static u32 main(u32, u32);
^~~~~~~
a.c:179:8: warning: return type of 'main' is not 'int' [-Wmain-return-type]
static u32 main(u32, u32);
       ^
a.c:179:8: note: change return type to 'int'
static u32 main(u32, u32);
       ^~~
       int
a.c:179:12: error: first parameter of 'main' (argument count) must be of type 'int'
static u32 main(u32, u32);
           ^
a.c:179:12: error: second parameter of 'main' (argument array) must be of type 'char **'
```

Despite `main` being declared static, and in its own file where there isn't an actual `main`, it thinks it's a bad declaration of `main`. Similar things can probably happen with other libc things that clang warns about redeclarations of.

Perhaps all function names should be mangled, say by adding a `_` prefix to them? As this is just for the `static` impls, and not seen by the outside, this doesn't seem too bad maybe, but it would make it a little less readable.

**Comment by binji** [comment]
Yes, that's right. Originally I tried to keep the names the same if possible, and have a list of names that aren't allowed. But that's silly, it really should mangle all names instead, as you say.

**Comment by kripken** [comment]
Cool, I'll take a look at doing this.
