### ISSUE TITLE
wasm-decompile link in README is broken

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/wabt#1428]
On main page: https://github.com/WebAssembly/wabt the link to wasm-decompile doc is broken https://webassembly.github.io/wabt/doc/wasm-decompile.1.html
I think it is missing from https://github.com/WebAssembly/wabt/tree/master/docs/doc

**Comment by aardappel** [comment]
Sounds like something needs to be regenerated from the man pages? The source is here: https://github.com/WebAssembly/wabt/tree/master/man
Where is the script for this? I see nothing in `scripts`.. @binji?

**Comment by binji** [comment]
There are quite a few tools to convert man pages to html, but tbh I don't know which one was used here. I tried groff, man2html, and pandoc, but all of them seem to generate different html than the ones here. Any other ideas?

**Comment by ngzhian** [comment]
I got pretty close with https://mandoc.bsd.lv/, it was missing hyperlinks to the other tools, and also some css class changes, which I think has to do with the version of mandoc I was using.

**Comment by aardappel** [comment]
Maybe add that as a script?

**Comment by keithw** [comment]
Fixed in #1592
