### ISSUE TITLE
Global usage error

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#143]
I tried to build [emscripten's hello world wast](https://gist.github.com/kripken/661d24692e183f423390e39263607157) into wasm, but I get errors like

````
a.out.wast:65:3: global can only be defined in terms of a previously defined global.
  (global $STACKTOP (mut i32) (get_global $STACKTOP$asm2wasm$import))
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

The relevant lines are 

````
  (import "env" "STACKTOP" (global $STACKTOP$asm2wasm$import i32))
[..]
  (global $STACKTOP (mut i32) (get_global $STACKTOP$asm2wasm$import))
````

and that error was on the last line there.

I think that wast code should be valid? We import `$STACKTOP$asm2wasm$import`, then use it to init a mutable global (asm2wasm needs mutable imports, so first we import, then assign to a mutable since imports can't be mutable).

**Comment by binji** [comment]
Yeah, there's a bug here. My guess is that it comes from merging the index space with imported and defined globals, though I have inspected it yet.
