### ISSUE TITLE
prelease blocking the homebrew formula upgrade

### ISSUE THREAD

**Issue by chenrui333** [WebAssembly/wabt#1439]
relates to https://github.com/Homebrew/homebrew-core/pull/55046

Just want to point out that the prerelease tag failed the homebrew audit check, let me know if that is intentional. Thanks!

**Comment by binji** [comment]
cc @sbc100 

Yes, version 1.0.16 is a test of using GitHub CI to create the build artifacts for a release. It seems as though it didn't work, so it's best to hold off for now, I think.

**Comment by chenrui333** [comment]
> cc @sbc100
> 
> Yes, version 1.0.16 is a test of using GitHub CI to create the build artifacts for a release. It seems as though it didn't work, so it's best to hold off for now, I think.

Cool, thanks for confirming it.

**Comment by sbc100** [comment]
Was the failure due to the lack of artifacts, or is there some other build failure that is actually going to be problem for you?

**Comment by binji** [comment]
It seems like it was blocked from the homebrew update because 1.0.16 is a pre-release, see https://github.com/Homebrew/homebrew-core/pull/55046#issuecomment-631945818

**Comment by sbc100** [comment]
Ah.. that doesn't seem like a bug at our end.    Its merely a reflection of reality, no?     Why shouldn't we have a pre-release period?

**Comment by sbc100** [comment]
(the fact that our releases are broken is another issue :)

**Comment by chenrui333** [comment]
It is not a bug though, but more like a question :)

Homebrew side does not like shipping upgrades with prerelease tag, that is why I raised in here regarding the release cycle matter.

**Comment by sbc100** [comment]
I think homebrew is correct in not wanting to ship pre-releases.    

I guess my question is, why would homebrew even consider doing this?  Can we  train homebrew to simply ignore the pre-releases?

**Comment by sbc100** [comment]
Oh, and BTW I'm very exited to make some improvements to the homebrew package!   If you are the maintainer perhaps we can work together to fix a few things?

1. Switch to llvm upstream
2. Drop fastcomp completely? (maybe a little premature but maybe we can do it)
3. Swtich to embedded config file (avoid the need for $HOME config file!)
4. Ship some pre-built libraries such as libc etc

Even without any of those changes it would be great to have you around to help with homebrew issues the come on this tracker from time to time.

**Comment by sbc100** [comment]
Doh, ignore that last comment.. I was thinking this was an emscripten issue, but its wabt (unless you are also the maintainer of emscripten in homebrew?)

**Comment by chenrui333** [comment]
> Oh, and BTW I'm very exited to make some improvements to the homebrew package! If you are the maintainer perhaps we can work together to fix a few things?
> 
> 1. Switch to llvm upstream
> 2. Drop fastcomp completely? (maybe a little premature but maybe we can do it)
> 3. Swtich to embedded config file (avoid the need for $HOME config file!)
> 4. Ship some pre-built libraries such as libc etc
> 
> Even without any of those changes it would be great to have you around to help with homebrew issues the come on this tracker from time to time.

yeah, I am the maintainer for homebrew-core project, feel free to kick off a PR, and we can improve from there. :)

**Comment by chenrui333** [comment]
> I think homebrew is correct in not wanting to ship pre-releases.
> 
> I guess my question is, why would homebrew even consider doing this? Can we train homebrew to simply ignore the pre-releases?

simply because we just want to ship the latest/stable release (from software UX perspective)

We do provide something called install from HEAD though (which is latest and greatest)

**Comment by chenrui333** [comment]
I think this is no longer an issue, closing it now.
