### ISSUE TITLE
wasm2wat: Missing `declare` on elem segments with expressions

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1449]
Given this input:

```
(module
  (table $t 10 funcref)
  (elem declare funcref (ref.func $f) (ref.func $f) (ref.null func) (ref.func $g))
  (func $f)
  (func $g)
)
```

this round trips as:

```
$ wat2wasm foo.wat -o foo.wasm --enable-all
$ wasm2wat foo.wasm --enable-all
(module
  (type (;0;) (func))
  (func (;0;) (type 0))
  (func (;1;) (type 0))
  (table (;0;) 10 funcref)
  (elem (;0;) funcref (ref.func 0) (ref.func 0) (ref.null func) (ref.func 1)))
```

The `elem` segment here, however, I think is missing the `declare`. I believe that the binary itself has the right encoding, it's just the printing which loses it.

Also FWIW I feel like I'm opening a lot of minor and nitpickity issues. If this is too much please let me know and I can set aside these issues until I get a chance to submit fixes myself!

**Comment by binji** [comment]
> Also FWIW I feel like I'm opening a lot of minor and nitpickity issues. If this is too much please let me know and I can set aside these issues until I get a chance to submit fixes myself!

No, thank you for reporting these! They're definitely not nitpicky.
