### ISSUE TITLE
Version is wrong

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1463]
The printed version is wrong. If I call `wat2wasm.exe --version` then download release 1.0.15 print

`1.0.13 (1.0.14)`

If I build the trunk version then it print

`1.0.13 (gh-actions-test2)`

Sounds like the version was never incremented.

**Comment by binji** [comment]
Thanks, it looks like we get this from the `CMAKE_PROJECT_VERSION`, so I'll have to remember to update that when we push new versions.

**Comment by Horcrux7** [comment]
On Windows the version is now `1.0.13 (1.0.17)`.

**Comment by binji** [comment]
Drat, I forgot to update it again. OK, I'll push out a new release...

**Comment by Horcrux7** [comment]
A new release is not required. It is like a cosmetic thing. For my project I use a check list for the release. Else I would also forgot important things.
