### ISSUE TITLE
Performance of WABT Interpreter

### ISSUE THREAD

**Issue by Leonardo2718** [WebAssembly/wabt#1465]
I was wondering how important is performance to the WABT project, in particular the performance of the interpreter? Is it something that the project should actively try to improve upon?

While working on [wasmjit-omr](https://github.com/wasmjit-omr/wasmjit-omr) [1], we found that we could improve overall performance by modifying a few key parts of the VM (mostly involving linear memory and function dispatch). I am curious whether people here would be interested in having these changes upstreamed. I would be happy to spend the time working on it if people in the community feel that there are benefits to the WABT project.

I haven't been able to work on wasmjit-omr in a long while, but I'm hoping I will have more time available soonish. I will have to revisit a lot of the perf oriented work anyways to bring the project in sync with the new interpreter.

[1] [wasmjit-omr](https://github.com/wasmjit-omr/wasmjit-omr) was a university project a few classmates and I did about two years ago where we used [Eclipse OMR](https://github.com/eclipse/omr) to write a JIT compiler to go with the WABT interpreter. As part of that, we spent significant time analyzing its performance characteristics and optimizing it. Eventually, our JIT gained us ~145x performance improvement on a simple Mandelbrot benchmark over the interpreter by itself. Overall, our performance roughly matched (and even surpassed in some cases) that of a native executable generated by clang.

**Comment by binji** [comment]
Yeah, I remember your project and thinking it looked very cool!

> I was wondering how important is performance to the WABT project, in particular the performance of the interpreter?

It's somewhat important, though if I had to rank the priorities, they'd probably go:

1) conformance to spec
1) simplicity
1) performance

That said, a simpler interpreter would run on the wasm bytecode directly, so there already have been some concessions for performance here.

> I am curious whether people here would be interested in having these changes upstreamed.

Yes, I think it would be great! I have rewritten the interpreter in the past year, so you may have to make some modifications to your patch. And as mentioned above, I wouldn't want to add too much complexity to the interpreter for speed -- I guess it depends on the specific changes. Feel free to open a PR so we can discuss it.

**Comment by keithw** [comment]
Closing as dormant.
