### ISSUE TITLE
Support for eqref an other features of the GC MVP

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1469]
What is the status of the GC features? With version 1.0.17 I try:

```
(module
  (func $test(local $val eqref)
  )
)
```
I receive `error: unexpected token "eqref", expected i32, i64, f32, f64, v128 or externref.`

**Comment by binji** [comment]
I haven't gotten around to implementing those features yet. I've been wanting to make more progress, but have been pretty busy with other things.

**Comment by sbc100** [comment]
Closing as duplicate of #1257
