### ISSUE TITLE
Why i32 got convert to u32?

### ISSUE THREAD

**Issue by apiel** [WebAssembly/wabt#1476]
I have this function `(import "socket" "core.create_socket" (func $std/socket/core.create_socket (result i32)))` in my wat file but it get converted to `extern u32 (*Z_socketZ_coreZ2Ecreate_socketZ_iv)(void);` or I would expect `extern s32 (*Z_socketZ_coreZ2Ecreate_socketZ_iv)(void);`.

Shouldn't wasm `i32` become `s32` (int32_t) ?

**Comment by binji** [comment]
It looks like you're using `wasm2c`, is that right?

The `i32` in wasm represents a signless 32-bit value, so it best aligns with the `uint32_t` (AKA `u32`) type, since that type has well-defined behavior for overflow. You can cast it to an `s32` if you need the signed version instead.

**Comment by apiel** [comment]
> It looks like you're using wasm2c, is that right?
Yes.

Thx for the clarification. I have seen that I was able to return negative value and it was still working. So would this mean if I want to be concistant with my types, I should use int16_t (this would actually be the same as u32)?

**Comment by binji** [comment]
WebAssembly doesn't have a 16-bit type, so if you started with C and compiled to WebAssembly, it will convert it to a Wasm `i32` and mask off the high bits. See for example, https://godbolt.org/z/qN-qXU
