### ISSUE TITLE
wasm2c: signal handler doesn't always work (linux)

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#1478]
I'm not sure why it sometimes does and sometimes doesn't... the flakiness is preventing me from reducing the testcase.

STR:
```
clang main.c wasm.c $WABT/wasm2c/wasm-rt-impl.c -I$WABT/wasm2c -lm -g -DWASM_RT_MEMCHECK_SIGNAL_HANDLER=1
```
Running that, it segfaults as it tries to load from an invalid address,
```
do a load of one byte from 0xfffffe16 in a mem of size 0x10000
Segmentation fault
```
(the printf is on line 2051 of `wasm.c`).

With `-DWASM_RT_MEMCHECK_SIGNAL_HANDLER=0` it works as expected.

(binaryen fuzzer seed: `17121235161227891584`)

[wasm.c.gz](https://github.com/WebAssembly/wabt/files/4905047/wasm.c.gz)
[wasm.h.gz](https://github.com/WebAssembly/wabt/files/4905048/wasm.h.gz)
[main.c.gz](https://github.com/WebAssembly/wabt/files/4905049/main.c.gz)

**Comment by kripken** [comment]
May be related, when running in `gdb` I see no signals are handled by wasm2c. When outside of gdb, `func_31_invoker` does an OOB that the signal handles, then `func_43` does another, and that one is *not* handled.

**Comment by binji** [comment]
Ah, I actually saw this bug too. I think the problem is that you're calling `setjmp` instead of `sigsetjmp`. You can use the macro `WASM_RT_SETJMP` instead, which will choose between using `setjmp` and `sigsetjmp` depending on whether signal handling is enabled.

**Comment by kripken** [comment]
Thanks! I should learn more about signal handling...
