### ISSUE TITLE
Is the wabt in system package managers officially supported?

### ISSUE THREAD

**Issue by Evian-Zhang** [WebAssembly/wabt#1490]
The Readme in this repo suggests me to build the source code locally, but I prefer to use the system package manager to manage the tools, so that I can always upgrade to the latest version without checking the GitHub releases frequently.

I found wabt package in Ubuntu's apt and macOS's homebrew repository. After installing them, I use

```
wasm2wat --version
```

to check the version. The one downloaded from apt in Ubuntu shows `1.0.13`, and the one downloaded from homebrew in macOS shows `1.0.13 (1.0.17)`.

I wonder if the wabt I found in those system package managers is officially supported, and how is the newest version different from the GitHub newest release's version.

**Comment by sbc100** [comment]
Like most software its really up to the maintainers in each distro to support the packaged versions.    We don't do the work of actually creating the packages here but we certainly encourage and support those that do.

I don't see any reason not to use a packaged version of wabt, it should work just fine.

**Comment by Evian-Zhang** [comment]
> Like most software its really up to the maintainers in each distro to support the packaged versions. We don't do the work of actually creating the packages here but we certainly encourage and support those that do.
> 
> I don't see any reason not to use a packaged version of wabt, it should work just fine.

But the version of wabt in those package managers are still 1.0.13, which was released in 18 Jan. I really hope the maintainers in each distro can keep the version up with the GitHub releases.

**Comment by sbc100** [comment]
Linux distro packages often lag upstream releases by many months or years, but it really depends on the distro and how stable its trying to be.   If you want up-to-date versions you can choose a distro that focuses on staying up-to-date.  You can also reach out the package maintainers themselves if you think an update is due. 

But its not really an issue that upstream wabt is responsible for.
