### ISSUE TITLE
Question: Should `local.get $v` work when `$v` is the name of a parameter declared via a separate type?

### ISSUE THREAD

**Issue by sabine** [WebAssembly/wabt#1496]
```
(module
  (type $f_t (func (param $v i64) (result i64)))
  (func $f (type $f_t) (get_local $v))
)
```

```
test.wat:3:35: error: undefined local variable "$v"
  (func $f (type $f_t) (get_local $v))
```

`wat2wasm` currently doesn't accept that, and I don't know if it should.

I don't know if the WASM text format spec wants us to recognize that $v is declared in type $f_t.

Is it reasonable to refer to the name of a parameter in a separately-defined type, or should a producer generally emit wat that inlines the function type declarations into the function declaration?

**Comment by rossberg** [comment]
The example is working as intended and spec'ed, there is no implicit namespace injection. Parameter names in type definitions only have documentation value.

**Comment by binji** [comment]
See a similar discussion here: https://github.com/WebAssembly/design/issues/1338

**Comment by sabine** [comment]
Thank you!
