### ISSUE TITLE
[wasm2c] Truncation of values slightly less than INT32_MIN is wrong

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#1499]
Noticed by the binaryen fuzzer's wasm2c integration.

Background and testcase: https://github.com/WebAssembly/spec/issues/1224

Spec tests are added in https://github.com/WebAssembly/spec/pull/1225

**Comment by keithw** [comment]
I believe this was fixed in #1502, and wasm2c began passing the full `conversions.wast` test again after #1680
