### ISSUE TITLE
[wasm2c] C code is unable to compile, undefined reference to `WASI_xx`

### ISSUE THREAD

**Issue by RLee063** [WebAssembly/wabt#1510]
I'm new to WASM, I just want to reverse a WASM program. I tried to compile the C code generated by wasm2c, but I got some errors:
```
/usr/bin/ld: /tmp/ccZq4O8u.o: in function `w2c_f20':
program.c:(.text+0x1698): undefined reference to `Z_envZ_boomZ_vii'
/usr/bin/ld: /tmp/ccZq4O8u.o: in function `w2c_f28':
program.c:(.text+0xe08a): undefined reference to `Z_wasi_unstableZ_clock_time_getZ_iiji'
/usr/bin/ld: /tmp/ccZq4O8u.o: in function `w2c_f29':
program.c:(.text+0xe1b5): undefined reference to `Z_wasi_unstableZ_proc_exitZ_vi'
/usr/bin/ld: /tmp/ccZq4O8u.o: in function `w2c_f31':
program.c:(.text+0xe240): undefined reference to `Z_wasi_unstableZ_fd_closeZ_ii'
```
It seems that the definition of WASI is missing. I noticed that the program uses [wasmer](https://github.com/wasmerio/wasmer) to run the .wasm, But I can't figure out how it works in a short time. 
Can someone tell me where to find the definition of these functions? Thanks a lot!

**Comment by kripken** [comment]
I'm not sure what `boom()` is, you'd need to look in the source code.

In general to run wasm2c output you need a runtime to provide what the wasm VM would, which includes `clock_time_get`, `proc_exit`, and `fd_close`. One option is the emscripten runtime which includes support for several WASI functions [including those](https://github.com/emscripten-core/emscripten/blob/master/tools/wasm2c/os.c) ([example instructions](http://kripken.github.io/talks/2020/universal.html#/21), or [in more detail](https://kripken.github.io/blog/wasm/2020/07/27/wasmboxc.html)).

**Comment by RLee063** [comment]
Thanks for reply.
I've taken a quick look at what you gave me, but I'm sorry that I didn't quite understand how emscripten provides support for WASI. And I have some questions about `emscripten/tools/wasm2c/os.c`

1. It seems that the version of WASI is different.
2. It doesn't seem to have support for some functions, like `fd_prestat_get` and `fd_prestat_dir_name`.

I think I should learn more about WASM, Thanks a lot!

By the way, I have tried to link these WASI functions to [libwasmer.so](https://github.com/wasmerio/wasmer/releases), but things are not going well. XD. Although it includes support for these WASI functions, it seems wasmer will do some extra things before calling these functions, reflected in these functions require more parameters. For example
```rust
pub fn fd_prestat_get(
    ctx: &mut Ctx,  //additional
    fd: __wasi_fd_t,
    buf: WasmPtr<__wasi_prestat_t>,
) -> __wasi_errno_t {
    debug!("wasi::fd_prestat_get: fd={}", fd);
    let (memory, state) = get_memory_and_wasi_state(ctx, 0);

    let prestat_ptr = wasi_try!(buf.deref(memory));

    prestat_ptr.set(wasi_try!(state.fs.prestat_fd(fd)));

    __WASI_ESUCCESS
}
```
compared with the declaration `Z_wasi_unstableZ_fd_prestat_getZ_iii`.

**Comment by kripken** [comment]
Yes, the support there for WASI is definitely incomplete, it's a work in progress... It would be good to see more work in this area, across the relevant coebases, but it is pretty new atm so things generally won't work out of the box, as you're seeing.
