### ISSUE TITLE
wast2wasm doesn't parse musl.wast

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/wabt#152]
https://wasm-stat.us/builders/linux/builds/11742/steps/musl/logs/stdio

Reverting #148 locally lets it build again.

The musl.wast looks like
```
(module
  (memory $0 1)
  (data ...)
    ...
  (type ...)
    ...
  (import ...)
    ...
  (export ...)
    ...
  (table 19 19 anyfunc)
  (elem ...)
  (func ...)
    ...
)
```

which seems valid?

**Comment by binji** [comment]
AIUI, the import isn't allowed to occur after the memory definition. See https://github.com/WebAssembly/spec/blob/binary-0xc/ml-proto/test/import-after-memory.fail.wast for example.

**Comment by jgravelle-google** [comment]
Interesting. Seems like s2wasm isn't generating perfectly valid .wasts then. And then #148 got wast2wasm compliant with the spec, so it wasn't breaking before then.
Thanks!
