### ISSUE TITLE
unable to build with emscripten

### ISSUE THREAD

**Issue by Mashpoe** [WebAssembly/wabt#1529]
I followed the instructions in the README, and tried `make emcc-release`, `make emcc-debug`, and various other combinations. Nothing works. `No rule to make target 'emcc-release'`.

Everything works perfectly fine with gcc, and I can actually get it to start compiling using with emscripten if I follow the manual instructions. I made the build directory, opened it, typed `cmake ..`, and then `cmake -G "Unix Makefiles" --build . -DCMAKE_C_COMPILER-emcc -DCMAKE_CXX_COMPILER-emcc -DCMAKE_BUILD_TYPE=Release`. this actually generates build files and I can run the makefile but I get multiple errors from emcc, including `invalid token at start of a preprocessor expression #if SIZEOF_SIZE_T == 4` and `use of undeclared identifier 'magic'`.

I have been able to build hello world with emscripten, and I do have the latest version. I may be doing something wrong with cmake, but I should at least be able to build it with emscripten when I follow the README instructions. All help is appreciated :)

**Comment by binji** [comment]
It looks like the target is actually `emscripten-release` not `emcc-release`. I'll update the docs. Not sure why the build would be failing for you, though. You can see that we test the emscripten build in the CI, so it should be working: https://github.com/WebAssembly/wabt/runs/1016311949

**Comment by Mashpoe** [comment]
thanks! I tried `emscripten-release` and it built
