### ISSUE TITLE
Memory64 text format parses `i64` in the wrong location

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1532]
I believe according to https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md#text-format the `i64` modifier is expected to come before the limits, but it looks like in the test added here in https://github.com/WebAssembly/wabt/pull/1500 have`i64` coming after the limits?

**Comment by binji** [comment]
@aardappel mind taking a look?

**Comment by aardappel** [comment]
Yup, I implemented it to come after, same in Binaryen. I can switch it around (it kinda makes more sense, as it affects validation of the limits) or we can change it in the proposal, what do you prefer?

**Comment by binji** [comment]
Yeah, I think I picked it arbitrarily for the overview, but I think you're right that it makes sense to come before limits.

**Comment by surma** [comment]
I just ran into this when writing a detector for wasm-feature detect.

`(module (memory i64 1))` works fine with `wat2wasm` (even without the `--enable-memor67` flag?!, but doesn’t work with `wasm2wat` without the flag).

`(module (memory 0 i64 1))` fails, however: 
```
src/detectors/memory64/module.wat:6:13: error: unexpected token i64, expected ).
  (memory 0 i64 1)
            ^^^
```

**Comment by aardappel** [comment]
Ok, I hadn't gotten to this, let me make it a priority to fix it :)

**Comment by aardappel** [comment]
Just looking at this, it seems this was already fixed in https://github.com/WebAssembly/wabt/commit/8e42376ccd5f05dc1036f91b4262e67b0fc66c2d ? In particular, `ParseLimitsIndex` is always called before `ParseLimits`. See also https://github.com/WebAssembly/memory64/issues/5

@surma the rest of this issue was from before the fix, and we didn't close it. `(module (memory 0 i64 1))` should indeed not be legal?

**Comment by surma** [comment]
I was looking at the [memory64 proposal](https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md) which says:

```
memtype ::= lim:limits             ⇒ i32 lim
         |  it:idxtype lim:limits  ⇒ it lim
```

which implies to me that `(memory 0 i64 1)` should be legal. Is the explainer outdated or am I misreading something?

**Comment by surma** [comment]
(also, should `(module (memory i64))` compile successfully _without_ the `--enable-memory64` flag? It currently does.)

**Comment by aardappel** [comment]
> which implies to me that (memory 0 i64 1) should be legal

I don't see how that is so? `idxtype` is `i64` (or `i32`) and comes first, then `limits` is min & max, e.g. `0 1` here?

**Comment by surma** [comment]
I think I have found my mistake. `0` was supposed to be the index, but  I had `id` confused with `idx`.

I was looking to find where `memtype` was used in [the main spec](https://webassembly.github.io/spec/core/text/modules.html#memories)  and found the memory declaration:

```
𝚖𝚎𝚖 ::= ‘(’ ‘𝚖𝚎𝚖𝚘𝚛𝚢’  𝚒𝚍?  mt:𝚖𝚎𝚖𝚝𝚢𝚙𝚎 ‘)
```

That’s where my `(memory 0 i64 1)` came from.  

**So all good! This issue can be closed.**

(I still think `(module (memory i64))` should not compile successfully without explicitly specifying `--enable-memory64`.)

**Comment by aardappel** [comment]
and yes it shouldn't accept the index type :)
