### ISSUE TITLE
wat2wasm outputs incorrect local indices on function with type use

### ISSUE THREAD

**Issue by gumb0** [WebAssembly/wabt#1551]
This looks to be related to https://github.com/WebAssembly/wabt/pull/1466

For the functions that define their type as `(type ...)` indices of local always start with 0:
```
$ cat type_sig.wast
(module
  (type $sig (func (param i32) (result i32)))
  (func (type $sig)
    (local $var i32)
    (local.get $var))
)
$ wat2wasm type_sig.wast 
``` 

This generates binary with `local.get 0` while the correct index should be `local.get 1`:
```
$ wasm2wat type_sig.wasm 
(module
  (type (;0;) (func (param i32) (result i32)))
  (func (;0;) (type 0) (param i32) (result i32)
    (local i32)
    local.get 0))
```

This also leads to `wast2json` incorrectly generating module for these spec tests https://github.com/WebAssembly/spec/blob/7526564b56c30250b66504fe795e9c1e88a938af/test/core/func.wast#L459-L485

**Comment by osa1** [comment]
This seems to be fixed in `master` branch.

**Comment by gumb0** [comment]
> This seems to be fixed in `master` branch.

You're right, I can't reproduce it on `master`, sorry I didn't check it earlier.

**Comment by binji** [comment]
Ah, thanks. I thought I fixed this, but wasn't sure if there was another bug. :)

**Comment by osa1** [comment]
In case anyone else is suffering from this bug and wondering if they need to update wabt: the latest release (1.0.19) **does not** have this fix. You need the master branch.

**Comment by binji** [comment]
> In case anyone else is suffering from this bug and wondering if they need to update wabt: the latest release (1.0.19) does not have this fix. You need the master branch.

Thanks for the FYI. I suppose we should push a new version then.

**Comment by chfast** [comment]
> > In case anyone else is suffering from this bug and wondering if they need to update wabt: the latest release (1.0.19) does not have this fix. You need the master branch.
> 
> Thanks for the FYI. I suppose we should push a new version then.

@binji is this still planned?

**Comment by binji** [comment]
Thanks for the reminder, I'll push a new version today.
