### ISSUE TITLE
Support --relocatable and multi-memory

### ISSUE THREAD

**Issue by wingo** [WebAssembly/wabt#1552]
See https://github.com/WebAssembly/wabt/pull/1549 for the kind of changes that need to happen.

**Comment by 00ff0000red** [comment]
Came to say that the multi-memory proposal is at stage 3, and that wabt should support it.

Any clue when this might happen?

**Comment by 7ombie** [comment]
Does WABT have any full-time maintainers?

**Comment by keithw** [comment]
Finished in #1751
