### ISSUE TITLE
wasm-decompile outputs seemingly repetitive/nonsensical code

### ISSUE THREAD

**Issue by devsnek** [WebAssembly/wabt#1565]
some examples:

![](https://gc.gy/72178717.png)

![](https://gc.gy/72178869.png)

![](https://gc.gy/72178927.png)

**Comment by binji** [comment]
@aardappel

**Comment by aardappel** [comment]
Weird, not sure why it would repeat using the same name twice.

Is this from LLVM output or some other generator?

**Comment by devsnek** [comment]
it is the output of rustc --release and wasm-opt -O4. I can upload the file in a bit.

**Comment by devsnek** [comment]
https://s.gc.gy/fbw-release.wasm

**Comment by aardappel** [comment]
Fix here: https://github.com/WebAssembly/wabt/pull/1666
