### ISSUE TITLE
wat2wasm: elem without offset shouldn't be accepted

### ISSUE THREAD

**Issue by igrep** [WebAssembly/wabt#1566]
# How to reproduce (and why this can be a problem)

Here is the minimum code to reproduce:

table-identifier.wat:

```wasm
(module
    (import "js" "tbl" (table $tblImported 1 anyfunc))
    (func $f (result i32) i32.const 42)
    (elem $tblImported $f)
)
```

Running `wat2wasm table-identifier.wat` generates a wasm file below:

(Update: this Wasm file is actually invalid. So the point here is wat2wasm shouldn't accept the fie above)

table-identifier.wasm (as textual form):

```wasm
(module
  (type (;0;) (func (result i32)))
  (import "js" "tbl" (table (;0;) 1 funcref))
  (func (;0;) (type 0) (result i32)
    i32.const 42)
  (elem (;0;) func 0))
```

The element segment `(elem (;0;) func 0))` is ignored (at least) by V8.
For example in REPL of Node.js:

```js
> tbl = new WebAssembly.Table({initial:1, element:"anyfunc"});
> wasm = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync('table-identifier.wasm')), { js: {
 tbl: tbl } })
Instance [WebAssembly.Instance] {}
> tbl.get(0) // The 0th element should be overwritten by calling `new WebAssembly.Instance(..)`!
null
```

## For comparison: adding the offset works as expected

table-i32.const.wat:

```wasm
(module
    (import "js" "tbl" (table 1 anyfunc))
    (func $f (result i32) i32.const 42)
    (elem (i32.const 0) $f) ;; Just changed tblImported into i32.const 0
)
```

Then run `wat2wasm table-identifier.wat`, and test with REPL of Node.js.

```js
> tbl = new WebAssembly.Table({initial:1, element:"anyfunc"});
Table [WebAssembly.Table] {}
> wasm = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync('table-i32.const.wasm')), { js: {
tbl: tbl } })
Instance [WebAssembly.Instance] {}
> tbl.get(0) // Not null because calling `new WebAssembly.Instance(..)` implicitly overwrites the imported table!
[Function: 0]
```

# My environment

```
> wat2wasm.exe --version
1.0.13 (1.0.19)

> node --version
v15.0.1
```

**Comment by binji** [comment]
It looks like wabt is allowing this syntax, but shouldn't. The spec interpreter fails to parse this:

```
$ cat.test.wat
(module
    (import "js" "tbl" (table $tblImported 1 funcref))
    (func $f (result i32) i32.const 42)
    (elem $tblImported $f)
)
$ wasm test.wat -o test.wasm
test.wat:4.24-4.26: syntax error: unexpected token
```

It seems wabt is interpreting this as a passive element segment, which is a feature added w/ the [bulk-memory-operations](https://github.com/webassembly/bulk-memory-operations/) proposal.

It should work with a table name, if you change it to:

```wasm
(module
    (import "js" "tbl" (table $tblImported 1 funcref))
    (func $f (result i32) i32.const 42)
    (elem $tblImported (i32.const 0) $f)
)
```

But note that the table name is not generally required, since for MVP wasm there was a maximum of one table anyway.

**Comment by igrep** [comment]
Oh, thanks. I misunderstood the syntax!
