### ISSUE TITLE
Statically link Visual C++ runtime when releasing on Windows

### ISSUE THREAD

**Issue by skuzmich** [WebAssembly/wabt#1568]
Currently we need to install Visual C++ Redistributable on Windows in order to run WABT, which is a slight inconvenience.

Could you link it statically?

I believe it is controlled by `-MT` and `-MTd` compiler fags and which are supported in CMake build via [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/v3.19/prop_tgt/MSVC_RUNTIME_LIBRARY.html) property, but I'm don't have a Windows dev box to try it myself.

**Comment by aardappel** [comment]
Will not be able to get to this any time soon, so un-assigning..
