### ISSUE TITLE
How to build wabt in release mode on Linux

### ISSUE THREAD

**Issue by Praveer1981** [WebAssembly/wabt#1571]
Hi,
I want to build all the tools in the release mode on Linux. I followed the instructions mentioned in the readme.md . but I am not able to get release version of binaries.
can someone help me

**Comment by binji** [comment]
You need to add `-DCMAKE_BUILD_TYPE=Release` to your cmake build configuration (see https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) for more info. If you're using the top-level `Makefile`, then you can build a target like `clang-release` instead.

**Comment by Praveer1981** [comment]
The command I used to generate the binaries:

```
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
```
It generates the wasm-objdump but when I run below command It seems to be debug binary

`$file wasm-objdump`
O/P:

`wasm-objdump: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=a7194a75b0079b4278a2cb380e140876071b8642, **with debug_info**, not stripped
`
To be more specific, I want release version of wasm-objdump.

is there anything I am missing here ? @binji

**Comment by Praveer1981** [comment]
I built in verbose mode to see the exact commands executed:
Below are the command I ran:

```
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
$ cmake --build .
```
O/P:
```
Scanning dependencies of target wasm-objdump
make[2]: Leaving directory '/home/kumarpr/Praveer_wabt/wabt/build'
/usr/bin/make -f CMakeFiles/wasm-objdump.dir/build.make CMakeFiles/wasm-objdump.dir/build
make[2]: Entering directory '/home/kumarpr/Praveer_wabt/wabt/build'
[ 72%] Building CXX object CMakeFiles/wasm-objdump.dir/src/tools/wasm-objdump.cc.o
/usr/bin/c++  -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -I/home/kumarpr/Praveer_wabt/wabt -I/home/kumarpr/Praveer_wabt/wabt/build -I/home/kumarpr/Praveer_wabt/wabt/third_party/gtest/googletest -I/home/kumarpr/Praveer_wabt/wabt/third_party/gtest/googletest/include  -std=c++11 -Wold-style-cast -fno-exceptions -O3 -DNDEBUG   -Wall -Wextra -Wno-unused-parameter -Wpointer-arith -g -Wuninitialized -Wno-clobbered -std=c++11 -o CMakeFiles/wasm-objdump.dir/src/tools/wasm-objdump.cc.o -c /home/kumarpr/Praveer_wabt/wabt/src/tools/wasm-objdump.cc
[ 73%] Building CXX object CMakeFiles/wasm-objdump.dir/src/binary-reader-objdump.cc.o
/usr/bin/c++  -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -I/home/kumarpr/Praveer_wabt/wabt -I/home/kumarpr/Praveer_wabt/wabt/build -I/home/kumarpr/Praveer_wabt/wabt/third_party/gtest/googletest -I/home/kumarpr/Praveer_wabt/wabt/third_party/gtest/googletest/include  -std=c++11 -Wold-style-cast -fno-exceptions -O3 -DNDEBUG   -Wall -Wextra -Wno-unused-parameter -Wpointer-arith -g -Wuninitialized -Wno-clobbered -std=c++11 -o CMakeFiles/wasm-objdump.dir/src/binary-reader-objdump.cc.o -c /home/kumarpr/Praveer_wabt/wabt/src/binary-reader-objdump.cc
[ 73%] Linking CXX executable wasm-objdump
/usr/bin/cmake -E cmake_link_script CMakeFiles/wasm-objdump.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++11 -Wold-style-cast -fno-exceptions -O3 -DNDEBUG  -rdynamic CMakeFiles/wasm-objdump.dir/src/tools/wasm-objdump.cc.o CMakeFiles/wasm-objdump.dir/src/binary-reader-objdump.cc.o  -o wasm-objdump libwabt.a
make[2]: Leaving directory '/home/kumarpr/Praveer_wabt/wabt/build'
[ 73%] Built target wasm-objdump
/usr/bin/make -f CMakeFiles/wasm2c.dir/build.make CMakeFiles/wasm2c.dir/depend
make[2]: Entering directory '/home/kumarpr/Praveer_wabt/wabt/build'
cd /home/kumarpr/Praveer_wabt/wabt/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/kumarpr/Praveer_wabt/wabt /home/kumarpr/Praveer_wabt/wabt /home/kumarpr/Praveer_wabt/wabt/build /home/kumarpr/Praveer_wabt/wabt/build /home/kumarpr/Praveer_wabt/wabt/build/CMakeFiles/wasm2c.dir/DependInfo.cmake --color=
```

**Comment by Praveer1981** [comment]
@binji here I can see that the command has `-g` flag. which means it will be always debug.
https://github.com/WebAssembly/wabt/blob/master/CMakeLists.txt#L142

if I remove `-g` and build it, it generates the binary of size in 723 kb. I am not sure it is correct. 
please advice

**Comment by sbc100** [comment]
That `-g` doesn't seem like it should be there.  I would have though cmake it self would add that flag (or not) as needed.

**Comment by Praveer1981** [comment]
@sbc100 I couldn't understand you completely. could you please elaborate a bit more .

**Comment by sbc100** [comment]
I think you can submit a patch to remove `-g` from the `CMakeList.txt` file.

I imagine cmake will automatically add this back in for `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by Praveer1981** [comment]
Thanks I will submit the patch.

**Comment by Praveer1981** [comment]
@sbc100 @binji  I have created a PR

**Comment by rathann** [comment]
PR was merged, so I think this can be closed.

**Comment by sbc100** [comment]
Yup! Thanks!
