### ISSUE TITLE
Demo allows compilation of multi-value select operation

### ISSUE THREAD

**Issue by 00ff0000red** [WebAssembly/wabt#1577]
The wat2wasm demo at https://webassembly.github.io/wabt/demo/wat2wasm allows the following code to compile (with flags):
```wat
(module
    (func (export "selectTwo") (result i32 i32)
        i32.const 0
        i32.const 0
        i32.const 0
        i32.const 0
        select (result i32 i32)
    )
)
```

Have the semantics of the select operation been established if it leaves multiple values on the stack?
Should wat2wasm prevent this from compiling?

Do any WebAssembly compilers/interpreters/runtimes handle this operation yet?

**Comment by rossberg** [comment]
The reftypes proposal, which introduces the explicitly typed variant of the select instruction, does not yet allow multiple results, although they are anticipated as a future extension. So until there's a proposal to add it (or we decide to slip it into the reftypes proposal), the code is invalid.

**Comment by 00ff0000red** [comment]
> So until there's a proposal to add it (or we decide to slip it into the reftypes proposal), the code is invalid.

So, do you believe that the compilation of such code should be prevented until the extension is created?

**Comment by rossberg** [comment]
That depends on wabt's philosophy. It is a conservative (and canonical) extension. I suppose it would be best if there was a feature switch for it.

**Comment by 00ff0000red** [comment]
> I suppose it would be best if there was a feature switch for it.

A feature switch would make more sense, as it is experimental, and at the union between the two proposals.
If it is created, that would be great to know!
