### ISSUE TITLE
Add emscripten builder for Travis

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#158]
If the build breaks and no one is around to hear it, does anyone fix it?

**Comment by binji** [comment]
Since folks are making more changes to the emscripten build, it would be really nice to have this. Perhaps we can use the same docker setup that binaryen uses: https://github.com/WebAssembly/binaryen/blob/master/.travis.yml#L63

**Comment by pepyakin** [comment]
Im wondering, is it feasible to start with waterfall builds?

**Comment by binji** [comment]
Yes, that should be possible since they're all archived. I suppose that has the benefit of being more up-to-date, right?

**Comment by pepyakin** [comment]
Right and, as you mentioned, they're all archived so I thought that should be easier to start with (However, I don't know what I'm talking about)

Cons: Breakage will be noticed after the offending PR was merged.

**Comment by kripken** [comment]
I'm looking into this.
