### ISSUE TITLE
src/interp/interp-wasm-c-api.cc:17:10: fatal error: 'wasm.h' file not found

### ISSUE THREAD

**Issue by cayden** [WebAssembly/wabt#1594]
I have a problem in MAC, operation
cmake -- build .
thanks!

**Comment by cayden** [comment]
it's ok to me .
git clone --recursive https://github.com/WebAssembly/wabt

**Comment by yaohuiwu** [comment]
I think someone needs to add the 'git clone --recursive https://github.com/WebAssembly/wabt' to the README doc.
