### ISSUE TITLE
How to support the updated EH spec

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#1604]
The new EH spec will eventually need to be supported in WABT. One new thing in the [update](https://github.com/WebAssembly/exception-handling/blob/1ec111eb32c8490991c943af2af40559dbd63cd4/proposals/exception-handling/Exceptions.md) is that the opcode for `catch_all` is 0x05, the same as `else`. This is not ambiguous because `else` must occur with an `if` and not a `try`, but wabt seems to have the assumption (e.g. in [opcode.def](https://github.com/WebAssembly/wabt/blob/master/src/opcode.def) ) that there's a 1:1 correspondence.
I haven't looked at how to fix it yet, but wondered if anyone (perhaps @aardappel or @sbc100) had any good ideas about the best way to make it work.

**Comment by sbc100** [comment]
I'm not too familiar with part of the code I'm afraid.

**Comment by lars-t-hansen** [comment]
Will anything good come from saving that one opcode, apart from saving one byte in the opcode space?

SpiderMonkey currently assumes a 1:1 mapping in a couple of places.  Resolving the opcode overloading is likely not a real hardship, but I still wonder whether the overloading is not simply adding complexity to the spec.

**Comment by wingo** [comment]
PR here, fwiw https://github.com/WebAssembly/wabt/pull/1596

**Comment by sbc100** [comment]
> Will anything good come from saving that one opcode, apart from saving one byte in the opcode space?
> 
> SpiderMonkey currently assumes a 1:1 mapping in a couple of places. Resolving the opcode overloading is likely not a real hardship, but I still wonder whether the overloading is not simply adding complexity to the spec.

Agreed, unless there is some significant upside it seems like a bad idea.

**Comment by takikawa** [comment]
I agree that there are downsides to sharing the opcode. In particular, it's not great for error messages (you could get errors expressed in terms of `else` but the source had `catch_all` or vice versa).

Historically, I think this punning was inherited from the [an early version](https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/old/Exceptions-v1.md) of the proposal.

**Comment by dschuff** [comment]
Thanks @wingo that's handy for just local hacking like I've been doing.
It sounds like we might want to reconsider the opcode though. I opened https://github.com/WebAssembly/exception-handling/issues/147 to discuss that.

**Comment by aardappel** [comment]
I guess `end` is technically already overloaded, but there we can just use the single identifier.

Supporting WABT to output different names may be somewhat messy, it would mean that any calls to `Opcode::GetName` would need context parameter to know which control structure we're currently in.

**Comment by aheejin** [comment]
We decided to change the `catch_all`'s opcode (WebAssembly/exception-handling#147) and @takikawa landed a PR doing that (#1608). Closing.
