### ISSUE TITLE
wat2wasm fails to convert ref.func

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wabt#1606]
With the following WAT file, `ref.wat`:

```
(module
  (func $a)
  (func $b (ref.func $a) drop)
)
```

I run `wat2wasm --enable-all ref.wat` and receive an error:

```
ref.wat:3:22: error: function is not declared in any elem sections
  (func $b (ref.func $a) drop)
                     ^^
```

I did not expect this type of error, since tests using [the roundtrip reference-types.txt](https://github.com/WebAssembly/wabt/blob/master/test/roundtrip/reference-types.txt) and [ref_func.wast](https://github.com/WebAssembly/testsuite/blob/18f83401a47a0e43772cf7d9f216e994bf7c7fa6/proposals/reference-types/ref_func.wast) seem to have this form of usage.

**Comment by rossberg** [comment]
This is intended behaviour, introduced due to WebAssembly/reference-types#76. See [here](https://github.com/WebAssembly/meetings/blob/master/main/2020/CG-05-12.md#discuss-global-reffunc-initializers-complicating-validation-reference-types-issue76) for the respective CG discussion.
