### ISSUE TITLE
Building inside a symlinked directory fails completely

### ISSUE THREAD

**Issue by ericonr** [WebAssembly/wabt#1607]
Reproduce:

```
$ mkdir /tmp/builddir
$ ln -s /tmp/builddir build
$ cd build
$ cmake /path/to/wabt
```

With Make:

```
$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ericonr/docs/extpro/wabt/build
make[2]: *** No rule to make target '../src/apply-names.cc', needed by 'CMakeFiles/wabt.dir/src/apply-names.cc.o'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:823: CMakeFiles/wabt.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

With ninja:

```
$ ninja
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ericonr/docs/extpro/wabt/build
[... this repeats itself until the loop detection kicks in ...]
```

Doing a normal build from a non symlinked directory seems to work, and other CMake projects work just fine in this same setup.

**Comment by sbc100** [comment]
Interesting, from my experiment it looks like the symlink only causes issues if it lives inside the wabt directory.   If I run the recipe from somewhere other then `/path/to/wabt` it seems to work fine.

Can you confirm this is what you see too?

Still trying to figure out why it doesn't work when the link is within the source tree.

**Comment by sbc100** [comment]
I see the same issue with at least one other project that I work on: binaryen.  Are you sure this isn't a generic cmake issue?

**Comment by sbc100** [comment]
Indeed I see the same issue with even a trivial cmake example:

```
cmake_minimum_required(VERSION 2.4)

project(hello_world)

add_executable(app main.cpp)
```

So I think this is a cmake bug.

**Comment by ericonr** [comment]
> Interesting, from my experiment it looks like the symlink only causes issues if it lives inside the wabt directory. If I run the recipe from somewhere other then /path/to/wabt it seems to work fine.

Yes, this also works for me.

> Indeed I see the same issue with even a trivial cmake example:

I almost certainly remember this working with fish-shell, but I went to check and it didn't work there anymore. This might have been a CMake regression instead D: I will install an older version and confirm. For the record, I'm using 3.19.3.

**Comment by ericonr** [comment]
Welp, it seems I misremembered it, because at least since 3.17.1, which is around the earliest for me building fish locally, this already didn't work.

Thanks for helping me debug! I will close this since it's not really something that this repo should solve.

Have a good week :)

**Comment by ericonr** [comment]
@sbc100 if you're interested, https://gitlab.kitware.com/cmake/cmake/-/issues/21819
