### ISSUE TITLE
wat2wasm produces code that gives "Invalid regular expression"

### ISSUE THREAD

**Issue by mvolkmann** [WebAssembly/wabt#1611]
My very basic example at https://github.com/mvolkmann/wasm-demo gives the following error when I run it in Chrome, but the code still works as expected.

```text
inject.js:2 Uncaught SyntaxError: Invalid regular expression: /(?:[Â›][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-PRZcf-nqry=><])|[--Â›Â­â€‹  ﻿ï¸€-ï¸]/: Range out of order in character class
```

The error comes from the generated file `index.js`.

**Comment by mvolkmann** [comment]
This issue seems to not be unique to using wat2wasm. I'm seeing the same error when I just use wasm-pack.
Here's a simple repo that demonstrates the issue. Following the steps in the README and viewing the DevTools console should show the error. https://github.com/mvolkmann/wasm-rust-linear-memory

**Comment by tlively** [comment]
Where does `inject.js` come from? Since this bug isn't specific to wabt, my guess is that this is a real bug in `inject.js`.

**Comment by mvolkmann** [comment]
I found out this was coming from some Chrome extension. After removing several extensions I was no longer using, this went away.
