### ISSUE TITLE
wat2wasm doesn't typecheck (elem) against table types

### ISSUE THREAD

**Issue by ghost** [WebAssembly/wabt#1612]
This snippet is invalid,
```wat
(module
	(import "" "" (func $f))
	(table 1 1 externref)
	(elem (i32.const 0) $f)
)
```

as `func` is not a super-type of `externref`.

wat2wasm currently doesn't catch it.

**Comment by 7ombie** [comment]
I personally found it tricky to type-check active table segments, as you need to refer back to the table it populates to know the reftype, which in turn, requires resolving the number literal or identifier that expresses the table index. This should happen during parsing, but the indices are not worked out until the compilation stage.

You cannot just track how many tables have been imported or defined in the parser, as a later import will be enumerated in the binary ahead of any definitions, even if the definition appears first in the source, so the indices can be invalidated.

The compiler can check the types as it compiles everything, and has the information it needs, but this creates a subtle issue: If your example code was at line 50, and another error was at line 100, the compiler would complain about line 100, and fixing that bug would reveal the error at line 50. This is a small thing, but you really don't want debugging tools to occasionally do something subtly different from what they normally do.

It's really a consequence of the design of WAT. It could have required that active segments are directly attached (lexically) to the memory or table they populate, which would have made validation easy, but would have been inflexible linguistically.
