### ISSUE TITLE
Support for final wasm-simd128 specin the wabt interpreter?

### ISSUE THREAD

**Issue by steven-johnson** [WebAssembly/wabt#1617]
Is there work underway to bring the WABT interpreter in line with the final proposal for the wasm-simd128 spec? If so, is there any rough ETA? If not, is this work scheduled to be done? (Or has it already been done and I somehow missed it?)

Halide currently uses the WABT interpreter for a fair number of our correctness tests (where performance is unimportant), and simd support is pretty crucial for most Halide users.

**Comment by tlively** [comment]
No, I don't know of any work underway for this right now. I can take a crack at it this week, though.

**Comment by steven-johnson** [comment]
Excellent. Let me know if I can assist.

**Comment by tlively** [comment]
If you're interested, PRs would be super welcome! If not, no problem :)

**Comment by steven-johnson** [comment]
> If you're interested, PRs would be super welcome! 

Not sure where to begin (ie, code structure, testing requirements, etc) & am juggling several things at the moment, but if you can open a PR doing one of the ops (as a useful reference/example) I will try to use that as a basis to help fill in the gaps.

**Comment by ngzhian** [comment]
@steven-johnson I can work on the opcode updates, don't worry for now, I should get something up today. :)

**Comment by repi** [comment]
Noticed that `wasm-strip` fails to strip modules with SIMD instructions in it, is this the same issue or should we file a separate issue for that?

**Comment by ngzhian** [comment]
> Noticed that `wasm-strip` fails to strip modules with SIMD instructions in it, is this the same issue or should we file a separate issue for that?

what's the error message? it's likely a new issue, the opcodes have already been updated.

**Comment by repi** [comment]
filed separate issue #1803

**Comment by keithw** [comment]
Done in 1ba6f750a50c9b033a2309f979edeb0b4bcbf1ef
