### ISSUE TITLE
Missing wasm.h?

### ISSUE THREAD

**Issue by jakirkham** [WebAssembly/wabt#1619]
In trying to build wabt 1.0.21 ran into the following compilation error:

```
../src/interp/interp-wasm-c-api.cc:17:10: fatal error: wasm.h: No such file or directory
   17 | #include <wasm.h>
      |          ^~~~~~~~
compilation terminated.
```

More details can be found in PR ( https://github.com/conda-forge/wabt-feedstock/pull/19 ) along with CI logs

Did something change recently?

**Comment by sbc100** [comment]
That file comes from a git submodule.   If you are using git need to also clone the submodules.

If you are downloading the source archive it should include the submodules as of https://github.com/WebAssembly/wabt/pull/1615, but you need to be sure you download the full archive (wabt-1.0.21.tar.xz) and not just the archive of the sources stored in the repo.   It looks like it did get correctly included:

```
$ tar tvf ~/Downloads/wabt-1.0.21.tar.xz | grep wasm.h
-rw-r--r-- runner/docker  16608 2021-03-02 16:40 wabt-1.0.21/third_party/wasm-c-api/include/wasm.hh
-rw-r--r-- runner/docker  22153 2021-03-02 16:40 wabt-1.0.21/third_party/wasm-c-api/include/wasm.h
```

**Comment by jakirkham** [comment]
Ah got it. Yeah that makes sense. Yep you're right we are downloading the source archive, but that won't work since it doesn't include git submodules. Thanks for producing the full archive. Will switch to that. Thanks again. Also sorry for the noise

**Comment by sbc100** [comment]
thanks to @rofl0r for the timely patch in #1615.
