### ISSUE TITLE
[SIMD] wasm2wat outputs incorrect instruction for i8x16.popcount

### ISSUE THREAD

**Issue by nemequ** [WebAssembly/wabt#1653]
With emscripten tot and this code:

```c
typedef char i8x16 __attribute__((__vector_size__(16)));

i8x16 popcnt(i8x16 v) {
  return __builtin_wasm_popcnt_i8x16(v);
}
```

wasm2wat thinks the popcnt instruction is an `i16x8.extadd_pairwise`

```
$ emcc -O3 -msimd128 -c -o popcnt.wasm popcnt.c && wasm2wat --enable-simd popcnt.wasm
(module
  (type (;0;) (func (param v128) (result v128)))
  (import "env" "__linear_memory" (memory (;0;) 0))
  (func $popcnt (type 0) (param v128) (result v128)
    local.get 0
    i16x8.extadd_pairwise_i8x16_s))
```

I've attached [a gzipped copy of popcnt.wasm](https://github.com/WebAssembly/wabt/files/6198473/popcnt.wasm.gz)

wasm-dis produces the expected output:

```wasm
(module
 (type $v128_=>_v128 (func (param v128) (result v128)))
 (import "env" "__linear_memory" (memory $mimport$0 0))
 (func $0 (param $0 v128) (result v128)
  (i8x16.popcnt
   (local.get $0)
  )
 )
 ;; custom section "linking", size 18
 ;; custom section "producers", size 157
 ;; features section: simd
)
```

It's possible the issue is on the LLVM side, if so sorry for the noise. Just let me know and I'll report it there instead.

**Comment by sbc100** [comment]
@tlively @ngzhian

**Comment by ngzhian** [comment]
Likely a llvm/emscripten issue, `hexdump -C popcnt.wasm` shows me that the opcode is `0xfd 0x7c, which indicates an issue somewhere between calling the builtin and generating wasm.

**Comment by ngzhian** [comment]
@tlively it looks like popcnt was not updated, see https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyInstrSIMD.td#L835.

**Comment by tlively** [comment]
Thanks for investigating, @ngzhian! Will fix.

**Comment by nemequ** [comment]
@tlively do you want me to move this over to bugs.llvm.org?

**Comment by tlively** [comment]
@nemequ No, that's ok. I have a patch up to fix this at https://reviews.llvm.org/D99536.

**Comment by nemequ** [comment]
Patch is in, just tested with emscripten tot and it works perfectly.  Thanks everyone!
