### ISSUE TITLE
[wat2wasm] Add a flag for indexing passive segments before active segments.

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/wabt#1663]
When compiling the text format, it would be useful to have a flag that causes any passive segments to be indexed ahead of any active segments, but otherwise in their lexical order.

Unfortunately, bulk-memory operations have already been standardized, and this feature would be a breaking change if applied everywhere, but it could be opt-in at the compiler level without any issues.

Active segments are only used to *prime* memories and tables (the data is copied, then dropped, and not available at runtime). Passive segments are conceptually different, and function more like little ROMs or *banks*. They are conceptually *components* of the module (like registers, functions, memories and tables are), with an index, optional identifier and special instructions so we can interact with them at runtime.

Ordering the passive segments ahead of any active segments, means that the indices for the components we actually interact with at runtime will be zero-indexed, and will increment properly (memory and table segments have their own indexspaces).

Conceptually then, the *memory banks* and *table banks* will each be intuitively indexed, and the indices of any memory or table *primers* are irrelevant to users of the text format.

[1]: https://github.com/WebAssembly/bulk-memory-operations/issues/159

**Comment by sbc100** [comment]
Can't you achieve this simply by specifying them first in the text format?

**Comment by 7ombie** [comment]
You can, but it would be helpful if you didn't need to do that. It's not a big deal if the request is rejected, but it's a feature I would use, if it was available.

**Comment by 7ombie** [comment]
This is not going anywhere, so I'll close it. No worries.
