### ISSUE TITLE
wasmdump cleanup

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#167]
dschuff's feedback:

```
if (ctx->options->headers) {
+    printf("%-12s start=%#010" PRIzx " end=%#010" PRIzx " (size=%#010" PRIzx
```

I think the size would probably be more readable in decimal than hex.
Actually, maybe start and end, too? IIRC the JS engines report byte offsets in Decimal in error messages stacktraces.

```
+static WasmResult on_import_func(uint32_t index,
+                                 uint32_t sig_index,
```

Might be nice to print the index for imports like the rest of the things.
Or maybe even better, the combined index space (imports+defined) for globals and functions?

```
+static WasmResult on_import_global(uint32_t index,
```

Might be nice to print the type here.

```
+static WasmResult on_export(uint32_t index,
+                            WasmExternalKind kind,
+                            uint32_t item_index,
```

it's not really clear what this index means.

**Comment by binji** [comment]
binji's feedback:

```
         CALLBACK(on_f32_const_expr, value_bits);
+        CALLBACK_CTX(on_opcode_uint32, value_bits);
```
I think it would be nicer to special case this, so you can print it as a float too

---
We can fix up some of the other output later. (I noticed function locals aren't written currently, for example).

**Comment by binji** [comment]
@dschuff @sbc100

**Comment by sbc100** [comment]
Cool, I was about to open exactly this issue :)
