### ISSUE TITLE
wat2wasm: function variable resolution broken

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#1689]
The first sample works with 1.0.23 but produce with the version `main` from today an error.

error: `test.wat:2:10: error: undefined function variable "$.<start>"`
command line: `wat2wasm.exe test.wat --enable-all`
OS: Windows 10
```
(module
  (start $.<start>)
  (event (param externref))
  (func $.<start>
  )
)
```
This sample works with version 1.0.23 and the current version form `main`.
```
(module
  (start $.<start>)
  (func $.<start>
  )
)
```

The same problem occurs with `export` of a function. A possible workaround may be to change the order. First the declaration of the function and then the usage. But why change the behavior when an `event` has been declared?

**Comment by 7ombie** [comment]
When did `event` get added? I can't find the proposal it is part of.

**Comment by Horcrux7** [comment]
It is part of the exception handling: https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md

Now it is named `tag` instead `event`: https://github.com/WebAssembly/exception-handling/pull/161

**Comment by 7ombie** [comment]
Thank you, @Horcrux7.

**Comment by ngzhian** [comment]
I think the error message is misleading, since `event` is now `tag`, your example works if we rename it to `tag`. I'm not sure why the error message becomes a undefined function though.

**Comment by ngzhian** [comment]
Here's a trace with `#define WABT_TRACING 1`:
```
-> ParseModule()
  -> ParseModuleCommand()
    -> ParseScriptModule()
      -> ParseBindVarOpt()
      <- ParseBindVarOpt
      -> ParseModuleFieldList()
        -> ParseModuleField()
          -> ParseStartModuleField()
            -> ParseVar()
            <- ParseVar
          <- ParseStartModuleField
        <- ParseModuleField
      <- ParseModuleFieldList
    <- ParseScriptModule
  <- ParseModuleCommand
<- ParseModule
```
Seems like we stop parsing module fields once we encounter `event`, which is unkown, so we fail to parse the `func`, then later when we check for bound variables we don't have an undefined variable.

**Comment by Horcrux7** [comment]
Thanks for the analyze. I had not expect such behavior.
