### ISSUE TITLE
WABT cannot handle constant expressions with more than one instruction.

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/wabt#1690]
I'm using the `readWasm` method of WABTJS, and it's choking on any constant expression that contains more than one instruction. The [Extended Constant Expressions Proposal][1] adds `add`, `sub` and `mul` instructions (so long as they are integer-typed) to the instructions permitted in a constant expression, so support for blocks of instructions is required.

It currently complains, saying `error: expected END opcode after initializer expression` after the first instruction (even though there's an END opcode after the block, as required).

[1]: https://github.com/WebAssembly/extended-const/blob/master/proposals/extended-const/Overview.md

**Comment by keithw** [comment]
I believe this was fixed in #1824
