### ISSUE TITLE
accommodate outputting the binary wasm to stdout

### ISSUE THREAD

**Issue by sfranzyshen** [WebAssembly/wabt#1692]
## update: jump to the bottom of all this ...

Pipes are used to give the output (stdout) of a command as the input (stdin) to another command ... command line piping has always been a power part of the Unix command line. This feature is absent in wabt. Is this something to consider ... as the concept is already being discussed and implemented within the webassembly.sh and wasi environments for example ...

### example:
`cat some.wasm | wasm2wat | wat2wasm > copyofsome.wasm`

**Comment by sfranzyshen** [comment]
from what I can see there was at least the attempt to support this by using a input file name of "-" but it doesn't work. Somewhere during the parsing of the command line the "-" filename thing gets lost ... I tried to follow along the process flow of the wasm2wat utility ... but I cannot figure out where ... Here's a example of how it fails ...
```
$cat some.wasm | wasm2wat -
stat failed: No such file or directory

```
* [wabt/src/tools/wasm2wat.cc](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc)
  *  [static std::string s_infile;](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L38) 
  * [int main(int argc, char** argv)](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L145)
    * [int ProgramMain(int argc, char** argv)](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L100)
      * [static void ParseOptions(int argc, char** argv)](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L60)
        * [parser.AddArgument("filename", OptionParser::ArgumentCount::One,](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L92)
        * [parser.Parse(argc, argv);](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L97) =>  [wabt/src/option-parser.cc](https://github.com/WebAssembly/wabt/blob/main/src/option-parser.cc)
      * [result = ReadFile(s_infile.c_str(), &file_data);](https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm2wat.cc#L107) => [wabt/src/common.cc](https://github.com/WebAssembly/wabt/blob/main/src/common.cc)
* [wabt/src/option-parser.cc](https://github.com/WebAssembly/wabt/blob/main/src/option-parser.cc)
  * [void OptionParser::Parse(int argc, char* argv[])](https://github.com/WebAssembly/wabt/blob/main/src/option-parser.cc#L163)
* [wabt/src/common.cc](https://github.com/WebAssembly/wabt/blob/main/src/common.cc)
  * [Result ReadFile(string_view filename, std::vector<uint8_t>* out_data)](https://github.com/WebAssembly/wabt/blob/main/src/common.cc#L79)
    * [if (filename == "-")](https://github.com/WebAssembly/wabt/blob/main/src/common.cc#L83)
      * [return ReadStdin(out_data);](https://github.com/WebAssembly/wabt/blob/main/src/common.cc#L61)

**Comment by sfranzyshen** [comment]
Updating to 1.0.23 and everything almost works as expected ... I still have a problem with wat2wasm (maybe other tools) this time with the output (stdout) ... looks like it blocks outputting to stdout ... probably to prevent from echoing to the terminal (could lock up the session) but it prevents the inline operation.  there is a command line switch to send a hex dump to stdout `-d, --dump-module Print a hexdump of the module to stdout` perhaps a switch for allowing dumping the binary as well to stdout `-w, --dump-wasm Print a wasm binary of the module to stdout` could be created to allow things to work for those who need it ??

**Comment by 7ombie** [comment]
It would be nice to also have a longer form that makes things a bit less cryptic, maybe supporting a `--stdout` flag or something like that:

``` sh
cat some.wasm | wasm2wat --stdout | wat2wasm -w --stdout | wasm-strip -w --stdout > copyof.wasm
```

We often put stuff like this in rc-files, where it's helpful to spell things out a bit.

**Comment by keithw** [comment]
Done in #1902 (`--output=-`)
