### ISSUE TITLE
Is WABT actively maintained?

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/wabt#1694]
I don't mean to sound ungrateful, but it has to be said... The issue tracker is just piling up, and simple questions often get ignored for years and forgotten.

**Comment by kripken** [comment]
It's true that no one seems to be spending time to answer questions specifically, but on the other hand PRs get filed, reviewed, and landed, and the code is used by people.

So I would say the code is maintained, but this repo's issue tracker doesn't get a lot of attention. It would be nice to see that improved, but it depends on people volunteering their time.

**Comment by 7ombie** [comment]
Thanks, @kripken. Fair point.

**Comment by keithw** [comment]
In the spirit of this question, closing this issue. :slightly_smiling_face:

**Comment by 7ombie** [comment]
Thank you, @keithw. It's nice to see the issues being dealt with. Much appreciated.
