### ISSUE TITLE
TARGET_ARCH sniffing doesn't handle arm64 on OSX

### ISSUE THREAD

**Issue by steven-johnson** [WebAssembly/wabt#1709]
When compiling on an arm64 Mac, configuring the build produces the warning:

```
CMake Warning at CMakeLists.txt:197 (message):
  Unknown target architecture!
```

This is a common enough architecture now that it should be handled without warning.

**Comment by rathann** [comment]
Duplicate of #1688 .

**Comment by keithw** [comment]
Closing as duplicate of #1688
