### ISSUE TITLE
Spec tests for the exception handling don't work

### ISSUE THREAD

**Issue by igor-laevsky** [WebAssembly/wabt#1710]
It appears that WABT uses https://github.com/WebAssembly/testsuite for it's spec tests. However it has outdated versions for some of the proposals, i.e exception-handling. When I try to take a fresh version directly from the https://github.com/WebAssembly/exception-handling I see a multitude of different issues in the various tools from WABT.

**Comment by takikawa** [comment]
I have some WIP patches to make the exception handling spec tests work in wabt. A few are ready to send for review already (like fixing inline import/export for tags) so I will make PRs for those soon, but the primary issue is that the wabt interpreter doesn't support exceptions. I have a half-done patch for that but haven't had much time to prioritize it.

**Comment by takikawa** [comment]
This should now be fixed by #1749 and #1764.

**Comment by keithw** [comment]
Closing per last comment
