### ISSUE TITLE
opcode.def Structure

### ISSUE THREAD

**Issue by julKali** [WebAssembly/wabt#1715]
I am a bit confused about the opcode.def file - what do the parameters represent?

These are the control instructions from the official specification:
![opcodes](https://user-images.githubusercontent.com/17690423/134524876-04f542bf-ee74-4fa3-8d9f-bc353a1c8c7d.png)

Note that both the `br` and the `br_if` instruction take one parameter, namely the label index.

However, the opcode.def file defines the br instruction to have no parameter, while the br_if instruction does:
![opcode.def](https://user-images.githubusercontent.com/17690423/134525185-508c8106-2569-468e-8a90-ab2a5b7d9f4a.png)

This is quite confusing and creates inconsistencies when using BinaryReader, as _both_ instructions trigger an `OnOpcodeIndex` callback:
![binaryreader](https://user-images.githubusercontent.com/17690423/134525504-e2cb533c-404a-4b47-a701-fb195603000b.png)

Is there a logic behind that which I don't see or is the opcode.def file just poorly maintained?

**Comment by sbc100** [comment]
I believe the `t1` .. `t3` parameters in opcode.def refer to stack operands.    The label that is part of `Br` and `BrIf` istructions are operands but immediates (read directly from the instruction stream and not from the stack).   It doesn't look like information on immediates is part of opcodes.def.

**Comment by julKali** [comment]
Ah, this makes sense, thank you! If you are certain enough that this is correct, please feel free to close this issue.

**Comment by sbc100** [comment]
No problem!
