### ISSUE TITLE
unexpected opcode: 0x18

### ISSUE THREAD

**Issue by kiwenlau** [WebAssembly/wabt#1736]
I use [wasm2wat demo](https://webassembly.github.io/wabt/demo/wasm2wat/) with all features enabled:

<img width="542" alt="截屏2021-10-15 08 20 07" src="https://user-images.githubusercontent.com/10240841/137412779-112a4799-95dc-4c02-8268-63ed77b32a82.png">

The .wasm file is attatched:

[a.out.wasm.zip](https://github.com/WebAssembly/wabt/files/7350026/a.out.wasm.zip)

I got the .wasm by compile following .cpp

```cpp
#include <stdio.h>

int main() {
  try {
    puts("throw...");
    throw 1;
  } catch(...) {
    puts("catch!");
  }
  return 0;
}
```

I compile cpp with [fwasm-exceptions](https://emscripten.org/docs/porting/exceptions.html) flag

```bash
emcc test.cpp -fwasm-exceptions
```

I use emcc 2.0.31 on macbook

```bash
emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.31 (4fcbf0239ccca29771f9044c990b0d34fac6e2e7)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by keithw** [comment]
I believe this has been updated.
