### ISSUE TITLE
GC supporting 

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/wabt#1759]
May I ask the supporting plan about the latest [GC MVP](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md)?  The [GC branch](https://github.com/WebAssembly/wabt/tree/gc) hasn't been updated for a long time.

**Comment by sbc100** [comment]
I think it would be great to get GC support in wabt, but I don't know of anyone actively working on it. 

Closing as duplicate of #1257.. lets continue any discussion there.
