### ISSUE TITLE
binary parser should error out when section size is 0

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#177]
For most sections that size must be none zero.  I had a binary with a TYPE section of size zero that generated the following error:

```
 $ ../wabt/out/wasmdump -h -v ../tmp.wasm 
TYPE         start=0x0000000a end=0x0000000a (size=0000000000)
 - count: 3
error: @0x0000000c: unexpected type form
```

Ideally it would have told me that the TYPE section was invalid because it didn't contain a `count`.

**Comment by binji** [comment]
Ah, it seems the actual issue is that it reading outside of the section.
