### ISSUE TITLE
Build failed on CentOS 7

### ISSUE THREAD

**Issue by Vilko** [WebAssembly/wabt#1773]
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc: In constructor ‘wasm_globaltype_t::wasm_globaltype_t(wasm_valtype_t*, wasm_mutability_t)’:
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:129:22: error: could not convert ‘* type’ from ‘wasm_valtype_t’ to ‘wabt::interp::ValueType {aka wabt::Type}’
         valtype{*type} {
                      ^
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc: In constructor ‘wasm_tabletype_t::wasm_tabletype_t(wabt::interp::TableType)’:
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:152:41: error: cannot convert ‘wasm_limits_t’ to ‘uint32_t {aka unsigned int}’ in initialization
         limits{FromWabtLimits(tt.limits)} {}
                                         ^
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:152:41: warning: missing initializer for member ‘wasm_limits_t::max’ [-Wmissing-field-initializers]
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc: In constructor ‘wasm_memorytype_t::wasm_memorytype_t(const wasm_limits_t*)’:
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:162:23: error: cannot convert ‘const wasm_limits_t’ to ‘uint32_t {aka unsigned int}’ in initialization
         limits{*limits} {}
                       ^
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:162:23: warning: missing initializer for member ‘wasm_limits_t::max’ [-Wmissing-field-initializers]
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc: In constructor ‘wasm_memorytype_t::wasm_memorytype_t(wabt::interp::MemoryType)’:
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:166:41: error: cannot convert ‘wasm_limits_t’ to ‘uint32_t {aka unsigned int}’ in initialization
         limits{FromWabtLimits(mt.limits)} {}
                                         ^
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:166:41: warning: missing initializer for member ‘wasm_limits_t::max’ [-Wmissing-field-initializers]
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc: In function ‘wasm_frame_t* wasm_frame_copy(const wasm_frame_t*)’:
/root/wasm/wabt/src/interp/interp-wasm-c-api.cc:1024:33: error: could not convert ‘* frame’ from ‘const wasm_frame_t’ to ‘wabt::interp::Frame’
   return new wasm_frame_t{*frame};
                                 ^
gmake[2]: *** [CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o] Error 1
gmake[1]: *** [CMakeFiles/wasm.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by keithw** [comment]
Closing per comment.
