### ISSUE TITLE
Wording of error message 'multiple result values not currently supported'

### ISSUE THREAD

**Issue by jzabinski-dolios** [WebAssembly/wabt#1796]
In `SharedValidator::OnFuncType`, there is this code:
```
if (!options_.features.multi_value_enabled() && result_count > 1) {
    result |=
        PrintError(loc, "multiple result values not currently supported.");
  }
```

WABT does indeed support multi-value, however.

Maybe the error message should say 'not currently enabled' when multi-value is disabled.

**Comment by sbc100** [comment]
Yes, that sounds good.   How about `multiple result values are not supported without multi-value enabled`?  Do you have time to send a patch?

**Comment by jzabinski-dolios** [comment]
Will send a patch next week when I am back from vacation
