### ISSUE TITLE
Empty param name in name section for imported functions

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#1799]
See https://github.com/WebAssembly/binaryen/issues/4418 for details. It looks like on imported functions wabt's name section emitting code will emit an empty name for params. That is, the empty string "". That seems like a bug to me as it is not useful for a debugger (the index would be better than the name).

**Comment by timkendrick** [comment]
Just to add some background on this issue - this concerns the output of `wat2wasm --debug-names` being run through binaryen's `wasm-opt` compiler.

`wasm-opt` assumes that all local/param names in the WASM debug `.name` section are non-empty strings (i.e. length > 0), however it appears that `wat2wasm` generates zero-length names for any unnamed function params/locals.

The binaryen team's opinion is that this is a bug in the wat2wasm output and that these empty names should be omitted from the wasm output. The `wasm-opt` compiler will generate warnings for any zero-length names it encounters when parsing the `.name` section.

The [WASM spec](https://webassembly.github.io/spec/core/appendix/custom.html#name-section) doesn't discuss whether zero-length names are valid or ought to be omitted.

As far as I understand it this behavior applies to all unnamed `local` and `param` names (not just imported functions as implied by this issue title).

Minimal example: `(module (func (param i32)))`

wat2wasm `.name` section output:

```
; section "name"
0000019: 00                                        ; section code
000001a: 00                                        ; section size (guess)
000001b: 04                                        ; string length
000001c: 6e61 6d65                                name  ; custom section name
0000020: 02                                        ; local name type
0000021: 00                                        ; subsection size (guess)
0000022: 01                                        ; num functions
0000023: 00                                        ; function index
0000024: 01                                        ; num locals
0000025: 00                                        ; local index
0000026: 00                                        ; string length
0000021: 05                                        ; FIXUP subsection size
000001a: 0c                                        ; FIXUP section size
```

Note the 'empty' local name in 0x24 - 0x26.

If the decision is that these 'empty' local names should be omitted from the debug output, I'm not sure what the behavior ought to be for 'sparsely' named locals.

Take the example `(module (func (param i32) (param $foo i32) (param i32)))`, which produces this `.name` section output:

```
; section "name"
000001b: 00                                        ; section code
000001c: 00                                        ; section size (guess)
000001d: 04                                        ; string length
000001e: 6e61 6d65                                name  ; custom section name
0000022: 02                                        ; local name type
0000023: 00                                        ; subsection size (guess)
0000024: 01                                        ; num functions
0000025: 00                                        ; function index
0000026: 03                                        ; num locals
0000027: 00                                        ; local index
0000028: 00                                        ; string length
0000029: 01                                        ; local index
000002a: 03                                        ; string length
000002b: 666f 6f                                  foo  ; local name 1
000002e: 02                                        ; local index
000002f: 00                                        ; string length
0000023: 0c                                        ; FIXUP subsection size
000001c: 13                                        ; FIXUP section size
```

It's not obvious to me how you could omit bytes 0x27-0x28 and 0x2e-0x2f while still maintaining a valid [indirect name map](https://webassembly.github.io/spec/core/appendix/custom.html#name-maps). This leads me to believe that the current wat2wasm is likely correct, however I definitely wouldn't class myself as an expert on the WASM binary format.

**Comment by sbc100** [comment]
Sounds like a bug in both binaryen and wabt.   I'm happy to fix wabt, but binaryen should probably not warn by default on empty string names.  Empty string is perfectly valid name.

**Comment by kripken** [comment]
> Empty string is perfectly valid name.

Would you expect a debugger or other tool that displays the source in a human-friendly way to print an empty name for a local? I think that would be bad. How would it even look?

**Comment by sbc100** [comment]
> > Empty string is perfectly valid name.
> 
> Would you expect a debugger or other tool that displays the source in a human-friendly way to print an empty name for a local? I think that would be bad. How would it even look?

There are lots of unicode chars that would not look good if you used them in a name section though, right?   (think of a tab char on its own for example).   I don't think it should be up to binaryen to enforce extra rules that are not part of the spec here.

**Comment by kripken** [comment]
True. But at least a unicode name could be rendered somehow with escaping, I think. Binaryen can't print the empty string as a name of a local, though, since `$` is not a valid wat name. So it just has to ignore empty names (as that PR linked in the first comment makes it do). I guess we could ignore them silently, but I think it's better to warn?

**Comment by timkendrick** [comment]
It sounds like empty names are not explicitly forbidden in the spec, and therefore wabt isn't don't anything 'wrong' by generating these, other than adding some unnecessary cruft to the names section (which @sbc100 has mentioned wabt can fix).

Given that binaryen has difficulties in printing these empty names, would a simple solution be for binaryen to just treat any empty names as if it were not specified?

Bear in mind I'm not at all familiar with the internals of either of these libraries so I probably don't have the requisite context, feel free to ignore if I'm oversimplifying the problem.

**Comment by kripken** [comment]
> Given that binaryen has difficulties in printing these empty names, would a simple solution be for binaryen to just treat any empty names as if it were not specified?

Yes, definitely, we could do that. Basically just remove the current warning, and after the PR, we'd be silently "dropping" such names - considering them not specified, as you said.

It's not a binaryen issue, though: I don't think `$` is a valid identifier in the wasm spec for the text format. I didn't look in the spec now, but it is considered invalid in both wabt ("`unexpected token $`") and binaryen ("`parse exception: expected string`").

I guess I don't feel that strongly as it's just a warning. If most people think silent ignoring is better, I'm happy to remove the warning.

**Comment by timkendrick** [comment]
I think perhaps the confusion is coming from an assumption that the debug names need to be valid WAT text format identifiers? I personally didn't assume this to be the case but I can see that would make sense.

TBH the spec isn't particularly clear on this - according to the [name section definition](https://webassembly.github.io/spec/core/appendix/custom.html#name-section):

> The purpose of this section is to attach printable names to definitions in a module, which e.g. can be used by a debugger or when parts of the module are to be rendered in text form.

...so it definitely cites WAT text form rendering as a potential use case for the debug names, however it also says that e.g.

> Each index must be unique, but the assigned names need not be.

This would be invalid in the WAT format which [doesn't allow duplicate identifiers](https://webassembly.github.io/spec/core/text/modules.html#functions) in the same scope (whereas of course languages with variable shadowing do).

So if I'm reading this correctly the spec allows names that would not be valid in the WAT text format, so I'm assuming that debug names are not intended to be restricted to what can legally be represented in the text format.

Anyway I don't feel strongly about this either - personally I'm fine with a warning, but I can also see a strong case for there not being a warning. Either way thanks for the time spent considering this!

**Comment by sbc100** [comment]
Turns out wabt uses the empty string to mean "no name" so I guess wabt can't handle empty strings as names either.  Fix is in: https://github.com/WebAssembly/wabt/pull/1801
