### ISSUE TITLE
wat2wasm gives error: unexpected token get_local

### ISSUE THREAD

**Issue by SathoriStudio** [WebAssembly/wabt#1802]
I have downloaded **wabt** in my Linux Mint machine, but when I try to use the **wat2wasm _file.wat_** command into a simple example like this, it gives me error.

```
(module
(func $add (param $lhs i32) (param $rhs i32) (result i32)
get_local $lhs
get_local $rhs
i32.add)
(export "add" (func $add))
)
```

This is the error:

```
add1.wat:3:5: error: unexpected token get_local, expected ).
    get_local $lhs
    ^^^^^^^^^
add1.wat:4:5: error: unexpected token get_local.
    get_local $rhs
```

The same code in the wat2wasm online demo works fine. When I use `wat2wasm --version` it says my version is 1.0.25.

Any ideas of why the _unexpected token get_local_ error appears? Thanks in advance.

**Comment by graial** [comment]
I had the same experience on arch linux when I cloned the repo
However, the error was gone when I downloaded the latest release instead

**Comment by SathoriStudio** [comment]
Thanks for the advice, @graial !

I have downloaded the **wabt-1.0.24-ubuntu.tar.gz** release and now it seems that wat2wasm is working fine. I also didn't need to "build" using CMake or anything similar, so I suppose that I should have started with the release. Thanks!

**Comment by dgruntz** [comment]
I had the same problem, but I could fix it by replacing `get_local` by `local.get`.

**Comment by sbyun** [comment]
Thanks dgruntz. It worked for me.

**Comment by xgqfrms** [comment]
> I had the same problem, but I could fix it by replacing `get_local` by `local.get`.

## So, what's wrong with that?

Are compiler versions different?

The old version uses `get_local `, but the new version use `local.get`.

**Comment by keithw** [comment]
See #1883 -- `get_local` isn't a valid instruction in WebAssembly. (It used to be called that when WebAssembly was in draft form, but the names were changed in 2018 before the WebAssembly 1.0 spec was published, and wabt dropped support for the draft names in 2021 (https://github.com/WebAssembly/wabt/pull/1792).)
