### ISSUE TITLE
wasm-strip fails on module with SIMD instructions

### ISSUE THREAD

**Issue by repi** [WebAssembly/wabt#1803]
running `wasm-strip` 1.0.24 on one of our Rust-compiled, with SIMD enabled, WASM modules fails with:

```
0000a70: error: expected valid local type
```
and another similar one (repro binary: [opcode_fail_module.wasm.zip](https://github.com/WebAssembly/wabt/files/7854907/opcode_fail_module.wasm.zip)) fail with:
```
00005c7: error: unexpected opcode: 0xfd 0x0
```
have seen a few other variants also:
```
000060b: error: unexpected opcode: 0xfd 0xc
```

The same modules, when compiled without SIMD support in Rust for `wasm32-unknown-unknown` does work to strip. So was suspecting the latest `wasm-strip` release doesn't fully support SIMD instructions.

Maybe solved in later PRs that hasn't had a release yet?

Sounded potentially related to:
- #1617

**Comment by bnjbvr** [comment]
The `opcode_fail_module.wasm` can be properly stripped with 1.0.25, and a quick bisection shows that it started doing so when SIMD has been enabled by default. There's a git tag for 1.0.25, but no github release. Would maintainers mind making a Github release, please?

**Comment by keithw** [comment]
Looks like 1.0.26 and 1.0.27 now have GitHub releases with built artifacts -- closing as this seems to have been done.
