### ISSUE TITLE
Fails reading local name after inlined type

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wabt#1806]
Latest version 1.0.25 seems to fail reading param names following a type field. this is allowed by spec and works with wasm-tools. https://www.w3.org/TR/wasm-core-1/#type-uses%E2%91%A0

```
(module
        (type $i32i32_i32 (func (param i32 i32) (result i32)))
        (import "Math" "Mul" (func $mul (param $x f32) (param $y f32) (result f32)))
        (import "Math" "Add" (func $add (type $i32i32_i32) (param $l i32) (param $r i32) (result i32)))
)
```

```
$ wat2wasm --debug-names --debug-parser -v example.wat
example.wat:4:53: error: unexpected token (, expected ).
... "Add" (func $add (type $i32i32_i32) (param $l i32) (param $r i32) (result...
                                        ^
```

**Comment by codefromthecrypt** [comment]
sorry for the empty desc, I updated it

**Comment by sbc100** [comment]
Do you happen to know if this is regression?  i.e. did it work with some previous release?

**Comment by sbc100** [comment]
This seems to fail at least as far back as 1.0.22.   I guess this means that spec tests are also missing a test case for this.

**Comment by codefromthecrypt** [comment]
timezone fail :) yeah I actually upgraded only to make sure it wasn't magically fixed. thanks for looking into this
