### ISSUE TITLE
Move to c++ 17

### ISSUE THREAD

**Issue by dbezhetskov** [WebAssembly/wabt#1811]
Some features are really hard to implement without typed unions like std::variant and other features from c++17.

For example, with typed function references and gc proposal we have named types during parsing `(ref null $foo_func)` and `(ref null $struct_type)` but we can't just add `std::string` to struct Type because we use Type as a member of unions in `struct InitExpr` and `struct ActionResult`. So, in the end we need to maintain maps: type_name -> its index during parsing and this is awful because possibly any thing in WebAssembly from local and global to function and table can have named type.

It is 2022 and we still use c++ 2011, so I propose to move to c++17, wdyt? @sbc100

**Comment by sbc100** [comment]
Sounds reasonable to me yes.   Both chromium and binaryen both recently switch to C++17.   I think we could do that same here most likely.

Would you like to send an initial PR?
