### ISSUE TITLE
Local names in wasm-objdump -x

### ISSUE THREAD

**Issue by mwilliamson** [WebAssembly/wabt#1815]
So far as I can tell, wasm-objdump doesn't use local names when printing instructions such as local.get. I wanted to check if this was so (rather than, for instance, my test file specifying the names incorrectly -- wasm2wat includes the names, so I assume this isn't the case), and whether there would be any interest in changing the behaviour to include the names of locals?

**Comment by sbc100** [comment]
I think you are correct in that objdump is just missing this feature.  Please feel free to send a PR.

One reason this might not have been notices (by myself at least) is that llvm doesn't generate local names so its not useful when dumping the output of the llvm-based compilers.
