### ISSUE TITLE
wat2wasm produces non-cannonical varint

### ISSUE THREAD

**Issue by dominictarr** [WebAssembly/wabt#1816]
I was inspecting the binary wasm file to clarify the wasm spec, and I noticed that version `1.0.23` of `wat2wasm` was producing non-canonical varints, for the `i32.const` I checked on the current main branch and it's a problem there too, it doesn't seem it was fixed by: https://github.com/WebAssembly/wabt/pull/1632

to reproduce:

```
(module

  (func $get (export "get") (result i32)
    (i32.const 64) ;; double byte varint!!!
  ;;(i32.const 63) ;; single byte varint
  )
)
```
```
> wat2wasm params.wat && hexdump params.wasm -C
00000000  00 61 73 6d 01 00 00 00  01 05 01 60 00 01 7f 03  |.asm.......`....|
00000010  02 01 00 07 07 01 03 67  65 74 00 00 0a 07 01 05  |.......get......|
00000020  00 41 c0 00 0b                                    |.A...|
00000025

```

that last line: `00 41 c0 00 0b`. 0x41 is encoding for `i32.const` which is followed by a varint. `c0 00` encodes 64, but so does `40`! (without needing another byte!) 8192 also uses 3 bytes to encode when it should only take 2.

**Comment by dominictarr** [comment]
sorry, it's actually correctly encoding signed numbers https://en.wikipedia.org/wiki/LEB128#Encode_signed_integer

**Comment by keithw** [comment]
Closing as seemingly resolved (please comment or reopen if this still needs attention).
