### ISSUE TITLE
wabt2wasm error: unexpected token get_local

### ISSUE THREAD

**Issue by Phoenixkaze** [WebAssembly/wabt#1820]
Build from source on macOS 12.3 beta with cmake 3.19.2

The input file (add1.wat) should not contain any errors.
```
(module
  (func $add (param $lhs i32) (param $rhs i32) (result i32)
    get_local $lhs
    get_local $rhs
    i32.add)
  (export "add" (func $add))
)
```

Run `wat2wasm add1.wat  -o add.wasm`
Given error
```
add1.wat:3:5: error: unexpected token get_local, expected ).
    get_local $lhs
    ^^^^^^^^^
add1.wat:4:5: error: unexpected token get_local.
    get_local $rhs
    ^^^^^^^^^
```

**Comment by keithw** [comment]
You'll have to use `local.get` now instead of `get_local` -- the names were changed in 2018 before the WebAssembly 1.0 spec was finalized, and wabt dropped support for the pre-1.0 names late last year (#1792).

**Comment by Phoenixkaze** [comment]
Thank you. Reading some old books published years ago, it really confused me.
