### ISSUE TITLE
We should have an AppVeyor build

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#186]
We should have a windows continuous build with GH integration. An external contributor wrote a build file for Binaryen (https://github.com/WebAssembly/binaryen/pull/623) and I set up a WebAssembly AppVeyor account to run it; we can probably just copy from that.

**Comment by binji** [comment]
Agreed, I'd be happy if someone figured this out and made it work. :)

**Comment by dschuff** [comment]
Done, and working in #201
