### ISSUE TITLE
unexpected token "anyfunc", expected a natural number

### ISSUE THREAD

**Issue by bitoceango** [WebAssembly/wabt#1863]
My wat is :

```
(module
  (func $thirteen (result i32) (i32.const 13))
  (func $fourtytwo (result i32) (i32.const 42))
  (table (export "tbl") anyfunc (elem $thirteen $fourtytwo))
)
```

when i excute ：

`wat2wasm table.wat -o table.wasm`

I get an error:

```
table.wat:4:25: error: unexpected token "anyfunc", expected a natural number (e.g. 123).
  (table (export "tbl") anyfunc (elem $thirteen $fourtytwo))
                        ^^^^^^^
table.wat:4:49: error: undefined table variable "$fourtytwo"
  (table (export "tbl") anyfunc (elem $thirteen $fourtytwo))
```

wat2wasm do not support anyfunc?

**Comment by sbc100** [comment]
`anyfunc` was renamed to `funcref` in #1026.    It was also rename in the main spec interpreter back in 2018: https://github.com/WebAssembly/spec/pull/926

**Comment by binji** [comment]
That used to work even with the old name though. I guess the deprecated name was removed?

**Comment by sbc100** [comment]
Yup it looks like support for the deprecated name was deliberately dropped back in December: #1792
