### ISSUE TITLE
How to extract source code from Native Client .nexe file, migrate to WebAssembly?

### ISSUE THREAD

**Issue by guest271314** [WebAssembly/wabt#1864]
This is probably not within the purvey of `WebAssembly` though you are th experts re compilation/decompilation of native code, and Google recommends migrating from Native Client to WebAssembly https://developer.chrome.com/docs/native-client/migration/.

Google released an extension which relies on Native Client that includes a voice that can be used with Web Speech API `window.speechSynthsis.speak()`. In that extension exists speech synthesis engine in the form of .nexe [US English Female Text-to-speech (by Google](https://chrome.google.com/webstore/detail/us-english-female-text-to/pkidpnnapnfgjhfhkpmjpbckkbaodldb).

What I want to do is extract the C++ source code from the .nexe file and migrate from the deprecated Native Client to WebAssembly.

How do I achieve that?

**Comment by guest271314** [comment]
I tried
```
$ llvm-objdump --arch-name=wasm64 -d tts_service_x86_64.nexe

```
which prints a series of 

```
invalid_type, invalid_type ...
```

**Comment by sbc100** [comment]
nexe files contains x86 instructions, so you won't want to specify the wasm64 arch when using objdump on them.

There is no way to automatically convert x86 instructions (in the nexe) into WebAssembly instruction.  The migration path from Native Client to WebAssembly involves to back to the source code and re-compiling, rather than binary file transltion.

**Comment by guest271314** [comment]
I have not been able to locate the source code for nexe files. 

All I have located is the nexe files in the extension and https://chromium-review.googlesource.com/c/chromiumos/platform/assets/+/1093522/.

**Comment by guest271314** [comment]
> There is no way to automatically convert x86 instructions (in the nexe) into WebAssembly instruction. 

According to [Automatically convert x86 assembly to C](https://reverseengineering.stackexchange.com/questions/4642/automatically-convert-x86-assembly-to-c) there is a way to convert x86 assembly to C. 

C to WebAssembly intruction appears possible [Compiling a New C/C++ Module to WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm) so what am I missing in the flow chart that does not allow direct conversion from nexe to WebAssembly instruction?

I really want to read the C/C++ source code before attempting to convert to wasm, however the last time I ran `objdump >> file` the machine froze as the nexe is 25MB. Ideally I pipe the dumpt directly to a program that converts to C/C++, if that is possible, then test converting to WASM.

**Comment by sbc100** [comment]
Its not really feasible to take the automatic conversion path since that APIs used by WebAssembly and NaCl are also very different.     Unless you are really determined and have a lot of resources I just don't think its a reasonable approach.

**Comment by guest271314** [comment]
The source code for tts_service_x86_64.nexe must be somewhere in Google source code.

> Unless you are really determined and have a lot of resources

Yes, I am really determined. I have been working on this subject matter since at lest 2017 https://lists.w3.org/Archives/Public/public-speech-api/2017Jun/0000.html. That is why I wrote https://github.com/guest271314/SpeechSynthesisRecorder (which is how we ultimately get to the present issue, detailed below), https://github.com/guest271314/native-messaging-espeak-ng,https://github.com/guest271314/SSMLParser, and https://github.com/guest271314/captureSystemAudio.

The context for this issue is this answer https://stackoverflow.com/a/70665493 only captures silence. I contacted the author and advised him of the history of the topic re the specification and implementation issues I had filed. I linked to https://github.com/espeak-ng/espeak-ng/tree/master/chromium_extension, which is based on one of the links above. They replied that the voice was not up to par. They filed https://stackoverflow.com/questions/70694704/tts-software-used-in-chrome-for-speechsynthesis trying to locate source of PATTS. Based on deduction I concluded tts_service_x86_64.nexe must be assembly code of the in-house Chrome speech synthesis engine, designed to work with Google voices. Thus I began attempting to "reverse engineer" the code we have.

>  I just don't think its a reasonable approach.

I am open to reasonable approaches you suggest.

**Comment by guest271314** [comment]
On the specification side, capture of entire system audio (or specific application) output, e.g., `speech-dispatcher`, has gotten passed around to various working groups that wind up just passing the buck back to other working groups, and nothing actually gets done over the course of years, TL:DR https://github.com/WebAudio/web-audio-api/issues/2478#issuecomment-1066107407, as if users in the field are not supposed to notice cicular references in human interactactions among groups - with zero net result therefrom, while authors who write code that winds up in browser source code are some of the smartest people on this planet. It must be a concious decision to not implement certain features to remedy use cases that are not possible per any existing specification.

Re speech synthesis engines specifically, well, in my view that is, while time and energy consuming to get right https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency/, is mainly viewed as propietary; a means to generate revenue by certain vendors/implementers, e.g., "Contact sales" at https://cloud.google.com/text-to-speech. Fine. In the meantime users are left to fend for themselves (https://github.com/coqui-ai/TTS; above re capturing audio output to speakers) to implement the use cases described.

I just asked if there was any way to get a hold of the source code of  tts_service_x86_64.nexe here since this appears part of prior art of WebAssembly and Native Messaging to some extent. And Google employees/affiliates might have access to  tts_service_x86_64.nexe. I didn't notice any license or royaly usage EUA attached to the files.

I look forward to your suggestions as how to get the source code of tts_service_x86_64.nexe in a form that is capable of being used, modified, improved, etc., by developers in the field - by any means. Thanks.

**Comment by sbc100** [comment]
This doesn't sounds like a issue that wabt can help you to solve.   Reverse engineering x86/x64 binaries is not something wabt can help you with I'm afraid.

**Comment by guest271314** [comment]
What approaches do you suggest?

**Comment by guest271314** [comment]
```
$ hd tts_service_x86_64.nexe
```

and

```
$ strings tts_service_x86_64.nexe
```

provide some details https://gist.github.com/guest271314/4894662d31ffb4ad2cd57683721bf4b4. Still some work to do.
