### ISSUE TITLE
call_indirect in wasm-objdump switches x and y

### ISSUE THREAD

**Issue by gerritsangel** [WebAssembly/wabt#1865]
I'm not quite sure if this a bug, but I think it's not quite in sync with the official spec.

From my wasm file's disassembly, wasm-objdump generate the following line:

```
 00b994: 11 87 80 80 80 00 00       |   call_indirect 7 0
```

This here should have the type index 7 and the table index 0. Unfortunately, it seems that this is reversed. The [binary docs](https://webassembly.github.io/spec/core/binary/instructions.html#control-instructions) write:

```
0x11 y:typeidx x:tableidx  => call_indirect x y
```

I'm not sure why this is reversed, but I think it's a bit misleading (At least it confused me while implementing my Webassembly runtime :D).

**Comment by sbc100** [comment]
I think the binary spec is a little odd here.. its reversing the order of x and y when compared to how they appear in the format.
The way the wasm-objdump works is that it lists the immediates in the order they appear in the binary, and in the case of call indirect the type index comes first, then the table.   See 

We could make maybe maybe special case this instruction they I think that could also be confusing. For a program like objdump where you hare displaying the raw bytes alongside the instruction i  think maintain the order of the immediates makes sense.  For example if you look at the bytes on the left you can see that the number 7 (87 80 80 80 00) comes before the number zero (00).   

Here is the method that prints the call_indirect instruction: https://github.com/WebAssembly/wabt/blob/d0e5fe79a0a330ff77e18e2d154d48a24ee4077e/src/binary-reader-objdump.cc#L764 .. and here is the call site: https://github.com/WebAssembly/wabt/blob/d0e5fe79a0a330ff77e18e2d154d48a24ee4077e/src/binary-reader.cc#L846 .. We could flip the arguments at the call site maybe?  But i'm not sure its great idea.

**Comment by gerritsangel** [comment]
I understand that the binary itself first lists y, then x. Not sure why it's like that, though. Somehow, it's seems more like a bug in the binary format than in the spec. 

In all other places for `call_indirect`, the specs first like x, then y, as in: https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-call-indirect-x-y

Unfortunately, I think the current objdump behaviour might be confusing when e.g. comparing with the WASM text format.

What I found with a quick search is:

* `call_indirect` has reverse order in the binary format
* `table.init` also has reverse order in binary format
* `table.copy` has same order in binary format.

**Comment by sbc100** [comment]
Don't think you there is an argument for making the objdump format match the binary data rather than the text format (since it is displayed side-by-side with the binary format on the left?)

We could flip the argument so that the we match the text format, but that could also be confusing.  Alternatively we could give names to the immediate?  e.g. `call_indirect idx=7 table=0`?

**Comment by sbc100** [comment]
Perhaps we could add some kind of `--verbose` option to the disassembly that adds names to immediates?

**Comment by binji** [comment]
It might be best to use the text format for `call_indirect`, e.g. `call_indirect <table#> (type <type#>)`. Though I agree that it's nice to see the values line up between the decoding and the bytes on the left.

**Comment by sbc100** [comment]
OK, this seems better: https://github.com/WebAssembly/wabt/pull/1866
