### ISSUE TITLE
Issue decoding table elements

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wabt#1878]
1.24 has no problem, but current versions including latest mistake the table element ID for re-defining the element:

```bash
~/Downloads/wabt-1.0.28/bin/wast2json --debug-names ./tests/spectest/testdata/elem.wast
./tests/spectest/testdata/elem.wast:16:4: error: redefinition of elem "$t"
  (elem $t (i32.const 0) $f $f)
   ^^^^
./tests/spectest/testdata/elem.wast:17:4: error: redefinition of elem "$t"
  (elem $t (offset (i32.const 0)))
   ^^^^
./tests/spectest/testdata/elem.wast:18:4: error: redefinition of elem "$t"
  (elem $t (offset (i32.const 0)) $f $f)
   ^^^^
```

**Comment by keithw** [comment]
The bulk memory operations proposal changed the text format (and the spec test was revised at the same time). You can still parse the 1.0 syntax by passing the `--disable-bulk-memory` option to `wast2json`.

**Comment by codefromthecrypt** [comment]
thanks for the tip. yeah we are still working on w3c recommendations not things that came after it. I'll wind back that setting.

**Comment by codefromthecrypt** [comment]
sorry other things are failing. Is there a way to know which features are enabled by default?

**Comment by codefromthecrypt** [comment]
meanwhile I added flags to disable everything except mutable globals which are there in 1.0

**Comment by sbc100** [comment]
> sorry other things are failing. Is there a way to know which features are enabled by default?

There is a table to features in the README which lists which ones are enabled by default: https://github.com/WebAssembly/wabt#supported-proposals

**Comment by codefromthecrypt** [comment]
thanks. maybe one suggestion would be to change the help output to include this info. I suppose I could have been more precise that I was wondering if the CLI can answer this. Meanwhile I'll put a comment where we use things to look at this table and keep track (for the areas where we need things to stay 1.0 compatible)

**Comment by codefromthecrypt** [comment]
I realize I never formally asked for the feature to constrain to 1.0 (I did ask for a chart on the website, but that's a different matter).

`--enable-1.0` can substitute for CLI output that says what's enabled and is a better solution  (at least for me) https://github.com/WebAssembly/wabt/issues/1899
