### ISSUE TITLE
wat2wasm failing with: unexpected token get_local, expected ).

### ISSUE THREAD

**Issue by AloisReitbauer** [WebAssembly/wabt#1883]
This is the wat file used:

```wat
(module
    (func $how_old (param $year_now i32) (param $year_born i32) (result i32)
        get_local $year_now
        get_local $year_born
        i32.sub)

    (export "how_old" (func $how_old))
)
```
I am using the binary for 1.0.28

**Comment by AloisReitbauer** [comment]
I also tried with 1.0.27. Same error

**Comment by keithw** [comment]
You'll have to use `local.get` now instead of `get_local  -- the names were changed in 2018 before the WebAssembly 1.0 spec was finalized, and wabt dropped support for the pre-1.0 names late last year (https://github.com/WebAssembly/wabt/pull/1792). (Dup of #1820)

**Comment by AloisReitbauer** [comment]
Thank you that worked!
