### ISSUE TITLE
RFE: Make online wat2wasm demo output base64

### ISSUE THREAD

**Issue by FGasper** [WebAssembly/wabt#1891]
It would be great to be able to copy-paste the binary .wasm output as base64 rather than having to download it.

Thank you!

**Comment by binji** [comment]
That seems like a reasonable change for the demo, do you think you could implement it and send a PR?

**Comment by FGasper** [comment]
I’ll have a look, sure.

**Comment by zherczeg** [comment]
I have made a PR for this issue: #1903
I hope it is not a problem.

**Comment by zherczeg** [comment]
I think this can be closed now.
