### ISSUE TITLE
wasm2c compilation error: 'setjmp.h' cannot be found

### ISSUE THREAD

**Issue by arjunr2** [WebAssembly/wabt#1914]
In the process of re-compiling the output of `wasm2c`, the `wasm-rt-impl.c` file requires `setjmp.h`, which cannot be found by the wasi-sdk clang release.

How do you get around this? Thanks!

**Comment by sbc100** [comment]
The wasm2c runtime currently requires setjmp.   You should be able to build all the other targets.  You can do that either by just running, for example, `ninja wasm2wat` or `make wasm2wat`. or you could modify the CMakeLists.txt to skip the building of wasm-rt-impl for WASI (like we currently do for win32): https://github.com/WebAssembly/wabt/blob/d030cfc662a84993b3d8db6591153176dbda5fe3/CMakeLists.txt#L364

**Comment by arjunr2** [comment]
Ok, is the wasm2c README up to date? It seems like the generated headers and export functions are different from those documented

**Comment by sbc100** [comment]
Its conceivable the docs are out of date yes.  Can you elaborate?

**Comment by arjunr2** [comment]
The `wasm2c` as of release 1.0.27 does not have definition and implementations for some of the `wasm_rt_*` functions.

I fixed that by cloning the repo and manually building it. However, now the generated WASI functions cannot be detected by the wasi-sdk clang 
```wasm-ld: error: /tmp/sample-f15563.o: undefined symbol: Z_wasi_snapshot_preview1Z_proc_exit
wasm-ld: error: /tmp/sample-f15563.o: undefined symbol: Z_wasi_snapshot_preview1Z_fd_close
wasm-ld: error: /tmp/sample-f15563.o: undefined symbol: Z_wasi_snapshot_preview1Z_fd_fdstat_get
wasm-ld: error: /tmp/sample-f15563.o: undefined symbol: Z_wasi_snapshot_preview1Z_fd_seek
wasm-ld: error: /tmp/sample-f15563.o: undefined symbol: Z_wasi_snapshot_preview1Z_fd_write
wasm-ld: error: /tmp/wasm-rt-impl-19744f.o: undefined symbol: longjmp
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sbc100** [comment]
Yes, those are external imports that your wasm module depends on.  Its up to you to define those when using wasm2c.

**Comment by sbc100** [comment]
Regarding the definitions of the wasm_rt functions.. did you try 1.0.28?  I will do a 1.0.29 release now.

**Comment by arjunr2** [comment]
Ok, thanks! I did try 1.0.28, but it wasn't in there.

**Comment by keithw** [comment]
Closing as it sounds like this has been fixed by the new release. If you do implement a version of the wasm-rt-impl.h/c that works on WASI, it would be fun to see it!
