### ISSUE TITLE
wamrc: Compiling generated LL files

### ISSUE THREAD

**Issue by arjunr2** [WebAssembly/wabt#1916]
It looks like `wamrc` currently supports generating LLVM optimized and unoptimzed code. I am looking to run some instrumentation passes on this LL file and generate an AoT executable again. 

However, function labels seem to be discarded in the generated LL file (particularly the `main` or `start` function), and it cannot be re-compiled using `clang`. Is there a way to generate Wasm/AoT code from the generated LL file?

Thanks!

**Comment by sbc100** [comment]
I think you might have the wrong project.  I don't think `wamrc` is part of wabt.

**Comment by arjunr2** [comment]
Oops, sorry about that. I will close this issue.
