### ISSUE TITLE
Use wasm2c to convert unityweb into c

### ISSUE THREAD

**Issue by weiforce** [WebAssembly/wabt#1926]
I convert the file into a C file and compile the code using gcc.

`mv webgl.wasm.unity webgl.wasm.gz`
`gunzip webgl.wasm.gz`
`wasm2c webgl.wasm`
`gcc -c webgl.wasm -o webgl`

gcc quits the shell without any prompt.

**Comment by keithw** [comment]
wasm2c has a README that you might find helpful: https://github.com/WebAssembly/wabt/blob/main/wasm2c/README.md

It gives some advice on how to use it and compile the output.

You'll probably want to use a "-o webgl.c" option to wasm2c (as shown in that README).

Then you'll want to use the compiler to compile the resulting ".c" file (not a ".wasm" file). Eventually you'll want to link that object file with the Wasm runtime (an example is included with wasm2c, and demonstrated in the README), as well as an implementation of whatever that Wasm module imports.

It's likely that this Wasm module imports a ton of functions from the outside world -- you'll have to provide implementations of those for it to work as desired.

Good luck!
