### ISSUE TITLE
wast2json changes element section contents in `(module binary ...)`

### ISSUE THREAD

**Issue by osa1** [WebAssembly/wabt#1927]
Tried with d8517aa9.

test.wast:

```wast
(module binary
  "\00asm" "\01\00\00\00"
  "\04\04\01"                          ;; Table section with 1 entry
  "\70\00\00"                          ;; no max, minimum 0, funcref
  "\09\09\01"                          ;; Element section with 1 entry
  "\02"                                ;; Element with explicit table index
  "\80\00"                             ;; Table index 0, encoded with 2 bytes
  "\41\00\0b\00\00"                    ;; (i32.const 0) with no elements
)
```

(Copied from [spec test suite][1])

Generate Wasm module with wast2json:

```
$ wast2json test.wast 
```

Generated Wasm module is different than the input module:

```
$ hd test.0.wasm
00000000  00 61 73 6d 01 00 00 00  04 04 01 70 00 00 09 06  |.asm.......p....|
00000010  01 00 41 00 0b 00                                 |..A...|
00000016
```

Note that after `0x09` (element section), section size is 6 in the generated Wasm module. In the input the section size is 9. Section contents (element segments) are also different.

[1]: https://github.com/WebAssembly/testsuite/blob/e25ae159357c055b3a6fac99043644e208d26d2a/binary-leb128.wast#L32-L40

**Comment by sbc100** [comment]
Hmm.. that does seems like a serious issue.  wast2json should simply be writing those bytes out verbatim.   Any idea whats going on?

**Comment by osa1** [comment]
As far as I understand, when wast2json sees a `(module binary ...)` it still parses the module and then converts the parsed module back to binary. So it doesn't directly emit the bytes it sees.

I just checked and the module contents are as expected after `WastParser::ParseScriptModule`.

However for binary modules `WastParser::ParseModuleCommand` still parses the module contents to a `Module`: https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/wast-parser.cc#L3319-L3343

In the code above, `bsm->data` is correct, so the problem should be when serializing the parsed module back to binary. It seems like the module deserializer and serializer do not have roundtrip property: if you deserialize a binary module and serialize it again you sometimes get a different serialization.

This may or may not be a problem, depending on what wast2json wants to do. I'm not a Wasm expert but I'm guessing it's possible to have two different binary encodings of a single module (e.g. we can probably add empty sections without changing module semantics?).

However when using wast2json to make it easier to run Wasm spec test suite it becomes a problem, as this behavior effectively changes test inputs.

**Comment by sbc100** [comment]
The entire point of the `(module binary` directive is to create a binary module that has the exact byte-for-byte layout specified in that directive.     This includes invalid bytes, for example, so its not possible to round trip such modules.  

So I'm confused as to why wast2json would try to turn those into Ir.. that seems wrong.. and can obviously fail if the module is not valid.

**Comment by osa1** [comment]
Good point re: invalid modules. I just realized as I investigate this more that `wast2json` has special handling of `assert_malformed` expressions. For example, if I generate .wasm for this example [from the spec test suite][1]:

```wast
  (module binary
      "\00asm" "\01\00\00\00"
      "\02\04\01"                           ;; import section with single entry
      "\00"                                 ;; string length 0
      "\00"                                 ;; string length 0
      "\80"                                 ;; malformed import kind
  )
```
It fails:
```
$ wast2json test.wast
test.wast:1:4: error: error in binary module: @0x0000000e: malformed import kind: 128
  (module binary
   ^^^^^^
```
If I put this module inside a `assert_malformed`, then it generates a .wasm binary as expected:
```wast
$ wast2json test.wast
$ hd test.0.wasm
00000000  00 61 73 6d 01 00 00 00  02 04 01 00 00 80        |.asm..........|
0000000e
```
This probably means for `assert_malformed` tests in Wasm test suite wast2wasm works as expected. However for other modules it still changes module encoding. [My original example][2] is encoded differently in wast2wasm-generated .wasm file, and as a result the test input is changed by wast2wasm and it cannot be used to run Wasm test suite.

[1]: https://github.com/WebAssembly/spec/blob/1b849c713eff03474e78352042fb51a79043b110/test/core/binary.wast#L1424-L1433
[2]: https://github.com/WebAssembly/testsuite/blob/e25ae159357c055b3a6fac99043644e208d26d2a/binary-leb128.wast#L32-L40

**Comment by sbc100** [comment]
I see that makes a little more sense.

The the module is not malformed, then what harm is there is roundtripping it though IR?   Aren't these differences in the binaryen un-observable/harmless?

**Comment by sbc100** [comment]
the test you link to does pass under wabt:

```
$ ./test/run-tests.py test/spec/binary-leb128.txt 
[+1|-0|%100] (0.12s) test/spec/binary-leb128.txt
```

**Comment by osa1** [comment]
The test is fine. The problem is when I generate the binary-encoded Wasm for that test using wast2json the test input changes. In my original message I show the differences. In the test the element section is:

```
09 09 01 02 80 00 41 00 0b 00 00
```

In the wast2json-generated .wasm file it is:

```
09 06 01 00 41 00 0b 00
```

The difference may not matter for spec-compliant compilers/interpreters, but when you try to achieve spec compliance you don't want another spec-compliant tool to change your test inputs. These two modules are probably the same (haven't tried decoding yet), but there is probably a reason why the spec test suite encodes it the way it encodes it.

**Comment by osa1** [comment]
>  Aren't these differences in the binaryen un-observable/harmless?

They are probably harmless, that's why I say "this may or may not be a problem". It just makes wast2json unsuitable for generating binary-encoded Wasm modules for the modules in Wasm test suite.

**Comment by sbc100** [comment]
I see... are you trying to run the results of `wast2json` in a non-wasm tool?  In that case, I agree it would make sense to fix this.

For the purpose of verifying if wabt itself is spec compliant, I'm not sure it needs fixing, since the binary parser used by `wast2json` shown that is can parse the binary.

**Comment by osa1** [comment]
> I see... are you trying to run the results of wast2json in a non-wasm tool? In that case, I agree it would make sense to fix this.

Yes, I'm using wast2json to avoid parsing Wast when running Wasm test suite.

---

To clarify what I mean, I decoded the binary in the Wasm test suite and the binary wast2json generates. Here's the original binary:

```
09      ;; element section
09      ;; section size = 9 bytes
01      ;; vec(elem) size = 1
02      ;; segment tag = 2 (active, with explicit table index)
80 00   ;; table index = 0, encoded in 2 bytes
41 00   ;; i32.const 0
0b      ;; end
00      ;; elem kind = 0 (funcref)
00      ;; vec(funcidx) size = 0
```

Here's the binary wast2json generates for the same section:

```
09      ;; element section
06      ;; section size = 6 bytes
01      ;; vec(elem) size = 1
00      ;; segment tag = 0
41 00   ;; i32.const 0
0b      ;; end
00      ;; vec(funcidx) vec size = 0
```

In the original binary the section tag is 2, so it's an active segment with explicit table index. In the binary generated by wast2json the tag is 0, so active segment with no element kind and no explicit table kind. Semantically these two are the same (i.e. make no difference in execution). However the first one tests parsing an active element segment with explicit table index and element kind. wast2json effectively changes this test, converts it into a test for an active element segment with no explicit table index and no element kind.

---

If you don't consider this a bug in wast2json please feel free to close. I was under the impression that, since wast2json can parse Wasm test suite inputs (the .wast files in spec/test/core), I should be able to use it when testing my implementation against Wasm spec test suite, but maybe that's not a goal for wast2json.

**Comment by sbc100** [comment]
No, I think this is a reasonable thing to want to do with wast2json.  You are just the first person I've heard of that is using it this was.

Do just to be clear, you have your own wasm engine and you want to use wast2json to decompose the spec spec tests into individual wat files for running tests against your engine?   If that is the same I'm happy to help you fix this bug, to accept patches to fix it.

**Comment by osa1** [comment]
> Do just to be clear, you have your own wasm engine and you want to use wast2json to decompose the spec spec tests into individual wat files for running tests against your engine?

This is exactly what I'm doing. My Wasm interpreter is available here: https://github.com/osa1/wasmrun I'm calling wast2json [here](https://github.com/osa1/wasmrun/blob/e0a44b63d0ae869c6561e44fe741ed31994f0df7/crates/spec-test/src/main.rs#L177-L182) to generate binary Wasm modules (which my interpreter can parse) and JSONs for the tests.

>  If that is the same I'm happy to help you fix this bug, to accept patches to fix it.

Great! Not sure if I'll have the time soon but I'll ping you if I have any questions.

**Comment by osa1** [comment]
This seems to be fixed with the commit referenced above.
