### ISSUE TITLE
multi instance of wasm2c support

### ISSUE THREAD

**Issue by calvin2021y** [WebAssembly/wabt#1933]
from the example https://github.com/WebAssembly/wabt/blob/main/wasm2c/README.md, no multi instance example.

I mean create multi vm instance, and load diff module and run at diff memory block.

**Comment by keithw** [comment]
Please see #1814, which adds multi-instance support. Here is the example in the README: https://github.com/fixpointOS/wabt/blob/module_instancing/wasm2c/README.md#instantiate-multiple-instances-of-a-module

**Comment by calvin2021y** [comment]
This solution is hard to work on, if you has a lot export and has a lot arguments .

A better solution will be create module_instance_t from vm instance object, and just pass module_instance_t into export function like this:

```c
  u32 x = atoi(argv[1]);

  vm  = wasm_rt_init();
  module_instance1 = Z_fac_init_module(vm);
  module_instance2 = Z_fac_init_module(vm);

  u32 result1 = Z_facZ_fac(&module_instance1, x);
  u32 result2 = Z_facZ_fac(&module_instance1, x);

  Z_fac_free(module_instance1);
  Z_fac_free(module_instance2);
  wasm_rt_free(vm);

```

**Comment by sbc100** [comment]
I believe that is pretty much exactly how the solution to #1814 works.  You pass in the module instance as arg0 and all the other args follow it.  It just happens that in the example the rot13 functions takes zero arguments.

**Comment by keithw** [comment]
Yeah, if you want to see the factorial function, check out https://github.com/fixpointOS/wabt/blob/module_instancing/wasm2c/examples/fac/main.c . It looks pretty similar to what you want...

**Comment by calvin2021y** [comment]
Sorry for mis understood.

I am read the example from the link https://github.com/fixpointOS/wabt/blob/module_instancing/wasm2c/README.md#instantiate-multiple-instances-of-a-module

```c
  /* Call `rot13` on first two argument, using the mangled name. */
  assert(argc > 2);
  host_instance_1.input = argv[1];
  Z_rot13Z_rot13(&rot13_instance_1);
  host_instance_2.input = argv[2];
  Z_rot13Z_rot13(&rot13_instance_2);
```

Is this document should be updated ?

Can I use it this way ?

```c

  Z_fac_module_instance_t module_instance1;
  Z_fac_instantiate(&module_instance1);
  Z_fac_module_instance_t module_instance2;
  Z_fac_instantiate(&module_instance2);

  u32 result1 = Z_facZ_fac(&module_instance1, x);
  u32 result 2= Z_facZ_fac(&module_instance2, x);

  Z_fac_free(&module_instance1);
  Z_fac_free(&module_instance2);
```

**Comment by sbc100** [comment]
Yes, rot13 is different because it doesn't take any arguments.   Instead it calls a host function to get its data.

Function arguments (or which rot13 has 0 and fac has 1) are passed as C arguments, as in your second example.

The documentation is showing how to setup two different host instances, not how to pass arguments to functions.
