### ISSUE TITLE
Bulk memory problem with wat2wasm + wasm2c

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#1934]
I have a WASM program written in text format that uses bulk memory operations.
When using wat2wasm, and then passing that output to wasm2c, I get the following error:

> error: unexpected opcode: 0xfc 0xa

I'm using WABT 1.0.29 on macOS.

**Comment by keithw** [comment]
wasm2c mainline doesn't yet support bulk memory operations, but you're very welcome to test out the PR at https://github.com/WebAssembly/wabt/pull/1877 which adds it, and I'd be grateful for any bug reports!

**Comment by remko** [comment]
@keithw Thanks. That branch works for me. Looking forward to seeing it merged.
