### ISSUE TITLE
0000075: error: invalid section code: 12

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [WebAssembly/wabt#1935]
wasm2c (v1.0.23) throws 0000075: error: invalid section code: 12

Checked spec, and there is such a section:
https://webassembly.github.io/spec/core/binary/modules.html#data-count-section

**Comment by keithw** [comment]
Section 12 was added by the bulk memory operations proposal. It is implemented in wasm2c in this pending PR: #1877
