### ISSUE TITLE
wat2wasm compiles to .wasm with no options, contrary to documentation

### ISSUE THREAD

**Issue by markdirish** [WebAssembly/wabt#1941]
Hello!

Just getting started with WebAssembly. Downloaded, built, and installed the `wabt` repository on my Windows system.

I created a simple `.wat` file (`test.wat`):

```wat
(module)
```
Then, I ran `wat2wasm` to "parse and typecheck" the file:

```bash
$ wat2wasm test.wat
```
I was surprised to see that it actually compiled my `test.wat` to `test.wasm` as well. The help text from the binary indicates:

> examples:
>   \# parse and typecheck test.wat
>   $ wat2wasm test.wat
> 
>   \# parse test.wat and write to binary file test.wasm
>   $ wat2wasm test.wat -o test.wasm
> 
>   \# parse spec-test.wast, and write verbose output to stdout (including
>   \# the meaning of every byte)
>   $ wat2wasm spec-test.wast -v

Perhaps the help text for running without a `-o` option should indicate that a `.wasm` file will be created with the same filename as the input `.wat` file? Or, if this is actually a bug, should be fixed to only "parse and typecheck" the input file.

**Comment by sbc100** [comment]
(feel free to send a PR)

**Comment by markdirish** [comment]
Will do tonight!

**Comment by markdirish** [comment]
Created a PR.

Did a little more digging, and it definitely seems intended that it _always_ build a binary, and default to the same name was the `.wat` file when the `-o` flag is not set:

https://github.com/WebAssembly/wabt/blob/57e6a58bfdd0babfd6f7fe401c9f2d8238ec3213/src/tools/wat2wasm.cc#L158-L160
