### ISSUE TITLE
wasm2c: Support `table.size`

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#1944]
I have a WASM program written in text format that uses the `table.size` instruction.
When using wat2wasm, and then passing that output to wasm2c, I get the following error:

    error: unexpected opcode: 0xfc 0x10

I'm using WABT 1.0.29 on macOS.

FYI, I also use `table.grow`.

**Comment by sbc100** [comment]
`table.grow` requires reference types, and wasm2c does not yet support reference types.  It looks like it should do soon though: #1887

**Comment by remko** [comment]
That PR indeed makes wasm2c succeed. I'll close this issue, as it'll be fixed when the PR is merged.
