### ISSUE TITLE
How to implement a transformation.

### ISSUE THREAD

**Issue by jameswalmsley** [WebAssembly/wabt#1948]
Hi,

I would like to add a tool to wabt, that can make some simple modifications to the wasm module loaded.
I've tried to iterate through the module and make some some changes, like renaming the functions..

But when I write the binary again, nothing has changed.

Is it possible to do something like this with wabt, are there some examples?

I'm trying to make some tools for a large project.

Thanks 

J

**Comment by keithw** [comment]
Sure, here's the wasm-strip tool, which is quite concise: https://github.com/WebAssembly/wabt/blob/main/src/tools/wasm-strip.cc

And here's an out-of-tree example that links with Wabt and uses ReadBinaryIr to parse it to a wabt::Module, modifies the Module, and then writes the modified Module back to disk: https://github.com/fixpointOS/wasm-tools/blob/main/src/export-audit/export-audit.cc
