### ISSUE TITLE
wasm2c converts signed to unsinged

### ISSUE THREAD

**Issue by dimitry-** [WebAssembly/wabt#1995]
It looks like clang/llvm converts function return types and parameters to signed (s32/s64) and wasm2c treats all numbers as unsinged. (unless there is also bug in wasm2wat which displays numeric types as signed)

Compiling following code:
```
int main() {
  return 1;
}
```
-> wasm2wat
```
(module
  (type (;0;) (func (result i32)))
  (func $__original_main (type 0) (result i32)
    (local i64 i64 i64 i32 i32)
    global.get $__stack_pointer
    local.set 0
    i64.const 16
    local.set 1
    local.get 0
    local.get 1
    i64.sub
    local.set 2
    i32.const 0
    local.set 3
    local.get 2
    local.get 3
    i32.store offset=12
    i32.const 1
    local.set 4
    local.get 4
    return)
  (table (;0;) 1 1 funcref)
  (memory (;0;) i64 2)
  (global $__stack_pointer (mut i64) (i64.const 66560))
  (export "memory" (memory 0)))
```

-> wasm2c produces following signature for main:
```
static u32 w2c___original_main(void) {
```

-> if I change `int` to `unsigned int` in original code
```
(module
  (type (;0;) (func (result i32)))
  (func $main1__ (type 0) (result i32)
    (local i32)
    i32.const 1
    local.set 0
    local.get 0
    return)
```

-> wasm2c
```
static u32 w2c_main1__(void) {
```

**Comment by keithw** [comment]
Hi -- I think everything here is working as intended. Similar to x86-64 and probably other machine code-ish representations, Wasm doesn't have a distinction between signed and unsigned _variables_ -- the signedness comes from the operations that act on them. (See https://webassembly.github.io/spec/core/syntax/types.html)

Here's an example that might be helpful. E.g. if you write this in C:
```c
#include <stdbool.h>

bool greater_signed(int x, int y) { return x > y; }

bool greater_unsigned(unsigned x, unsigned y) { return x > y; }
```
and then compile it like this:
```sh
$ clang -Os -c -o signtest.o signtest.c
```
you'll get this:
```wat
$ wasm2wat -f --generate-names signtest.o 
(module
  (type $t0 (func (param i32 i32) (result i32)))
  (import "env" "__linear_memory" (memory $env.__linear_memory 0))
  (func $greater_signed (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    (i32.gt_s
      (local.get $p0)
      (local.get $p1)))
  (func $greater_unsigned (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    (i32.gt_u
      (local.get $p0)
      (local.get $p1))))
```
Note the difference between the "i32.gt_s" and the "i32.gt_u" -- this is the only place that the signedness of the parameters is manifest. The parameters themselves aren't signed or unsigned in either function; they're just "i32" in both cases. The "bool" return value is also represented as an "i32"!

If you then run wasm2c on this code, it ends up as:
```c
$ wasm2c -o signtest-mod.c signtest.o
$ less signtest-mod.c
[...]
static u32 w2c_greater_signed(u32 w2c_p0, u32 w2c_p1) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  w2c_i0 = w2c_p0;
  w2c_i1 = w2c_p1;
  w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
  FUNC_EPILOGUE;
  return w2c_i0;
}

static u32 w2c_greater_unsigned(u32 w2c_p0, u32 w2c_p1) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  w2c_i0 = w2c_p0;
  w2c_i1 = w2c_p1;
  w2c_i0 = w2c_i0 > w2c_i1;
  FUNC_EPILOGUE;
  return w2c_i0;
}
```

So I think everything is functioning as intended, and I'm not sure wasm2c has much flexibility here to do anything different, but I agree it's not necessarily obvious!
