### ISSUE TITLE
Tag 1.0.30?

### ISSUE THREAD

**Issue by alexreinking** [WebAssembly/wabt#2007]
Now that the header layout change has landed, we (Halide) would like to have a version number to point to. I think this requires just a one-line change for the version number in the CMakeLists.txt file and then a Github release. 

Are there any blockers I'm not aware of?

**Comment by sbc100** [comment]
No, please go ahead and send a PR for 1.0.30 if you have time.

**Comment by Horcrux7** [comment]
The binaries are missing in version 1.0.30.

**Comment by steven-johnson** [comment]
Hmm... I went throught the usual "Create Release" flow; my understanding was that an Action was supposed to auto-populate the Release with the binaries. Apparently that didn't happen?

**Comment by sbc100** [comment]
Let me see if I have any more luck.  I'll try re-creating it.

**Comment by sbc100** [comment]
Looks like to worked when I did.. no idea why

**Comment by alexreinking** [comment]
> Looks like to worked when I did.. no idea why

@sbc100 - GitHub can be funny about permissions, sometimes. I was pulling my hair out not too long ago trying to figure out why it would let me upload a Docker image from my local computer, but _not_ from a GHA workflow.
