### ISSUE TITLE
wabt 1.0.30 build issue

### ISSUE THREAD

**Issue by chenrui333** [WebAssembly/wabt#2016]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
  /tmp/wabt-20221003-91990-ggldl9/src/interp/interp-wasi.cc:647:10: fatal error: 'wasi_api.def' file not found
  #include "wasi_api.def"
           ^~~~~~~~~~~~~~
  1 error generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/3178360168/jobs/5179823985
relates to Homebrew/homebrew-core#112291

**Comment by sbc100** [comment]
Oh, its looks like we are not testing with `-DWITH_WASI=ON`.   I'm working on a fix now.   In the mean you could remove that cmake flag?  (Do you actually need/use it?)
