### ISSUE TITLE
Incorrect arguments for `memory.copy` between memories of different types

### ISSUE THREAD

**Issue by adambratschikaye** [WebAssembly/wabt#2025]
When both the multi-memory and memory64 features are enabled it's possible for memory.copy to copy between two memories of different types. In this case, the memory64 proposal specifies that the src and dst arguments should correspond to the types of the memory they are accessing, and the size argument should correspond to the "minimum" of the two memory types [1]. That is, the size should be an i32 if either of the memories has type i32 and it should be i64 if both of the memories have type i64.

This existing code just expects all three arguments to match the type of the source memory which works whenever the source and destination memories have the same type, but doesn't match the `memory64` proposal when the two memories have different types.

This also conflicts with the current implementation of `wasmtime`. This example `wat`:
```
;; test.wat
(module
  (memory $mem32 i32 1)
  (memory $mem64 i64 1)
  (func
    i32.const 1
    i64.const 0
    i32.const 0
    memory.copy $mem32 $mem64
  )
)
```
compiles fine with `wasmtime`:
```
wasmtime compile --wasm-features all test.wat
```
but fails to be converted with `wat2wasm`:
```
wat2wasm --enable-all test.wat
test.wat:8:5: error: type mismatch in memory.copy, expected [i64, i64, i64] but got [i32, i64, i32]
    memory.copy $mem32 $mem64
    ^^^^^^^^^^^
```

These use commit `4867813f7717653cd6317f11a9df6966653d450c` of `wasmtime` and commit `eca3519d738bcd245d46915e9c373c6d58f5b20b` of `wabt`.

[1]
https://github.com/WebAssembly/memory64/blob/5bfb70d9888b96a2f3d6412ed3599b91364da610/proposals/memory64/Overview.md?plain=1#L211

**Comment by keithw** [comment]
Fixed in #2024
