### ISSUE TITLE
Stack validation error

### ISSUE THREAD

**Issue by zherczeg** [WebAssembly/wabt#2026]
```
(module
  (func (local i32)
  block
    i32.const 3
    if (result i32)
      i32.const 4
    else
      i32.const 3
      if (result i32)
        i32.const 4
      else
        local.get 0
      end

      local.set 0
      ;; This instruction pushes an i32 which is never used
      ;; Code should be invalid.
      i32.const 5
      br 1
    end

    local.set 0
  end
))
```

This code should be a validation error, since the `i32.const 5` pushes a value which is never consumed.

**Comment by keithw** [comment]
Hmm, I think WABT is correct here. It also agrees with the reference interpreter. The `br` is stack-polymorphic and consumes the intermediate stack values (see https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-br-l). Here's a simple example that both WABT and the reference interpreter think is valid:
```wat
(module
 (func (i32.const 5)
       (br 0)))
```

**Comment by zherczeg** [comment]
Thank you for the explanation.
