### ISSUE TITLE
Dead code stack validation error

### ISSUE THREAD

**Issue by zherczeg** [WebAssembly/wabt#2027]
```
(module
  (func
    block
      br 0
      ;; Dead code, but still seems a validation error.
      drop
    end
))
```

The `drop` instruction should expect something on the stack.

**Comment by keithw** [comment]
I think WABT is also correct here (and the reference interpreter agrees). The `br` instruction is stack-polymorphic and everything after it is unreachable, so it can basically treated as leaving as many values as needed on the stack (of the right types) to satisfy the rest of the instruction sequence. See https://webassembly.github.io/spec/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-br-l

**Comment by zherczeg** [comment]
Thank you for the explanation.
