### ISSUE TITLE
Spec JSON new format question

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/wabt#203]
I see the new spec json format is more oriented toward running in wasminterp.
I was wondering if there is anything left to help running in a javascript host ?
I ask mainly for int64 where the only solution I can think of is to generate a module on the fly with the int64 hardcoded value that will import the function I want to test and do a compare.

**Comment by binji** [comment]
Ah, I assumed you had switched to using the spec repo for this.

I think it shouldn't be too hard to modify `spec-json-to-js.py` to do some simple modifications so this can do what it did before and bundle the assertion function into the module as an export. I'll take a look.

**Comment by Cellule** [comment]
We are about to change to use the spec repo. I was just wondering if wabt provided something to that effect.
I ended adding a test hook in chakra that can pass a string representing an int64 and call the Wasm function with it.
It proves to be useful for our internal tests as well.

**Comment by binji** [comment]
FYI: this is fixed in #229.
