### ISSUE TITLE
Assertion fails roundtripping reading/writing file

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#2050]
I have the following program that reads a WASM module and immediately tries to write it again:

      wabt::Errors errors;
      wabt::Features features;
      wabt::Module mod;
      auto result = ReadBinaryIr("in.wasm", in_data, sizeof(in_data), wabt::ReadBinaryOptions(features, NULL, true, true, true), &errors, &mod);
      assert(Succeeded(result));
      result = ValidateModule(&mod, &errors, wabt::ValidateOptions(features));
      result |= GenerateNames(&mod);
      assert(Succeeded(result));
      result = ApplyNames(&mod);
      assert(Succeeded(result));

      wabt::FileStream out("out.wasm");
      result = wabt::WriteBinaryModule(&out, &mod, wabt::WriteBinaryOptions(features, false, false, true));
      assert(Succeeded(result));

`in_data` is a byte array with a WebAssembly module generated using `wat2wasm`.

When I compile this program against the Git version of WABT, and I run this program, I get the following output:

    Assertion failed: (is_index()), function index, file ir.h, line 58.

Here is the backtrace

    * frame #4: 0x000000010000ccbc reproducer`wabt::Var::index() const + 68
      frame #5: 0x00000001000962a0 reproducer`wabt::(anonymous namespace)::BinaryWriter::GetLabelVarDepth(wabt::Var const*) + 28
      frame #6: 0x0000000100093dc8 reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExpr(wabt::Func const*, wabt::Expr const*) + 728
      frame #7: 0x0000000100093994 reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExprList(wabt::Func const*, wabt::intrusive_list<wabt::Expr> const&) + 140
      frame #8: 0x0000000100094788 reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExpr(wabt::Func const*, wabt::Expr const*) + 3224
      frame #9: 0x0000000100093994 reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExprList(wabt::Func const*, wabt::intrusive_list<wabt::Expr> const&) + 140
      frame #10: 0x0000000100093cec reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExpr(wabt::Func const*, wabt::Expr const*) + 508
      frame #11: 0x0000000100093994 reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteExprList(wabt::Func const*, wabt::intrusive_list<wabt::Expr> const&) + 140
      frame #12: 0x000000010008b47c reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteFunc(wabt::Func const*) + 64
      frame #13: 0x000000010008780c reproducer`wabt::(anonymous namespace)::BinaryWriter::WriteModule() + 5444
      frame #14: 0x0000000100086260 reproducer`wabt::WriteBinaryModule(wabt::Stream*, wabt::Module const*, wabt::WriteBinaryOptions const&) + 60
      frame #15: 0x0000000100002738 reproducer`main(argc=1, argv=0x000000016fdff118) at reproducer.cpp:29:12

Do you have any clue what could be going wrong? Is there anything I can do to get to the bottom of what's going on? 

Note that I also run the same module through `WriteC`, and this seems to work fine.

**Comment by keithw** [comment]
I don't know how well this is documented, but if you want to roundtrip a module like this through the BinaryWriter, I think either you'll want to (1) completely skip the calls to GenerateNames and ApplyNames or (2) if you do want to ApplyNames, then you'll also need to ResolveNamesModule to match up the referents with the referees.

Both of these approaches seem to fix the problem. Otherwise I believe what happens is that you end up with numeric referents (e.g. a function call or throw) that can't be matched to their named referees.
