### ISSUE TITLE
Tag 1.0.31?

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#2059]
I'm interested in a new WABT build that includes the wasm2c reftypes and the CWriter in libwabt. 
It's not super-urgent, but just so you know at least 1 person is waiting for a new tag ;)

**Comment by keithw** [comment]
Done in #2060.

**Comment by keithw** [comment]
Whoops, jumped the gun. I guess it hasn't been tagged yet.

**Comment by sbc100** [comment]
I just made the release+tag
