### ISSUE TITLE
interp: Value conditional struct field not present in release build

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#2069]
I'm trying to track down an issue with a modified version of `wasm-interp.cc` I'm using. It's not clear whether it's a bug on my end, or a bug in interp, so I hope someone can point me to what's going wrong. I tried to strip down the interpreter to the minimal reproducing program.

I have the following WebAssembly program:

```wasm
(import "shell" "read" (func $shell_read (param i32 i32)))
(func $run (export "run")  
  (call $shell_read (i32.const 0x8) (i32.const 0x9)))
 ```

I try to run this using the following interpreter:

```c++
namespace wabti = wabt::interp;

wabt::Result run() {
  static wabti::Store store;
  static wabt::Features features;
  static wabt::Errors errors;
  wabti::ModuleDesc desc;
  CHECK_RESULT(wabti::ReadBinaryInterp("input.wasm", input, sizeof(input), 
        wabt::ReadBinaryOptions(features, nullptr, true, true, true), &errors, &desc));
  auto core = wabti::Module::New(store, desc);

  // Bind import
  wabti::RefVec imports;
  auto import = core->desc().imports[0];
  auto ft = *wabt::cast<wabti::FuncType>(import.type.type.get());
  auto func = wabti::HostFunc::New(store, ft,
    [](wabti::Thread &, const wabti::Values &params, wabti::Values &, wabti::Trap::Ptr*) -> wabt::Result {
      std::cout << "cb " << params.size() << " " << params[0].type << std::endl;
      return wabt::Result::Ok;
  });
  imports.push_back(func.ref());

  // Instantiate module
  wabti::Trap::Ptr trap;
  auto corei = wabti::Instance::Instantiate(store, core.ref(), imports, &trap);
  assert(corei);

  // Run
  wabti::Values runParams;
  wabti::Values runResults;
  return store.UnsafeGet<wabti::Func>(corei->funcs()[1])->Call(store, runParams, runResults, &trap, nullptr);
}

int main(int argc, char *argv[]) {
  run();
}
```

When I run this against a Debug build of libwabt, the program works fine, and this is the output:

    cb 2 -1

However, when I run this against a Release build of libwabt, this is what I get:

    cb 1 9

It seems that at least the params parameter is wrong (wrong length, and wrong contents).

I tried running an asan build. In my real program, I get asan errors during module instantiation, but in the minimal program above, I don't get anything.

**Comment by remko** [comment]
I found the problem: in `interp.h`, the `Value` struct has a field that is not present when compiled with `NDEBUG`. The release build of wabt defines this macro, but my application doesn't.

This sounds like a bug in `interp.h`: if there is a field that is conditional, the condition should be specified in `config.h`. I.e. there should be a `#define WABT_DEBUG 0` or something in `config.h`.

**Comment by sbc100** [comment]
Yup that sounds like a bug!  A PR would be most welcome.
