### ISSUE TITLE
wast2json fails on test/core/select.wast 

### ISSUE THREAD

**Issue by devoncarew** [WebAssembly/wabt#2125]
When I run `wast2json` on the `test/core/select.wast` test from https://github.com/WebAssembly/spec, I see the following failure:

```
wast2json test/core/select.wast

test/core/select.wast:526:55: error: unexpected token "result", expected an instr.
  (func (result i32) unreachable select (result i32) (result))
                                                      ^^^^^^
test/core/select.wast:527:55: error: unexpected token "result", expected an instr.
  (func (result i32) unreachable select (result i32) (result) select)
                                                      ^^^^^^
test/core/select.wast:528:51: error: unexpected token "result", expected an instr.
...nc (result i32) unreachable select (result) (result i32) select (result i32))
```

**Comment by sbc100** [comment]
What version of wabt are you using?  It looks like maybe this issue was fixed 3 weeks ago in #2104?

**Comment by devoncarew** [comment]
Thanks for the response! It may be a version issue; I don't see the crash on one machine (w/ wast2json --version `1.0.32`), but see it on my home machine. I'll verify the version there later today.

**Comment by devoncarew** [comment]
Yup - my personal machine was using `1.0.31`. After upgrading the version to `1.0.32` I no longer see the issue.
