### ISSUE TITLE
wasm2c/spec/float_exprs.txt fails with GCC 13.0.0

### ISSUE THREAD

**Issue by rathann** [WebAssembly/wabt#2130]
Building wabt 1.0.32 and running testsuite with gcc 13.0.0 on Fedora rawhide (development branch) yields one new test failure, on x86_64, aarch64 and ppc64le (I haven't tested on s390x or i686 yet):
```
- test/wasm2c/spec/float_exprs.txt
  expected error code 0, got 1.
  STDERR MISMATCH:
  --- expected
  +++ actual
  @@ -0,0 +1,18 @@
  +Traceback (most recent call last):
  +  File "/builddir/build/BUILD/wabt-1.0.32/test/run-spec-wasm2c.py", line 569, in <module>
  +    sys.exit(main(sys.argv[1:]))
  +             ^^^^^^^^^^^^^^^^^^
  +  File "/builddir/build/BUILD/wabt-1.0.32/test/run-spec-wasm2c.py", line 563, in main
  +    utils.Executable(main_exe, forward_stdout=True).RunWithArgs()
  +  File "/builddir/build/BUILD/wabt-1.0.32/test/utils.py", line 96, in RunWithArgs
  +    raise error
  +utils.Error: Error running "out/test/wasm2c/spec/float_exprs/float_exprs" (1):
  +None
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3083: assertion failed: in Z_float_exprs_86_wasmZ_f32Z2Eno_trichotomy_lt(&Z_float_exprs_86_wasm_instance, 0.f, make_nan_f32(0x400000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3086: assertion failed: in Z_float_exprs_86_wasmZ_f32Z2Eno_trichotomy_le(&Z_float_exprs_86_wasm_instance, 0.f, make_nan_f32(0x400000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3089: assertion failed: in Z_float_exprs_86_wasmZ_f32Z2Eno_trichotomy_gt(&Z_float_exprs_86_wasm_instance, 0.f, make_nan_f32(0x400000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3092: assertion failed: in Z_float_exprs_86_wasmZ_f32Z2Eno_trichotomy_ge(&Z_float_exprs_86_wasm_instance, 0.f, make_nan_f32(0x400000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3095: assertion failed: in Z_float_exprs_86_wasmZ_f64Z2Eno_trichotomy_lt(&Z_float_exprs_86_wasm_instance, 0.0000000000000000L, make_nan_f64(0x8000000000000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3098: assertion failed: in Z_float_exprs_86_wasmZ_f64Z2Eno_trichotomy_le(&Z_float_exprs_86_wasm_instance, 0.0000000000000000L, make_nan_f64(0x8000000000000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3101: assertion failed: in Z_float_exprs_86_wasmZ_f64Z2Eno_trichotomy_gt(&Z_float_exprs_86_wasm_instance, 0.0000000000000000L, make_nan_f64(0x8000000000000)): expected 0, got 1.
  +out/test/wasm2c/spec/float_exprs/float_exprs-main.c:3104: assertion failed: in Z_float_exprs_86_wasmZ_f64Z2Eno_trichotomy_ge(&Z_float_exprs_86_wasm_instance, 0.0000000000000000L, make_nan_f64(0x8000000000000)): expected 0, got 1.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1 +1 @@
  -794/794 tests passed.
  +786/794 tests passed.
```

Full dependency chain changes and build logs at [Fedora continuous rebuild service](https://koschei.fedoraproject.org/package/wabt?collection=f38)

**Comment by keithw** [comment]
Thanks as always for these early reports. Are you able to find a combination of compiler flags (I guess in addition to the `-frounding-math -fsignaling-nans` we already need -- I wonder if GCC 13 adds any new options) that makes GCC pass this test?

It looks like the NaN is comparing either `>=` or `<` to zero...

**Comment by rathann** [comment]
@keithw You're welcome! I looked at https://gcc.gnu.org/gcc-13/changes.html and https://gcc.gnu.org/gcc-13/porting_to.html but I don't see anything new related to floats.

**Comment by keithw** [comment]
Well, thanks, and... sigh. I think investigation of this issue will require looking at the output and maybe reducing the test case to figure out what's happening. (Does the problem still happen if you turn off '-O2' in run-spec-wasm2c.py ? Does GCC think NaN is < 0? Or >= 0? Or is it only when checking both that it fails? Is there a GIMPLE intermediate form we can look at? I guess, can we bisect gcc to find the commit between 12 and 13 where this started breaking?)

If you feel up to this, please go for it, and either way I guess we should leave this issue open for whoever gets to it first.

**Comment by keithw** [comment]
FWIW I just tested this on current gcc tip-of-tree (now that GCC 13.1 has been released) and I can't replicate the failure on x86-64. Are you still seeing this? (I do see that there's a memory_init test where GCC is smart enough to detect a trap at compile time -- we're probably going to have to use `-Wno-error=array-bounds` if we want to keep the runtime trap that the testsuite requires.)

**Comment by keithw** [comment]
The Fedora build link suggests the problem may have gone away with the upgrade from gcc-c++ 13.0.1-0.1.fc38.1 to 13.0.1-0.2.fc38, so, closing as apparently solved by fate (but thank you for reporting these!).
