### ISSUE TITLE
wasmdump doesn't seem to dump Names section

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#214]
I was investigating some breakage from https://github.com/WebAssembly/binaryen/pull/831 (v8 isn't up to date with the Names section changes) and found that wasmdump doesn't print the header for the names section when it's present. Looking at the code, it looks like the intention is that it should, and it's not immediately obvious to me why.

**Comment by dschuff** [comment]
#216 looks like it should fixe the bug. I still also think that `wasmdump -h` should show the section headers for all of the sections, including known unknowns (names) and and unknown unknowns; it can just show the section name and size, if nothing else. Also the `--debug-names` flag doesn't show up in `wasmdump --help`

**Comment by binji** [comment]
Reopening for these additional issues. @sbc100

**Comment by sbc100** [comment]
wasmdump does show the headers for the names section, and --debug-names is not an option to wasmdump but to the wast2wasm tool.   I'll make a PR to actually tests the -h flag.
