### ISSUE TITLE
Make wasm2c more readable

### ISSUE THREAD

**Issue by xzwDavid** [WebAssembly/wabt#2141]
Hi~

After reading src code of wasm2c, I found that wasm2c mainly uses enumeration to match and generate C code.And this makes the generated C code look similar to wat.

eg. if I want generated c code like this:

```
if (*hex == '#') {
    hex++;
}   
```

for now, it would generated like this:
```static void _colorFromHexString(u32 p0, u32 p1) {
  u32 l0 = 0, l1 = 0, l2 = 0, l3 = 0;
  FUNC_PROLOGUE;
  u32 i0, i1, i2, i3;
  f32 f1;
  f64 d1, d2;
  i0 = p0;
  i1 = 1u;
  i0 += i1;
  l0 = i0;
  i0 = p0;
  i0 = i32_load8_s(Z_envZ_memory, (u64)(i0));
  i1 = 35u;
  i0 = i0 != i1;
  if (i0) {
    i0 = p0;
    l0 = i0;
  }
```

corresponding to wat:
```(func (;7;) (type 3) (param i32 i32)
  (local i32 i32 i32 i32)
  get_local 0
  i32.const 1
  i32.add
  set_local 2
  get_local 0
  i32.load8_s
  i32.const 35
  i32.ne
  if  ;; label = @1
    get_local 0
    set_local 2
  end
```
Is it possible that we use some method like regular expression to make it easier?
like:
```i0 = i32_load8_s(Z_envZ_memory, (u64)(hex));
if (i0 != 35u) {
    l0 = hex + 1u;
}
```
Does it sound feasible?

**Comment by keithw** [comment]
I think your best bet is probably to use the wasm-decompile tool in WABT, which generates output pretty close to what you were hoping for. If I put that module in a file and then assemble and decompile it, here's what I get:

```wat
$ cat /tmp/example.wat
(memory 1)
(func
  (local i32 i32 i32 i32)
  local.get 0
  i32.const 1
  i32.add
  local.set 2
  local.get 0
  i32.load8_s
  i32.const 35
  i32.ne
  if  ;; label = @1
    local.get 0
    local.set 2
  end
)
```

```c
$ wat2wasm /tmp/example.wat --output=- | wasm-decompile -
memory M_a(initial: 1, max: 0);

function f_a() {
  var a:byte_ptr;
  var c:int = a + 1;
  if (a[0] != 35) { c = a }
}
```

Does this do the trick for you?

(By the way, it looks like you may be using a _really_ old version of WABT/wasm2c -- since mid-2020, wasm2c has used variable names that look like `w2c_i0` instead of just `i0`, and in the WAT, instruction names like "get_local" were only in draft versions of the specification before getting renamed in 2018 to "local.get". WABT hasn't accepted the old instruction names since late 2021.)

**Comment by xzwDavid** [comment]
Thanks for your reply!

"wasm-decompile" does make wasm code look explicit, but I wonder whether there is tool like wasm-decompile to generate readable C code.

Namely, assuming that we want example.c, we need use "wat2wasm" and "wasm2c" then generate code like this:
```C
static void w2c_f0(Z_example_instance_t* instance) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  w2c_i0 = w2c_l0;
  w2c_i1 = 1u;
  w2c_i0 += w2c_i1;
  w2c_l2 = w2c_i0;
  w2c_i0 = w2c_l0;
  w2c_i0 = i32_load8_s(&instance->w2c_M0, (u64)(w2c_i0));
  w2c_i1 = 35u;
  w2c_i0 = w2c_i0 != w2c_i1;
  if (w2c_i0) {
    w2c_i0 = w2c_l0;
    w2c_l2 = w2c_i0;
  }
  FUNC_EPILOGUE;
}
```
Is it worth a try to add some tools (like "wasm2c example.wasm -o | wasm2c-decompile -")to generate C code like this:
```C
static void w2c_f0(Z_example_instance_t* instance){
  int* a=byte_ptr;
  int c= a + 1;
  if (a[0] != 35) { c = a; }
}
```

**Comment by sbc100** [comment]
I think there is tension between wanting to make the output of wasm2c readable and maintaining its simplicity, and 1-to-1 nature with the wasm bytecode.  Can I ask why you want the C code to look more like the original program?   Is it just about readability or do you think the compiler will do a better job on the result?

**Comment by xzwDavid** [comment]
Well, I haven't reach the level knowing exactly how wat2wasm works and have no idea about potential performance. Intuitively, generated C code looking more like assembly style seems to "skip" some step for executing C code, but I am not sure whether it would make compiler do better. I will give some tests for it before I ask again. 


At the same time, I think the tool making C code readable can give people friendly using experience(eg. If we want a native running env, we may need debug with generated C code).   And I think it would be fun to implement it, so I open an issue to check whether this idea is necessary?
