### ISSUE TITLE
wasm-objdump GC proposal

### ISSUE THREAD

**Issue by pannous** [WebAssembly/wabt#2145]
While wasm-objdump can read the Type section according to the GC proposal:
```
Type[2]:
 - type[0] () -> i64
 - type[1] (struct (mut i32) (mut i32) (mut i32))
``` 

It fails reading the Code sections new 0xFB prefix:
`error: 0x64 missing opcode callback at 0x55 (0xfb=<invalid>)`

where `wasm-dis` outputs:
```
(struct.get $1 1
       (struct.new $1
        (i32.const 1)
        (i32.const 2)
        (i32.const 3)
       )
      )
```

**Comment by keithw** [comment]
Thanks... unfortunately wabt just doesn't have full support for the GC proposal (or the typed function references proposal) yet. If you're able to contribute this, we'd love to have it. Please feel free to continue discussion on #1257 or #1874.
