### ISSUE TITLE
Update Names section for 0xd

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#215]
Since 0xd, the names section names anything in the function index space, which includes imports as well as locally-defined functions. Wabt and v8 haven't been updated to handle this yet, but Spidermonkey and Binaryen have.

**Comment by binji** [comment]
This should work, though there was a bug where the names section wouldn't be read if the module contained only imports. Note that you also have to pass `--debug-names` to read this section.

**Comment by binji** [comment]
Ah, and it wouldn't work if there was a "data" section either, since we never looked for unknown sections after the last known section.
