### ISSUE TITLE
wasm-strip removes also names that are being used for Module.ccall

### ISSUE THREAD

**Issue by terop2** [WebAssembly/wabt#2156]
Is there way to tell wasm-strip not to remove the calls that are being called with Module.ccall. Currently it strips everything and then javascript cannot call the wasm functions :-)

**Comment by terop2** [comment]
maybe exported functions shouldn't be stripped?

**Comment by keithw** [comment]
Hmm, I'm confused by this. wasm-strip doesn't modify or remove the names of exports. Are you sure the function you're trying to call is exported under the right name? (Look for an "export" expression in the `wasm2wat` output.)

**Comment by terop2** [comment]
the compiler gives warnings about the symbols I export, but I haven't studied why that happens. But the exports have been working well until I tried wasm-strip... Basically the behaviour is that it just doesn't call the exported function with ccall, no error message or anything.

**Comment by terop2** [comment]
(my 3d engine takes 16 seconds to load ordinary 2d game, and that's too long time, so I'm trying to optimize the 22Mb wasm.br files to be smaller. -Os helped to 16Mb, but strip didn't seem to work...)

**Comment by terop2** [comment]
(oh, you can see it in https://meshpage.org )

**Comment by sbc100** [comment]
If you are using emscripten, I don't see any reason to use wasm-strip.   Passing `-Oz` to emscripten will already do all the stripping for you.   I don't know of any benefit to then calling wasm-strip.   When you build with emscripten it uses binaryen's wasm-opt tools which already does all the stripping possible.

**Comment by terop2** [comment]
Thanks for this information, it helped tremendously. I got my previously 22Mb wasm.br file to 13Mb wasm.br file with -Oz option and there's now no need for wasm-string at all.

**Comment by sbc100** [comment]
I think we can close this, unless you want to keep debugging to find out precisely what it is that wasm-strip is doing that you think it shouldn't be.

**Comment by terop2** [comment]
yes, can close this.
