### ISSUE TITLE
Lexer: Refactor Result and make functions more pure

### ISSUE THREAD

**Issue by Yongbeom-Kim** [WebAssembly/wabt#2159]
Some functions return a `Result` enum - and because the return value is taken up by the `Result` value, these functions also pass in a pointer to write the intended 'output' into - a good example are the `Parse*` functions in [`literal.cc`](https://github.com/WebAssembly/wabt/blob/main/src/literal.cc).

Personally, I find that this is needlessly confusing given Rust's [Result enums](https://doc.rust-lang.org/std/result/enum.Result.html) - it kinda feels like this is emulating half of Rust's Result counterpart, but not quite, and makes the resulting function calls less readable as well. 

I suggest that the Result struct should also encapsulate return values as well, so [this line]((https://github.com/WebAssembly/wabt/blob/main/src/literal.cc#L283)) in `literal.cc` would go from something like this:
```c++
    } else if (Succeeded(ParseHexdigit(*s, &digit))) {
```
to something like this:
```c++
    } else if (auto result = ParseHexdigit(*s); Succeeded(result)) {
digit = result.get()
```

I don't think this should yield any runtime costs either, since the copy operation should be elided - wondering if you will be open to a pr on this

**Comment by sbc100** [comment]
Is that second form actually more readable to you?  To me a looks more complicated, and at least it involves more typing and reading.

Maybe there is some template magic that can be done to avoid that?

**Comment by Yongbeom-Kim** [comment]
Hmm, actually I do see that the first is a little cleaner in the end - I suppose I'm having mixed feelings about the receiver pointer on top of the result object and my suggestion to the result object is analogous to std::[expected](https://en.cppreference.com/w/cpp/utility/expected) or [optional](https://en.cppreference.com/w/cpp/utility/optional)

I can imagine something like this:
```c++
    } else if (auto result = ParseHexdigit(*s)) {
```

or to be more verbose,
```c++
    } else if (Succeeded(auto result = ParseHexdigit(*s))) {
```

and then to fetch the value would just be `*result`

My thought is that it would make the flow of data a little clearer - what do you think?

**Comment by sbc100** [comment]
I don't feel particularly strongly about it either way.    Perhaps that's because I'm used to dealing with old school C, so having out pointers seems fairly normal/natural to me.  

If you feel more strongly, and if there is a way to make it work without adding to too much code/complexity please feel free to send a PR.
