### ISSUE TITLE
need a cmake option turn off build libwabt.a ( libwasm-rt-impl.a only)

### ISSUE THREAD

**Issue by calvin2021y** [WebAssembly/wabt#2174]
I want build `libwasm-rt-impl.a` without `libwabt.a` for cross build.  (libwabt.a not needed)

try build with `-DBUILD_TESTS=OFF -DWITH_WASI=OFF -DBUILD_TOOLS=OFF -DBUILD_LIBWASM=OFF `,  can not turn it off.

**Comment by keithw** [comment]
There is a named target that just builds libwasm-rt-impl.a -- please try this:

```
$ cmake -S. -B build
[...]
$ cmake --build build --target wasm-rt-impl
[100%] Building C object CMakeFiles/wasm-rt-impl.dir/wasm2c/wasm-rt-impl.c.o
[100%] Linking C static library libwasm-rt-impl.a
[100%] Built target wasm-rt-impl
$
```
