### ISSUE TITLE
wasm2c docs expired,  build with linker error

### ISSUE THREAD

**Issue by calvin2021y** [WebAssembly/wabt#2175]
```c
/* Construct the module instance. */
  wasm2c_fac_instantiate(&fac);
````

this api changed,   use `wasm2c_fac_instantiate(&db2, NULL, NULL);` get this linker error:

```sh
lld: error: undefined symbol: _w2c_env_0x5F_main_argc_argv
>>> referenced by sqlite.c:327248 (test.c:327248)
>>>               db2.o:(symbol _w2c_db2_0x5F_main_void+0x2b5)

lld: error: undefined symbol: _w2c_wasi__snapshot__preview1_proc_exit
>>> referenced by sqlite.c:327315 (sqlite.c:327315)
>>>               db2.o:(symbol _w2c_db2_0x5F_wasi_proc_exit+0x4f)

lld: error: undefined symbol: _w2c_wasi__snapshot__preview1_args_sizes_get
>>> referenced by sqlite.c:327304 (sqlite.c:327304)
>>>               db2.o:(symbol _w2c_db2_0x5F_wasi_args_sizes_get+0x5b)

lld: error: undefined symbol: _w2c_wasi__snapshot__preview1_args_get
>>> referenced by sqlite.c:327292 (sqlite.c:327292)
>>>               db2.o:(symbol _w2c_db2_0x5F_wasi_args_get+0x5b)
```

**Comment by calvin2021y** [comment]
change entry into `__main_void`, get this error:

```sh
lld: error: undefined symbol: _w2c_wasi__snapshot__preview1_proc_exit
>>> referenced by sqlite.c:323116 (sqlite.c:323116)
```

**Comment by sbc100** [comment]
Those symbols are needed by the wasm binary you are compiling.  You need provide definitions for them.

In particular those look like WASI syscalls that are used in wasi-libc (and programs build with wasi-libc).   
wasm2c doesn't (yet) provide any implementations of any syscalls so its currently up to you to define those in your program.

**Comment by calvin2021y** [comment]
Thanks for explain.

I use a empt main function inside wasm code. (no run any code inside main), and build with master branch.

then build for host with `-fno-optimize-sibling-calls -frounding-math` and clang.

```c
#include <stdio.h>
#include <stdlib.h>
#include "sqlite.h"

int main(int argc, char** argv) {

  /* Initialize the Wasm runtime. */
  wasm_rt_init();

  /* Declare an instance of the `fac` module. */
  w2c_db2 db2;
  struct w2c_wasi__snapshot__preview1* preview_ptr;

  /* Construct the module instance. */
  wasm2c_db2_instantiate(&db2, NULL);

  /* Free the fac module. */
  wasm2c_db2_free(&db2);

  /* Free the Wasm runtime state. */
  wasm_rt_free();

  return 0;
}

void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1* p, u32 i){
	
}
``

If I build with `lto`,  the app blocked after start.   (without lto app start and quit in less 1 sec)

**Comment by sbc100** [comment]
Regarding the documention, are you referring it https://github.com/WebAssembly/wabt/tree/main/wasm2c?

It looks correct to me.  The current/correct signature for `wasm2c_fac_instantiate` is `void wasm2c_fac_instantiate(w2c_fac*);` and least when using the latest build of wasm2c that is what it outputs.  What version are you using?

**Comment by sbc100** [comment]
If you build your wasm file such that it imports functions than the host can/must provide them. 

If you are using wasi-sdk to build your wasm file then you can call a host function simply by declaring it and calling it like any normal C extern function.

At link time you will need to use `--allow-undefined=foo` or you can take you function `__attribute__((import_name("foo")))` in the source code.

When you convert such a program using wasm2c you will get a new undefined symbol called something like `w2c__evn_foo`

**Comment by keithw** [comment]
> I need to be able call host function inside wasm. (host provide the sqlite VFS IO data), is there a example or documents for this?

You might like the `rot13` example for this (https://github.com/WebAssembly/wabt/tree/main/wasm2c/examples/rot13).

**Comment by calvin2021y** [comment]
I try this find can not use `--allow-undefined=foo` set for symbol name. (allow all undefined,  to limit names need `--allow-undefined-file=file_path`)

I test the host function and it work, with extra arguments `w2c_env`. I just test pass int here.  is this support pass memory block or pointer ?

**Comment by calvin2021y** [comment]
work fine,  close this.

the build file size is huge compare to native build.
