### ISSUE TITLE
Compliance with 6.5.10

### ISSUE THREAD

**Issue by cognivore** [WebAssembly/wabt#2186]
Consider this snippet

```
(module
    (func $f (param $y f32) (param $y1 f32) (result f32) (result f32) (result f32)
        (local $y2 f32)
        (local.set $y2 (f32.const 11.0))
        (f32.sub (f32.const -1.0) local.get $y) ;; A
        (f32.sub local.get $y local.get $y1 local.get $y2) ;; B
    )
    (func (export "main") (result f32) (result f32) (result f32)
        (call $f (f32.const 2.0) (f32.const 10.0))
    )
)
```

Per specification,

![image](https://user-images.githubusercontent.com/66186054/228824269-64a1625b-d59a-4aa3-b394-7e7f76a3b1c4.png)

Seemingly, both (;A;) and (;B;) don't comply with the grammar. However, 

# Observed behaviour

The code is processed with wabt.

# Expected behaviour

When ran with wabt, a parse error is raised on line 5 saying that "(" was expected, but "local.get" found.

**Comment by keithw** [comment]
I'm having trouble replicating this. Both `wat2wasm` and the reference interpreter seem to correctly reject this module.

With the reference interpreter (current main branch):
```
$ cat /tmp/badmod.wat 
(module
    (func $f (param $y f32) (param $y1 f32) (result f32) (result f32) (result f32)
        (local $y2 f32)
        (local.set $y2 (f32.const 11.0))
        (f32.sub (f32.const -1.0) local.get $y) ;; A
        (f32.sub local.get $y local.get $y1 local.get $y2) ;; B
    )
    (func (export "main") (result f32) (result f32) (result f32)
        (call $f (f32.const 2.0) (f32.const 10.0))
    )
)
$ ./wasm /tmp/badmod.wat 
/tmp/badmod.wat:5.35-5.44: syntax error: unexpected token
```

With `wat2wasm` (current main branch):
```
$ ./bin/wat2wasm -o /tmp/badmod.wasm /tmp/badmod.wat
/tmp/badmod.wat:5:35: error: unexpected token local.get, expected ).
        (f32.sub (f32.const -1.0) local.get $y) ;; A
                                  ^^^^^^^^^
/tmp/badmod.wat:6:18: error: unexpected token local.get, expected ).
        (f32.sub local.get $y local.get $y1 local.get $y2) ;; B
                 ^^^^^^^^^
/tmp/badmod.wat:8:5: error: unexpected token (, expected EOF.
    (func (export "main") (result f32) (result f32) (result f32)
    ^
```

Can you give a little more detail on where/how you see WABT parsing this incorrectly?

**Comment by keithw** [comment]
:-) We've all been there. Hope you will find WABT useful in your future WebAssembly needs! If you really want the true reference implementation, https://github.com/WebAssembly/spec/tree/main/interpreter is it.
