### ISSUE TITLE
Ubuntu 22.04 doesn't have CMake 3.16

### ISSUE THREAD

**Issue by penzn** [WebAssembly/wabt#2187]
I don't know to what degree that matters, but #1968 disabled building on latest LTS Ubuntu (22.04), which only has CMake 3.14 at the moment. Ubuntu tends to lag behind Debian.

**Comment by keithw** [comment]
Hmm, I'm confused by this. #1968 says "Ubuntu Linux 20.04 LTS ships 3.16 and the newest LTS ships 3.22," and that matches what I see online (https://launchpad.net/ubuntu/jammy/+source/cmake).

**Comment by penzn** [comment]
Weird, could be my environment, let me check.

**Comment by penzn** [comment]
I got a rogue CMake version installed somehow, sorry about that.

**Comment by keithw** [comment]
:-)
