### ISSUE TITLE
wasm2c runtime: add per-thread init/free, and make wasm_rt_init/free return and take a `void*`?

### ISSUE THREAD

**Issue by keithw** [WebAssembly/wabt#2189]
Trying to get #2046 closed off (use of globals preventing the wasm2c runtime from being thread-safe).

It looks like the only remaining blocker is the `static char* g_alt_stack` variable, which currently gets malloc'ed once per process via `wasm_rt_init()` which calls `os_install_signal_handler()`.

The challenge is that: if we want the runtime to be thread-safe, every thread will need a **different** allocated region for the alt stack, so that each thread can (in theory) be handling stack exhaustion by running the SIGSEGV signal handler at the same time. Each thread will have to install its own alt stack separately by calling `sigaltstack()`. (The signal handler itself only has to be installed once per process.)

I think my preferred way to fix this would be:
- we eliminate the global `g_alt_stack` variable
- we add a new API pair that looks like:
   ```c
   void* wasm_rt_thread_init();
   wasm_rt_thread_free(void*);
   ```
   `wasm_rt_thread_init()` is responsible for (a) malloc'ing the altstack (sadly this has to be done at runtime because SIGSTKSZ is only known at runtime), (b) installing it via `sigaltstack()`, and (c) returning it via an opaque `void*` that the caller has to keep around. `wasm_rt_thread_free()` does the reverse (de-installing the altstack **if** it's still the current altstack, and freeing the memory either way)
   
   If the host wants to use wasm2c-generated code across multiple threads, it needs to call `wasm_rt_thread_init()` in each thread before calling in to a wasm2c-generated module.
- we don't require every user to call these functions (especially not in single-threaded code), but we change the signature of `wasm_rt_init()` and `wasm_rt_free()` to be:
    ```c
   void* wasm_rt_init();
   wasm_rt_free(void*);
   ```
   so that they can internally call `wasm_rt_thread_init()` and `wasm_rt_thread_free()` for whatever thread they are run on.

I think I like this design better than the gymnastics of trying to make `g_alt_stack` a thread-local global and worrying about managing it on a per-thread basis (e.g., what happens if the user calls `wasm_rt_thread_init()` on the same thread that they called `wasm_rt_free()` on), but it does increase the burden for the host of having to keep this `void*` around.

@shravanrn @sbc100 Do you have thoughts?

**Comment by shravanrn** [comment]
Yup, this makes sense. This approach is consistent with other sandboxing runtimes like Native Client which provides APIs to create and destroy a thread context explicitly from the host. Personally, I don't have objections to either design (a TLS variable versus an explicit thread state object managed by the host) and so am happy to go with this if you prefer.

**Comment by sbc100** [comment]
So the idea would be that calling any wasm2c function on a thread that hasn't called wasm_rt_thread_init would be undefined behaviour?  

I don't love that fact that we are changing the API or `wasm_rt_init/free` for single-threaded users.

I also don't really see that downside TLS global for this (especially given that we already have  WASM_RT_THREAD_LOCAL).

We would likely need a bunch of asserts in debug build anyway and it would be easy enough to forbid calling wasm_rt_thread_init/wasm_rt_thread_free on the "main" thread.
