### ISSUE TITLE
Docfix: clang issues

### ISSUE THREAD

**Issue by KloudKoder** [WebAssembly/wabt#2200]
I read the instructions in the root README.md file. I chose to do "Building using the top-level Makefile (Linux and macOS)". It complained about the fact that I don't have clang. So I installed it. Then I tried "make" again and it complained about not being able to find "lstdc++" (which I take to mean that the library "stdc++" is missing). "stdc++" is apparently the standard library from GCC (which I do already have installed), even though we're using clang in this context. Based on my forum browsing, stdc++ has to get "borrowed" from GCC because of something to do with GPL license terms. Anyway, I searched for how to install this library, and just turned up a lot of threads with people arguing over how to do it. Nothing seemed to work on my end. (To make matters worse, the "++" sometimes gets confused with a regex expression when you try to install it, and escape characters don't seem to fix the problem. Surely there's a better way but I haven't discovered it.) I had to completely give up and go back to the "cmake" approach. In the interest of saving others the wasted time, maybe just delete the section on building from Makefile, or explain how to resolve this problem on systems that don't have clang preinstalled.

By the way, in the "Running wasm2wat" section, it gives some examples using "test.wat", as though it's a test file that one can compile. There is no such file and the user is left to guess how to create such an example. Probably it's easy but a little more explanation would go a long way.

**Comment by keithw** [comment]
Thanks... I think we'd happily take some proposals if you think we can make this clearer! I'm sorry it sounds like it was frustrating.

You're right that if you just run `make`, it will build "the default version of the tools: a debug build using the Clang compiler" as the README says. You can use basically any C++17 compiler (e.g. GCC or MSVC); there's no need for Clang specifically. As you found, the easiest way may be to use the CMake instructions earlier in the README: it will try to auto-detect your compiler of choice. Or if you want to use `make`, as the README says right after the defaults, you can give it an argument like `make gcc-debug` or `make gcc-release` and it will happily build with GCC.

(Re: installing clang, on most GNU/Linux distributions this is usually something like `sudo apt install clang` or the equivalent, and then if all goes well, it will work out of the box. If you're installing clang from source, it can use either libstdc++ or libc++ as you prefer; I don't think the GPL or other legal issues are directly relevant here.)

**Comment by KloudKoder** [comment]
That was actually much clearer than your README.md, so thank you.

Your GCC syntaxes seemed to work on my end. Definitely those options should be in the docs.

clang was a nightmare that I wish I could have avoided (500 MB of who-knows-what, which now refuses to uninstall). I've anecdotally noticed that most Linux distros seem to ship with GCC as opposed to clang, so dedicated GCC documentation is justifiable.

This should be easy: download source, build it, and follow instructions to get a demo running in a debugger at the command line, like it's 1980 or something. I had to hunt around your folder structure just to find some WAT files, so maybe I can guess how to morph them into something that I actually need to create.

Now, I know it's probably asking too much to have a manual which specs out the proper text format. But please, at least, include a test.wasm and test.wat (which is sort of implied under "Some examples").

**Comment by keithw** [comment]
Re: GCC, I think that's the **intent** of the next sentence in the README ("There are many make targets available for other configurations as well...", and then it lists "gcc" as the first option under "compilers"). Will happily take a PR that makes this gentler or less confusing. FWIW there are also wabt packages in Debian/Ubuntu/Fedora/Arch Linux.

For a manual that describes the text format, https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format is pretty good.

**Comment by KloudKoder** [comment]
I see your point. I think what threw me off was the references to clang under "Building using the top-level Makefile (Linux and macOS)". They imply that clang needs to be present. There are other sections that appear to imply the same, e.g. "Sanitizers". Maybe instead of using clang everywhere as an example, it would be better to refer to "$CC". (It's always desirable to be able to copypaste commands just to get things started. The less we have to think about routine build operations, the better. In this case, that's not straightforward due to the compiler differences, hence my suggestion. But maybe even this wouldn't work due to path differences among compilers, in which case a table of options instead of a single command line for each operation would be clearer.)

Thanks for the text format link. Why not add that to README.md as well?

**Comment by sbc100** [comment]
One of the first lines of the README already links to the WebAssembly text format to the WebAssembly binary format specs.  I'm not sure we need to do more than that.  If folks want to learn about what WebAssembly is there are lots places to do that already.

**Comment by KloudKoder** [comment]
@sbc100 Fair enough, I honestly didn't notice that.

I do still think it would help to break up the command lines according to clang, GCC, etc. 

Ultimately, having a debuggable test file (maybe something even simpler than "Hello World") would go a long way toward getting people off to a constructive start. As it stands, I basically need to do a forensic analysis in order to figure out how to mock up new instructions in the interpreter, which is probably a rather common task considering the continual evolution of the WASM spec. Having a sample template would expose the major functions and architectural layers involved, even in the absence of an actual user manual. "Use this GDB syntax, watch these 2 numbers get added together, follow the process through the floating-point interpreter, etc." Something like that. Even a YouTube video with a few examples would go a long way. Anything but having every user go through a similar forensic process to figure out how it works.

**Comment by sbc100** [comment]
I'm afraid that documenting the internals of wabt probably isn't something that the core contributors have time to do as we have very limited resources.   Honestly, just readying the code, and perhaps looking at the history (to see where and how instructions get added) is probably the best approach for someone wanting to contribute new instructions.   I apologize if this sounds dismissive of negative, but I am trying to give an honest answer..

**Comment by keithw** [comment]
Closing per last message. And also happy to take improvements to the documentation -- I agree lots of users probably find the learning curve steep.
