### ISSUE TITLE
Is `global.get` allowed in element segments?

### ISSUE THREAD

**Issue by TethysSvensson** [WebAssembly/wabt#2201]
As far as I can tell from the webassembly spec, it should be valid to use the `global.get` instruction in an element segment.

However I am unable to use `wat2wasm` on this module

```wat
(module
  (import "m" "f" (global funcref))
  (table 0 10 funcref)
  (elem 0 (offset (i32.const 0)) funcref (global.get 0)))
```

If I try, I get this error:

```
foo.wat:4:43: error: invalid elem expression expression; must be either ref.null or ref.func.
  (elem 0 (offset (i32.const 0)) funcref (global.get 0)))
                                          ^^^^^^^^^^
```

If I use the `--no-check` flag I am able to override the check and generate a resulting `.wasm` file.

Looking at the generated file in a hexdump, it looks exactly like I would expect it to. However I am unable to get `wasm2wat` to accept this generated module, even if I use the `--no-check` flag.

Am I misreading the spec, or is this a bug in wabt?

**Comment by sbc100** [comment]
Interesting, that does look like a bug in the support for the reference types proposal, but it also must represent a hole in the spec tests since wabt runs all the spec tests tests for reference types.

**Comment by sbc100** [comment]
I added a spec test to cover this case, but it will take a bit of work on the wabt side to fix it I think.
