### ISSUE TITLE
Randomize LC_ALL in CI?

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/wabt#2243]
This is a silly request but it'd be neat if CI simply randomized LC_ALL.

Yeah it'd mean failure is probabilistic instead of guaranteed, but it'd help expand the test surface.

**Comment by sbc100** [comment]
What kind of failures are you hoping to catch?

**Comment by SoniEx2** [comment]
the kind of failures that happen when someone tries to parse localizable strings ^^

**Comment by keithw** [comment]
WABT itself never calls setlocale(), so afaik there's no way that the LC_ALL environment variable can affect the behavior of any of the executables or tests.

I also don't **think** libwabt ever calls a locale-sensitive function (so even if it's linked with an application that has called setlocale(), I don't think libwabt's behavior will be affected), but I'm not 100% sure about this. If we find a counterexample, my view would be that we should probably just remove it...

**Comment by SoniEx2** [comment]
yeah, but you never know whether you're accidentally relying on localizable strings in e.g. shell scripts.

randomizing LC_ALL should make it obvious if you are.

**Comment by sbc100** [comment]
Have we had reports of such issues in wabt?

**Comment by SoniEx2** [comment]
Not that we know of, no. And it should stay that way.

**Comment by keithw** [comment]
Closing for now -- I don't think we have consensus that the benefit here would be worth it.
