### ISSUE TITLE
error: couldn't allocate input reg for constraint 'r' on MIPS with clang when compiling wasm2c-generated source

### ISSUE THREAD

**Issue by glandium** [WebAssembly/wabt#2266]
When compiling Firefox (which uses wasm2c) for MIPS with clang, the following error happens:
```
rlbox.wasm.c:142:1: error: couldn't allocate input reg for constraint 'r'
 DEFINE_LOAD(f32_load, f32, f32, f32)
 ^
 rlbox.wasm.c:128:14: note: expanded from macro 'DEFINE_LOAD'
     wasm_asm("" ::"r"(result));                            \
```

GCC is happy with it, but fundamentally, the asm constraint is wrong (r is for GPRs, and here the result is a floating point value).

Those constraints were added in a7d484ef3d1f64649dd9f48cb1d5434f0fda561b, and the reason given was:
> Preventing load instructions from being optimized away if their value is unused (using inline assembly with an input operand and empty code). This is necessary to f
orce an OOB trap on platforms that use mprotect and the signal handler to detect OOB.

Would using `__attribute__((used))` work instead? Or volatile?

**Comment by sbc100** [comment]
While we should fix this.. I do wonder if FF might want to disable these directives.. since IIRC they exist mostly to confirm to strict letter to the spec (i.e. deterministic trapping).. but its seems like a use case like FF (where the desired semantics want to be closer to the original C code) these are an unnecessary slowdown.   @shravanrn WDYT?

**Comment by keithw** [comment]
> Would using __attribute__((used)) work instead? Or volatile?

Volatile would work but I think the performance impact is probably way too big -- we want the compiler to be able to optimize duplicate loads, store-then-load, etc.

I think `__attribute__((used))` is only useful for static objects (it forces them to be emitted even if unused).

I'd love to find a more general way to solve this. GCC does seem to include floating-point registers as "general registers" for purposes of this "GCC simple asm" constraint, so there is an argument that clang should be bug-compatible here (even on MIPS). But I guess the more practical route to solving this (if we care about obeying the Wasm spec on MIPS) is probably to find the appropriate asm constraint on that platform and #ifdef it...

**Comment by shravanrn** [comment]
> I do wonder if FF might want to disable these directives.. since IIRC they exist mostly to confirm to strict letter to the spec (i.e. deterministic trapping).. but its seems like a use case like FF (where the desired semantics want to be closer to the original C code) these are an unnecessary slowdown

**Re perf** Yup, this is true. Although, in practice, I am not sure if this will amount to noticeable performance differences as the Wasm file being produced in the Firefox use case is the result of compilation under clang's O2 or O3 flags. Thus, it would seem unlikely that many unused memory loads have survived this far. Given this, removing the reg constraints isn't a high priority performance change at the moment, but it is possible that some future workloads may see more of a performance gap.

**Re unblocking this use case** That said, I think we would be fine to just add a flag to disable the reg constraints to unblock this use case while we investigate better solutions. Alternately, we can temporarily disable this constraint for the precise combination of "floats on MIPS with clang".  Either would be fine by me. 

**Re better solution** For the moment, the only thing i can think of is to introduce a call to a noop function with the result of the load and then rely on LTO to eliminate this. Example below. My guess is that this could be ok performance wise with LTO disabled, but will significantly affect performance without LTO.

```c
void dont_eliminate_float_read(float v);

#define DEFINE_LOAD(name, t1, t2, t3)                                  \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {             \
    MEMCHECK(mem, addr, t1);                                           \
    t1 result;                                                         \
    wasm_rt_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], \
                   sizeof(t1));                                        \
    dont_eliminate_float_read(result);                                 \
    return (t3)(t2)result;                                             \
  }
```

Separate asm file

```s
dont_eliminate_float_read:
    ret
```

**Comment by sbc100** [comment]
But if `dont_eliminate_float_read` is written in asm then LTO can't eliminate it, right?

Also, if LTO was able eliminate it would it also be able to eliminate the now-dead load?

**Comment by keithw** [comment]
I think this is ultimately a clang-on-MIPS bug for failing to interpret the constraint the same as GCC, but we can be more conservative in the use of inline asm by limiting our use to "known-good" architectures. We already do this for SIMD loads, so this makes the non-SIMD loads more consistent.

I submitted #2267 which I think fixes this -- @shravanrn @sbc100 @glandium wdyt?

**Comment by shravanrn** [comment]
> But if `dont_eliminate_float_read` is written in asm then LTO can't eliminate it, right?
> 
> Also, if LTO was able eliminate it would it also be able to eliminate the now-dead load?

You're probably right tbh. Even if something like this worked, it would probably be too brittle to deploy.

**Comment by shravanrn** [comment]
Another idea: the issue seems to occur only when reading floats right? Would it make sense to copy floats into a u32 first with a memcpy, apply the reg constraint as a u32, and then use a second memcpy to copy the result into a float, i.e., would something like this work? 

```
static inline f32 f32_load(wasm_rt_memory_t* mem, u64 addr) {
  MEMCHECK(mem, addr, f32);
  u32 result;
  wasm_rt_memcpy(&result, &mem->data[addr], sizeof(t1));
  __asm__("" ::"r"(result));

  f32 float_result;
  wasm_rt_memcpy(&float_result, &result, sizeof(t1));
  return float_result;
}
```

**Comment by glandium** [comment]
@keithw Ideally the force reads would be separated for integers and floats, to have the possibility of using the right constraint for each. BTW, the right constraint for floats on mips would be `"f"`

**Comment by shravanrn** [comment]
^ Oh that seems way better

**Comment by keithw** [comment]
We can do that, but somebody should also report this as a bug to clang -- it really should match GCC's interpretation of the meaning of the asm constraints. This is a GNU extension (and clang seems to agree on non-MIPS platforms).
