### ISSUE TITLE
desugar: overflow issue for typeidx of call_indirect instruction

### ISSUE THREAD

**Issue by jhscheer** [WebAssembly/wabt#2270]
wat-desugar (1.0.33) seems to have an overflow issue for the `typeidx` of the `call_indirect` instruction.

e.g.:
This module (located [here](https://github.com/WebAssembly/spec/blob/master/test/core/ref_func.wast)):
``` wat
(module
  (func $f (import "M" "f") (param i32) (result i32))
  (func $g (param $x i32) (result i32)
    (i32.add (local.get $x) (i32.const 1))
  )

  (global funcref (ref.func $f))
  (global funcref (ref.func $g))
  (global $v (mut funcref) (ref.func $f))

  (global funcref (ref.func $gf1))
  (global funcref (ref.func $gf2))
  (func (drop (ref.func $ff1)) (drop (ref.func $ff2)))
  (elem declare func $gf1 $ff1)
  (elem declare funcref (ref.func $gf2) (ref.func $ff2))
  (func $gf1)
  (func $gf2)
  (func $ff1)
  (func $ff2)

  (func (export "is_null-f") (result i32)
    (ref.is_null (ref.func $f))
  )
  (func (export "is_null-g") (result i32)
    (ref.is_null (ref.func $g))
  )
  (func (export "is_null-v") (result i32)
    (ref.is_null (global.get $v))
  )

  (func (export "set-f") (global.set $v (ref.func $f)))
  (func (export "set-g") (global.set $v (ref.func $g)))

  (table $t 1 funcref)
  (elem declare func $f $g)

  (func (export "call-f") (param $x i32) (result i32)
    (table.set $t (i32.const 0) (ref.func $f))
    (call_indirect $t (param i32) (result i32) (local.get $x) (i32.const 0))
  )
  (func (export "call-g") (param $x i32) (result i32)
    (table.set $t (i32.const 0) (ref.func $g))
    (call_indirect $t (param i32) (result i32) (local.get $x) (i32.const 0))
  )
  (func (export "call-v") (param $x i32) (result i32)
    (table.set $t (i32.const 0) (global.get $v))
    (call_indirect $t (param i32) (result i32) (local.get $x) (i32.const 0))
  )
)
```
will look like this when run through `wat-desugar`:
``` wat
(module
  (import "M" "f" (func $f (param i32) (result i32)))
  (func $g (param $x i32) (result i32)
    local.get $x
    i32.const 1
    i32.add)
  (global (;0;) funcref (ref.func $f))
  (global (;1;) funcref (ref.func $g))
  (global $v (mut funcref) (ref.func $f))
  (global (;3;) funcref (ref.func $gf1))
  (global (;4;) funcref (ref.func $gf2))
  (func (;2;)
    ref.func $ff1
    drop
    ref.func $ff2
    drop)
  (elem (;0;) declare func $gf1 $ff1)
  (elem (;1;) declare func $gf2 $ff2)
  (func $gf1)
  (func $gf2)
  (func $ff1)
  (func $ff2)
  (func (;7;) (result i32)
    ref.func $f
    ref.is_null)
  (export "is_null-f" (func 7))
  (func (;8;) (result i32)
    ref.func $g
    ref.is_null)
  (export "is_null-g" (func 8))
  (func (;9;) (result i32)
    global.get $v
    ref.is_null)
  (export "is_null-v" (func 9))
  (func (;10;)
    ref.func $f
    global.set $v)
  (export "set-f" (func 10))
  (func (;11;)
    ref.func $g
    global.set $v)
  (export "set-g" (func 11))
  (table $t 1 funcref)
  (elem (;2;) declare func $f $g)
  (func (;12;) (param $x i32) (result i32)
    i32.const 0
    ref.func $f
    table.set $t
    local.get $x
    i32.const 0
    call_indirect $t (type 4294967295))
  (export "call-f" (func 12))
  (func (;13;) (param $x i32) (result i32)
    i32.const 0
    ref.func $g
    table.set $t
    local.get $x
    i32.const 0
    call_indirect $t (type 4294967295))
  (export "call-g" (func 13))
  (func (;14;) (param $x i32) (result i32)
    i32.const 0
    global.get $v
    table.set $t
    local.get $x
    i32.const 0
    call_indirect $t (type 4294967295))
  (export "call-v" (func 14))
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func))
  (type (;2;) (func (result i32))))
```

Notice that the `typeidx` of `call_indirect` is **4294967295** when it should be **0** (in this case).

**Comment by keithw** [comment]
Thank you for finding and reporting this!

**Comment by keithw** [comment]
BTW: I'm curious if you get a lot of value out of wat-desugar? As you can probably see from #2278, we're considering eliminating it and telling people to use wat2wasm | wasm2wat if they want this functionality. Do you have thoughts/would this be a problem for your use-case?

**Comment by jhscheer** [comment]
My main use-case is to quickly toggle folded expressions with `--fold-exprs`. This is also possible with wasm2wat.
However, the "wat2wasm | wasm2wat" transformation is not lossless, e.g. the order of the Module Fields is changed and the symbolic identifiers are gone.

For comparison, the above mentioned Module run through "wat2wasm | wasm2wat":
```wat
(module
  (type (;0;) (func (param i32) (result i32)))
  (type (;1;) (func))
  (type (;2;) (func (result i32)))
  (import "M" "f" (func (;0;) (type 0)))
  (func (;1;) (type 0) (param i32) (result i32)
    local.get 0
    i32.const 1
    i32.add)
  (func (;2;) (type 1)
    ref.func 5
    drop
    ref.func 6
    drop)
  (func (;3;) (type 1))
  (func (;4;) (type 1))
  (func (;5;) (type 1))
  (func (;6;) (type 1))
  (func (;7;) (type 2) (result i32)
    ref.func 0
    ref.is_null)
  (func (;8;) (type 2) (result i32)
    ref.func 1
    ref.is_null)
  (func (;9;) (type 2) (result i32)
    global.get 2
    ref.is_null)
  (func (;10;) (type 1)
    ref.func 0
    global.set 2)
  (func (;11;) (type 1)
    ref.func 1
    global.set 2)
  (func (;12;) (type 0) (param i32) (result i32)
    i32.const 0
    ref.func 0
    table.set 0
    local.get 0
    i32.const 0
    call_indirect (type 0))
  (func (;13;) (type 0) (param i32) (result i32)
    i32.const 0
    ref.func 1
    table.set 0
    local.get 0
    i32.const 0
    call_indirect (type 0))
  (func (;14;) (type 0) (param i32) (result i32)
    i32.const 0
    global.get 2
    table.set 0
    local.get 0
    i32.const 0
    call_indirect (type 0))
  (table (;0;) 1 funcref)
  (global (;0;) funcref (ref.func 0))
  (global (;1;) funcref (ref.func 1))
  (global (;2;) (mut funcref) (ref.func 0))
  (global (;3;) funcref (ref.func 3))
  (global (;4;) funcref (ref.func 4))
  (export "is_null-f" (func 7))
  (export "is_null-g" (func 8))
  (export "is_null-v" (func 9))
  (export "set-f" (func 10))
  (export "set-g" (func 11))
  (export "call-f" (func 12))
  (export "call-g" (func 13))
  (export "call-v" (func 14))
  (elem (;0;) declare func 3 5)
  (elem (;1;) declare func 4 6)
  (elem (;2;) declare func 0 1))
```

**Comment by sbc100** [comment]
> My main use-case is to quickly toggle folded expressions with `--fold-exprs`. This is also possible with wasm2wat. However, the "wat2wasm | wasm2wat" transformation is not lossless, e.g. the order of the Module Fields is changed and the symbolic identifiers are gone.
wat2wasm

Does adding `--debug-names` to wat2wasm fix the symbolic identifiers issue?

I think it would be good if we could make `wat2wasm | wasm2wat` basically the same as wat-desugar.. unless there is some reason why they should differ?

> 
> For comparison, the above mentioned Module run through "wat2wasm | wasm2wat":
> 
> ```webassembly
> (module
>   (type (;0;) (func (param i32) (result i32)))
>   (type (;1;) (func))
>   (type (;2;) (func (result i32)))
>   (import "M" "f" (func (;0;) (type 0)))
>   (func (;1;) (type 0) (param i32) (result i32)
>     local.get 0
>     i32.const 1
>     i32.add)
>   (func (;2;) (type 1)
>     ref.func 5
>     drop
>     ref.func 6
>     drop)
>   (func (;3;) (type 1))
>   (func (;4;) (type 1))
>   (func (;5;) (type 1))
>   (func (;6;) (type 1))
>   (func (;7;) (type 2) (result i32)
>     ref.func 0
>     ref.is_null)
>   (func (;8;) (type 2) (result i32)
>     ref.func 1
>     ref.is_null)
>   (func (;9;) (type 2) (result i32)
>     global.get 2
>     ref.is_null)
>   (func (;10;) (type 1)
>     ref.func 0
>     global.set 2)
>   (func (;11;) (type 1)
>     ref.func 1
>     global.set 2)
>   (func (;12;) (type 0) (param i32) (result i32)
>     i32.const 0
>     ref.func 0
>     table.set 0
>     local.get 0
>     i32.const 0
>     call_indirect (type 0))
>   (func (;13;) (type 0) (param i32) (result i32)
>     i32.const 0
>     ref.func 1
>     table.set 0
>     local.get 0
>     i32.const 0
>     call_indirect (type 0))
>   (func (;14;) (type 0) (param i32) (result i32)
>     i32.const 0
>     global.get 2
>     table.set 0
>     local.get 0
>     i32.const 0
>     call_indirect (type 0))
>   (table (;0;) 1 funcref)
>   (global (;0;) funcref (ref.func 0))
>   (global (;1;) funcref (ref.func 1))
>   (global (;2;) (mut funcref) (ref.func 0))
>   (global (;3;) funcref (ref.func 3))
>   (global (;4;) funcref (ref.func 4))
>   (export "is_null-f" (func 7))
>   (export "is_null-g" (func 8))
>   (export "is_null-v" (func 9))
>   (export "set-f" (func 10))
>   (export "set-g" (func 11))
>   (export "call-f" (func 12))
>   (export "call-g" (func 13))
>   (export "call-v" (func 14))
>   (elem (;0;) declare func 3 5)
>   (elem (;1;) declare func 4 6)
>   (elem (;2;) declare func 0 1))
> ```

**Comment by jhscheer** [comment]
> 
> Does adding `--debug-names` to wat2wasm fix the symbolic identifiers issue?
> 

Yes, thanks for the tip.
