### ISSUE TITLE
wasm2wat : Unexpected opcode 0xfe 0x25

### ISSUE THREAD

**Issue by Dalzhim** [WebAssembly/wabt#2281]
I'm encountering an error when trying to convert my wasm file to a wat file using `wasm2wat`. The error is `0003778: error: unexpected opcode: 0xfe 0x25`. I am able to run other tools such as `wasm-decompile` and `wasm-objdump` on the same wasm file. It appears that the opcode means `i32.atomic.rmw.sub` as far as I can tell from the disassembly :
```
 003776: fe 25 02 04                |   i32.atomic.rmw.sub 2 4
```

I notice a difference between the address in the error message (0003778) and the one from the disassembly (003776). Is it meaningful?

Otherwise, my main objective is to successfully convert my existing wasm file. Any idea how I can solve or debug this opcode issue?

**Comment by sbc100** [comment]
The opcode is part of the threads proposal so you probably need to pass `--enable-threads` to wasm2wat.

**Comment by Dalzhim** [comment]
Thank you, that parameter did solve my issue! Something in my codebase must have changed and added a new dependency I wasn't aware of for threads to have become necessary, but that is not an issue for here! ;)
