### ISSUE TITLE
Proposal: stats

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/wabt#2295]
Currently, wabt has opcodecnt, used to output opcode counts. We would kinda like to see a more general tool to output (and in some sense, visualize) various stats for a given wasm file.

Function/global/import/export counts, opcodes per function, local count (okay it's currently possible to find the max locals using `opcodecnt|grep` but anyway), max stack size, honestly the list is kinda endless...

We do appreciate the existing opcodecnt functionality and its 2 data visualization outputs:

- Count of each opcode by type. (e.g. "local.get")
- Count of each opcode by instance. (e.g. "local.get 1")

**Comment by SoniEx2** [comment]
If there is interest in this, we think a good first step would be to rename "opcodecnt" to "stats".

**Comment by sbc100** [comment]
I don't know of anyone who uses this tool.  If you are using it and you want to make improvements that certainly sounds reasonable to me.

**Comment by SoniEx2** [comment]
Hmm, think we should break this issue down into smaller issues, especially now that wasm-opcodecnt has been renamed to wasm-stats. :) (ref #2298 )
