### ISSUE TITLE
Need Help | wat2wasm: "error: unexpected token"

### ISSUE THREAD

**Issue by shamb0** [WebAssembly/wabt#2337]
Hi @everyone,

I need assistance with using the "wat2wasm" conversion tool correctly.

- For demonstration, I have chosen the file "left-to-right.wast," available [here](https://github.com/WebAssembly/testsuite/blob/dc27dad3e34e466bdbfea32fe3c73f5e31f88560/left-to-right.wast).

- When using the "wat2wasm" tool, I encountered an error: "error: unexpected token" at line 181, as depicted in this screenshot: 

![Error Screenshot](https://i.imgur.com/8m2dXyn.png).

- For testing purposes, I eliminated all statements after line 180. The modified file is shown here: 

![Testing Snapshot](https://i.imgur.com/poeS0yB.png).

- This change allowed the tool to function correctly, as seen in this screenshot: 

![Successful Result](https://i.imgur.com/lwLSqmN.png).

- I noticed similar results with these tools:

- [demo/wat2wasm](https://webassembly.github.io/wabt/demo/wat2wasm/)

  ![Tool Screenshot](https://i.imgur.com/LKj2kY5.png)

- [bytecodealliance/wasm-tools](https://github.com/bytecodealliance/wasm-tools)

  ![Tool Screenshot](https://i.imgur.com/LgH3qVi.png)

- Could I be missing any specific option flags or not using the correct test specification? Your guidance would be helpful.

**Comment by shamb0** [comment]
Thanks @sbc100,

With help of your suggestion, I've successfully extracted the wasm file from wast using the `wast2json` tool by following these steps:

```shell
./out/clang/Debug/wast2json \
    --enable-all \
    ./third_party/testsuite/left-to-right.wast \
    -o ../temp01-shamb0-test/left-to-right.json
```

- The resulting files are:

```shell
.
├── left-to-right.0.wasm
└── left-to-right.json
```

- I attempted to test the wasm file with `wasmtime` using this command:

```shell
RUST_LOG=trace ./target/debug/wasmtime \
    --debug debug-info=true \
    ../temp01-shamb0-test/left-to-right.0.wasm \
    --invoke get 2
```

![](https://i.imgur.com/OJ8voSJ.png)

- However, I did not receive a response from `wasmtime`. Could you advise on how to effectively test the extracted wasm file?

Your guidance is appreciated.

**Comment by keithw** [comment]
If you want to run the tests in that file, you can use wabt's interpreter (with the spectest imports):

```sh
$ ./bin/wast2json ./third_party/testsuite/left-to-right.wast -o /tmp/ltr/left-to-right.json
$ ./bin/spectest-interp /tmp/ltr/left-to-right.json
96/96 tests passed.
```

To run an individual exported function (without the spectest imports available):
```sh
$ ./bin/wasm-interp /tmp/ltr/left-to-right.0.wasm --run-export=i32_call_indirect
i32_call_indirect() => i32:66052
```

**Comment by shamb0** [comment]
Thank you @keithw, following your suggestion, I successfully ran the wasm file using `wasm-interp`.

Thanks to @sbc100's pointer, I will check with the 'wasmtime' team regarding the observed behavior.
