### ISSUE TITLE
wasm2c is multiple times slower on Apple ARM processors (M3) than x86-64

### ISSUE THREAD

**Issue by jwatt** [WebAssembly/wabt#2343]
I have a 16-core 7950X and a 16-core M3 MBP. They both build the Firefox source code in roughly the same amount of time...or would, but for the `wasm2c` invocation takes about 1 minute on the former and over 3 minutes on the latter.

For further discussion see: https://bugzilla.mozilla.org/show_bug.cgi?id=1867594#c6

Are there known reasons for wasm2c taking multiple times as long on ARM, and is there any prospect of that improving?

**Comment by keithw** [comment]
Hmm, can you post the module in question (the input to wasm2c)?

**Comment by keithw** [comment]
Closing as dormant (and seemingly solved on the referenced issue, in the sense that this is apparently about unoptimized builds and the performance of unoptimized clang codegen on arm64 vs x86-64).
