### ISSUE TITLE
`wast2json` fails to parse `if.wast` from latest testsuite

### ISSUE THREAD

**Issue by andreaTP** [WebAssembly/wabt#2347]
Hi 👋 and thanks for the super-helpful project!

On my Mac I ca reproduce as follows (in a tmp folder):

```bash
git clone https://github.com/WebAssembly/testsuite.git
wget https://github.com/WebAssembly/wabt/releases/download/1.0.34/wabt-1.0.34-macos-12.tar.gz
./wabt-1.0.34/bin/wast2json ./testsuite/if.wast
```

Produces the unexpected result:

```bash
./testsuite/if.wast:533:33: error: unexpected token (, expected ).
    (if (i32.const 1) (i32.eqz) (then) (else))
                                ^
./testsuite/if.wast:537:17: error: unexpected token "invoke", expected an instr.
(assert_return (invoke "empty" (i32.const 0)))
                ^^^^^^
```

The regression seems to be caused by this diff:
https://github.com/WebAssembly/testsuite/commit/26d62d0ad297b14218807cd20d9b568e11ec7bd9#diff-76c78c41ca3eaa954f864741d9462243de307c6e0ca747b7bcab93fba9767837

**Comment by keithw** [comment]
Yes, here is the upstream addition to the testsuite: https://github.com/WebAssembly/spec/pull/1682

Will have to take a look at the WAT parser (wasm-tools already fixed this here, which maybe we can use as inspiration: https://github.com/bytecodealliance/wasm-tools/pull/1215).

Unfortunately this isn't the only change in the testsuite repo that will cause issues; the new testsuite also upgrades the exception-handling proposal to "v4" of that proposal (adding try_table, eliminating try_catch & try_delegate, and restoring exnref), which is going to require a bunch of work in the text/binary readers and writers, interpreter, and wasm2c to support

**Comment by andreaTP** [comment]
Thanks for the quick turnaround!
Do you have already a release date in mind?

**Comment by keithw** [comment]
Not really -- if this is something users are clamoring for, we could cut a release right now.

**Comment by andreaTP** [comment]
Just nice to have from my side, I'm not blocked 👍
