### ISSUE TITLE
wat2wasm fails converting .wast files in testsuite: error: unexpected token (, expected EOF.

### ISSUE THREAD

**Issue by AbeWJS** [WebAssembly/wabt#2375]
Fresh clone of WABT on macOS built with CMake and make results in wat2wasm reporting errors like this one:

`local build % ./wat2wasm ../third_party/testsuite/f32.wast -o ~/wasm_test.wasm
../third_party/testsuite/f32.wast:19:1: error: unexpected token (, expected EOF.
(assert_return (invoke "add" (f32.const -0x0p+0) (f32.const -0x0p+0)) (f32.co...
^
`

Perhaps a configuration issue, but unsure why this would happen, everything suggests this should work out of the box.

**Comment by AbeWJS** [comment]
Ah, is this just the assert firing as ARM isn't supported?

**Comment by SoniEx2** [comment]
wat (webassembly text format) 2 wasm does not support wast (which we believe originally stood for webassembly spec test?) files
