### ISSUE TITLE
Use of call_ref does not take a type indice in wat2wasm

### ISSUE THREAD

**Issue by jlpettersson** [WebAssembly/wabt#2383]
I am trying to use `call_ref` from [function references](https://webassembly.github.io/function-references/core/). According to the linked documentation, I thought that I should include a type index when using `call_ref` instruction. But `wat2wasm` does not build with a type index passed.

I tried with this example, using latest `wat2wasm` (version 1.0.34).

```
(module
    (type $f_type (func (result i32)))
    (table 2 funcref)
    (elem (i32.const 0) func $f1 $f2)

    (func $f1 (result i32)
        (i32.const 99)
    )

    (func $f2 (result i32)
        (i32.const 71)
    )

    (func (export "c") (result i32)

        (ref.func $f1)
        (call_ref $f_type)  ;; expected to pass $f_type here, but only builds without it.

    )
)
```

When I change `(call_ref $f_type)` to only `(call_ref)`, it builds using wat2wasm. However that wasm binary does not run using `node --experimental-wasm-typed_funcref`, it throws `[CompileError: WebAssembly.instantiate(): Compiling function #2 failed: invalid signature index: 11 @+64]`, but this issue is mainly how I should use `call_ref`with `wat2wasm`.

**Comment by keithw** [comment]
WABT doesn't support the function-references (or GC) proposals -- we don't even have it in our feature matrix yet (https://github.com/WebAssembly/wabt/). :-(

You will probably have better luck with `wasm-tools parse` or binaryen's `wasm-as`.
