### ISSUE TITLE
WASM2C - What happened to wasm_rt_allocate_memory

### ISSUE THREAD

**Issue by woodsmc** [WebAssembly/wabt#2391]
The function prototype is available in the header file: `wasm-rt.h` line : 512
 
But is missing from the implementation file : `wasm-rt-impl.c`, it appears to have been removed here - 80b4f087aa65a7f23d3489f80eaa298a1cdb3913

Has it be deprecated? or has the function implementation been moved to another .c file?

**Comment by keithw** [comment]
Hello Chris -- see https://github.com/WebAssembly/wabt/blob/main/wasm2c/wasm-rt-mem-impl-helper.inc#L66-L94 , included at https://github.com/WebAssembly/wabt/blob/main/wasm2c/wasm-rt-mem-impl.c#L161 .

The wasm2c README has just been updated (thanks to you) to include the additional source file: https://github.com/WebAssembly/wabt/blob/main/wasm2c/README.md?plain=1#L116

(BTW I replied to your email an hour+ ago -- did it not arrive?)

**Comment by shravanrn** [comment]
Documented in PRs #2390 #2392

**Comment by woodsmc** [comment]
Thanks folks. I missed the email, but really appreciate the support.
