### ISSUE TITLE
Error while running testsuite (simd_lane, simd_load) "loop not vectorized"

### ISSUE THREAD

**Issue by lanodan** [WebAssembly/wabt#2403]
- wabt 1.0.34
- clang 17.0.6

Extracted lines:
```
out/test/wasm2c/spec/simd_lane/simd_lane.0.c:967:6: error: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
out/test/wasm2c/spec/simd_load/simd_load.12.c:803:6: error: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
```

Full build log: [wabt-1.0.34_broken_simd_tests:20240319-155457.log](https://github.com/WebAssembly/wabt/files/14653567/wabt-1.0.34_broken_simd_tests.20240319-155457.log)

**Comment by SoniEx2** [comment]
we believe this could be a matter of updating simde.

**Comment by lanodan** [comment]
Interesting, I ran it on simde 0.8.0 which is pretty recent so might have been caused by a recent update of it?

**Comment by SoniEx2** [comment]
nah, the issue seems to happen in the old version too, we just thought it might've been fixed but we guess not.

we don't really understand why it's erroring/warning like that, tbh.
