### ISSUE TITLE
Wast2Json fails on the testsuite

### ISSUE THREAD

**Issue by CharlieTap** [WebAssembly/wabt#2410]
Running the latest wast2json  (1.0.34) on [comments.wast](https://github.com/WebAssembly/testsuite/blob/main/comments.wast) or [if.wast](https://github.com/WebAssembly/testsuite/blob/main/if.wast) fails with the following errors:

```sh
comments.wast:104:1: error: unexpected token "(", expected a binary module or a text module.
(assert_return (invoke "f1") (i32.const 2))
^
comments.wast:104:30: error: unexpected token (, expected EOF.
(assert_return (invoke "f1") (i32.const 2))
                             ^
if.wast:533:33: error: unexpected token (, expected ).
    (if (i32.const 1) (i32.eqz) (then) (else))
                                ^
if.wast:537:17: error: unexpected token "invoke", expected an instr.
(assert_return (invoke "empty" (i32.const 0)))
                ^^^^^^
```

**Comment by sbc100** [comment]
wast2json is only known to work on the version of the testsuite that wabt itself includes as a submodule.   Once that gets updated I assume wast2json will get updated too, but we don't know of any efforts to update currently.

**Comment by keithw** [comment]
wast2json (from Git) does work on the latest if.wast (since #2349); we just haven't done a release since then.

We do need to update for the spec change that affected comments.wast (https://github.com/WebAssembly/spec/pull/1684).

**Comment by sbc100** [comment]
I'm trying to roll the testsuite now and I'm running into this issue too.    Do you have a fix the comments.wast issue @keithw ?

**Comment by keithw** [comment]
Unfortunately I haven't looked at this one yet.

**Comment by sbc100** [comment]
FYI I looked into just now and made some progres.... but haven't fully figured it out yet.

**Comment by sbc100** [comment]
The comments.wast issue was fixed in #2416

**Comment by CharlieTap** [comment]
Whats the chances we can get a release soon for this? I'd like to update this in the CI for my project but I don't build from source as it takes a while 😅

**Comment by sbc100** [comment]
I don't see why we can't do one right now.. I'll see its as simple as just creating a release..
