### ISSUE TITLE
[wasm2c] Strange issue with double parsing in msvc

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#2422]
For some reason INT_MIN is not parsing correctly under MSVC.. 

```
#include <stdio.h>

int main() {
  double x = -2147483648;
  double y = -2147483648L;
  double z = -2147483648.0;
  printf("%f\n", x);
  printf("%f\n", y);
  printf("%f\n", z);
}
```

Under MSVC this produces:

```
2147483648.000000
2147483648.000000
-2147483648.000000
```

i.e. only adding `.0` at the end causes the sign bit to be preserved.

Gcc and clang both (correctly I believe) produce:

```
-2147483648.000000
-2147483648.000000
-2147483648.000000
```

**Comment by SoniEx2** [comment]
isn't this #2389 ?

**Comment by SoniEx2** [comment]
INT_MIN/etc are notorious for being a pain as a numeric constant, the usual workaround is to write it as an expression (-2147483647 - 1).

(something about it being technically UB?)

**Comment by sbc100** [comment]
Ah yes, I think #2389 will fix this.  My fix was to append `.0` which also seems to work.

**Comment by sbc100** [comment]
`-fsanitize=undefined` doesn't warn here..

**Comment by sbc100** [comment]
Closing as duplicate of #2388
