### ISSUE TITLE
“picosha2.h”: No such file or directory 

### ISSUE THREAD

**Issue by dairuidark** [WebAssembly/wabt#2429]
I'm not sure if the usage of cmake is correct, this is the command I ran, and I got a file not found error, please help me, thank you.

cmake --build .. --config DEBUG --target install

cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=..\..\ -G "Visual Studio 2022"

“picosha2.h”: No such file or directory [D:\P
rogram Files\wasm2c\wabt\build\wabt.vcxproj]

**Comment by turuslan** [comment]
Hello, @dairuidark.

Have you tried cloning submodules (`git clone --recursive ...` or `git submodule init`)?

I had same error because [hunter](https://github.com/cpp-pm/hunter) package manager didn't clone submodules (third_party/picosha2).

**Comment by keithw** [comment]
Closing as answered.
