### ISSUE TITLE
Module fails to compile without a proper error message

### ISSUE THREAD

**Issue by Janrupf** [WebAssembly/wabt#2453]
The following module fails to compile:

```wasm
(module
    (func (param externref) (result i32)
        (ref.is_null)
    )
)
```

Running `wat2wasm` on this leads to an exit code if 1, but no proper error message. Debugging with GDB shows that the typechecker throws an error here:
https://github.com/WebAssembly/wabt/blob/1edeaf2948b4afd711e50ba2007ee44503cd80fe/src/type-checker.cc#L814

The problem is, that even though the `result` is now set to an error, no error message is printed, as the `PeekType` function doesn't do so. This code is obviously not valid WASM (its missing a `local.get 0` in front of `ref.is_null`), but I still would expect a proper error message.

<details><summary>Example with `i32.add`</summary>

```wasm
(module
    (func (param i32) (result i32)
        (i32.add)
    )
)
```

Gives a proper error message:
```
simple.wat:3:10: error: type mismatch in i32.add, expected [i32, i32] but got []
        (i32.add)
         ^^^^^^^
```
</details>

(NOTE: After looking at the at the following the `PeekType` call, I assume the condition should have been `type == Type::Any || !type.IsRef()`)

**Comment by AG-597** [comment]
I have this same issue, it simply runs, then returns no output, no error message.

**Comment by sbc100** [comment]
I think think assumption looks correct.  Would you be able to send a PR to fix that line?

**Comment by SoniEx2** [comment]
we think we can fix this...
