### ISSUE TITLE
Something wrong with wasm to wat conversion.

### ISSUE THREAD

**Issue by Yeeyooo** [WebAssembly/wabt#2511]
Hello, I encountered some problems when I'm trying to use wasm2wat.
I tried to use wasm2wat to convert some wasm file(with wasmgc) to text format, but the conversion failed, giving the warning:
`000000f: error: expected valid field type (got -0x9)`
After adding the `--enable-gc` option, I got the same error. Then I use the `--enable-all` option, this time I get the following error: 
`000000e: error: unexpected type form (got 0x5e)`.
The command I use is simple: `wasm2wat app_dev.wasm -o app_dev.wat` and `wasm2wat app_dev.wasm -o app_dev.wat --enable-all`.
I tried with some other .wasm files, the conversion processes all failed like above. I'm not sure what is going wrong, maybe some implementation problems?

**Comment by keithw** [comment]
WABT doesn't support the GC proposal (please see the README, https://github.com/WebAssembly/wabt/ , for the list of supported proposals / feature extensions). You'll have better luck using wasm-tools (https://github.com/bytecodealliance/wasm-tools/) which does support GC.

**Comment by Yeeyooo** [comment]
Thank you for your response and recommendation!

**Comment by Yeeyooo** [comment]
> WABT doesn't support the GC proposal (please see the README, https://github.com/WebAssembly/wabt/ , for the list of supported proposals / feature extensions). You'll have better luck using wasm-tools (https://github.com/bytecodealliance/wasm-tools/) which does support GC.

Thank you for your reply and recommendation!
