### ISSUE TITLE
Assertion failure in validator

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#258]
The following code (from a test written for pre-0xa wast) causes the validator to assert:
```
(module
  (func $foo (param f32)
    (call $foo (f32.const 0.0))))
```
```
assertion failed: (var->type == WASM_VAR_TYPE_INDEX), function check_var, file /Users/dschuff/code/WAOT/third_party/wabt/src/validator.c, line 101.
```
Seems valid? Or has the wast syntax changed to no longer allow this?

**Comment by binji** [comment]
I can't repro this. Are you using an old wast2wasm?

**Comment by dschuff** [comment]
Looks like I wasn't running `wasm_resolve_names_script` which is necessary before validation.
