### ISSUE TITLE
Add support to Freebsd build

### ISSUE THREAD

**Issue by microbash** [WebAssembly/wabt#262]
Hello.
Could you add support to freebsd build?
I have tried to make but unsuccessful.

# git clone --recursive https://github.com/WebAssembly/wabt
# cd wabt/
# gmake
mkdir -p out/clang/Debug/
cd out/clang/Debug/ && cmake -G "Unix Makefiles" /tmp/wabt/ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/local/llvm39/bin/clang
-- Check for working C compiler: /usr/local/llvm39/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/llvm39/bin/clang++
-- Check for working CXX compiler: /usr/local/llvm39/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for alloca.h
-- Looking for alloca.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Could NOT find BISON: Found unsuitable version "2.7.12-4996", but required is at least "3.0" (found /usr/local/bin/bison)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.11", minimum required is "2.7")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/wabt/out/clang/Debug
gmake --no-print-directory -C out/clang/Debug/ all
Scanning dependencies of target hexfloat_test
[  2%] Building C object CMakeFiles/hexfloat_test.dir/src/literal.c.o
In file included from /tmp/wabt/src/literal.c:17:
In file included from /tmp/wabt/src/literal.h:22:
In file included from /tmp/wabt/src/common.h:26:
/tmp/wabt/out/clang/Debug/config.h:57:2: error: no alloca
#error no alloca
 ^
1 error generated.
CMakeFiles/hexfloat_test.dir/build.make:62: recipe for target 'CMakeFiles/hexfloat_test.dir/src/literal.c.o' failed
gmake[3]: *** [CMakeFiles/hexfloat_test.dir/src/literal.c.o] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/hexfloat_test.dir/all' failed
gmake[2]: *** [CMakeFiles/hexfloat_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
gmake[1]: *** [all] Error 2
Makefile:164: recipe for target 'clang-debug' failed
gmake: *** [clang-debug] Error 2

**Comment by binji** [comment]
Does this fix it?

**Comment by microbash** [comment]
Yes. I can compile it completely. Thank you. Very fast answer and solution.

**Comment by binji** [comment]
Cool :)
