### ISSUE TITLE
decoding the end of the reloc section

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wabt#272]
With the change in d3c6c973d9c5fe13ad1066d5de47470a41b54943, wasm2wast etc. seem to handle the end of the reloc section differently. With this binary:
```
$ hexdump -C t.o
00000000  00 61 73 6d 0d 00 00 00  01 84 80 80 80 00 01 60  |.asm...........`|
00000010  00 00 02 8e 80 80 80 00  01 03 65 6e 76 06 70 72  |..........env.pr|
00000020  69 6e 74 66 00 00 03 82  80 80 80 00 01 00 04 84  |intf............|
00000030  80 80 80 00 01 70 00 00  05 83 80 80 80 00 01 00  |.....p..........|
00000040  00 0a 8b 80 80 80 00 01  09 00 10 80 80 80 80 00  |................|
00000050  0f 0b 00 93 80 80 80 00  04 6e 61 6d 65 02 06 70  |.........name..p|
00000060  72 69 6e 74 66 00 03 66  6f 6f 00 00 8a 80 80 80  |rintf..foo......|
00000070  00 05 72 65 6c 6f 63 01  00 00 04                 |..reloc....|
0000007b
```
Before the patch I got this:
```
$ wasm2wast t.o
(module
  (type (;0;) (func))
  (import "env" "printf" (func printf (type 0)))
  (func foo (type 0)
    call printf
    return)
  (table (;0;) 0 anyfunc)
  (memory (;0;) 0))
```
But after the patch I get this:
```
$ wasm2wast t.o
error: @0x00000079: unfinished section (expected end: 0x7b)
```

**Comment by sbc100** [comment]
Previously there was no support for decoding the reloc section(s) at all.  I think perhaps this is just the fact that the format of the reloc section is still in flux and the format wabt is producing / expecting is different the one you currently produce (the one that is document in tool-conventions).  I have a PR to update tool-conventions now.

**Comment by binji** [comment]
Hm, but it shouldn't fail if reading the reloc section fails.

**Comment by sbc100** [comment]
I'm going to close because I think its just simply wabt not sharing the same format as the llvm output for reloc sections.  It should resolve it itself once we settle on a format.

**Comment by binji** [comment]
I just mean that, in general, wasm2wast shouldn't fail if there is an error in a custom section, even if it's one that we parse like reloc or name.

**Comment by sbc100** [comment]
Really?  Why allow malformed sections?

**Comment by binji** [comment]
Because that's the defined behavior of the wasm binary format: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure

> Custom sections are ignored by the WebAssembly implementation, and thus validation errors within them do not invalidate a module.

**Comment by sbc100** [comment]
Doesn't that just apply to the runtimes?  I would have thought tools like wabt that make use of the custom sections should validate them.   Perhaps in this case, since 2wast is not using the relocation information it should ignore errors here, but 2wast does use the "name" section, right?  So presumably it should fail in the name section is malformed, no?

**Comment by binji** [comment]
I guess I can see it both ways: it would be odd if the runtime can read a wasm file that wasm2wast couldn't. But it also would be nice to know that a section is malformed. I guess this is the case for a warning.
