### ISSUE TITLE
We should be consistent about how we pass WasmStringSlice 

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#274]
right now there is a mix of pass-by-pointer and pass-by-value.  I guess we should probably be consistent and try to pass by pointer or const pointer whereever possible, even through the structure is small.

**Comment by binji** [comment]
I think I'd actually prefer pass by value, since that makes it easy to pass them from one function to another (since there's no const& in C)

**Comment by binji** [comment]
StringSlice is gone now.
