### ISSUE TITLE
Make ownership of string names in WasmBindingHash optional

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#275]
Often the string slices that are using the hash are part of the input file, or otherwise not individually free-able, but WasmBindingHash currently assumes it can/should destroy all the names when it is destroyed.  

A simple flag in the binding data structure would be enough for most cases since I imagine this is an all or nothing kind of thing.

**Comment by binji** [comment]
The binding hash always uses `std::string` now, so this issue is obsolete.
