### ISSUE TITLE
function-section index versus function-index-space index

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wabt#277]
wasmdump -v prints functions with their function-index-space indices, which includes imports:
```
IMPORT:
 - func[0] sig=8 <- env.__syscall6
 - func[1] sig=8 <- env.__syscall140
 - func[2] sig=12 <- env.sbrk
 - func[3] sig=13 <- env.abort
FUNCTION:
 - func[4] sig=0
 - func[5] sig=1
 - func[6] sig=1
```

However, wasmdump -d prints functions with their function-section index.
```
a.out.wasm:     file format wasm 0x00000d

Code Disassembly:
func 0
 00018c: 02 7f                      | block i32
 00018e: 41 00                      |   i32.const 0
...
```
Note the "func 0". It's confusing to see two different index spaces for functions.

As far as I'm aware, function-section indices aren't used for anything in wasm, so my suggestion would be to print function-index-space indices everywhere, because that's what someone debugging a wasm binary is likely to need.

**Comment by binji** [comment]
Agreed, WebAssembly already has enough index spaces, we shouldn't add more. :-)
