### ISSUE TITLE
validation mode for structurally-unreachable code

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#299]
The debate about validating code after unconditional branches/unreachable (https://github.com/WebAssembly/design/pull/894) hasn't really been resolved, and part of the debate hinges on its effect on producers, so it would be nice if wabt had a validation mode (or even just a prototype PR) to reject such structurally-unreachable code to make it easier to prototype/test producer changes.

**Comment by binji** [comment]
We decided not to do this, and instead do full type-checking, Closing.
