### ISSUE TITLE
Assertion on wasm file

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#304]
I hit this when working on binaryen's type system change fuzz testcases, it hits

> wasm2wast: /home/alon/Dev/wabt/src/binary-reader-ast.c:291: WabtResult on_function_signature(uint32_t, uint32_t, void *): Assertion `index < ctx->module->funcs.capacity' failed.

**Comment by kripken** [comment]
Hmm github can't upload binaries, here's a link: https://dl.dropboxusercontent.com/u/80664946/a.out.wasm

**Comment by binji** [comment]
Fixed.
