### ISSUE TITLE
Validation behavior for wabt tools

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#306]
Earlier, I was surprised to find that `wasm2wast` does not validate the binary, but `wast2wasm` does, unless you ask it not to. `wasmdump` also does not. So we should probably reconcile these behaviors somehow. Probably `wasmdump` should not validate, since its purpose is to show a low-level view of the binary. Probably also `wasm2wast` and `wast2wasm` should do the same thing.
A couple of options:
1. `wasm2wast` and `wast2wasm` should validate by default, because their purpose is to convert binaries between formats. Once we have `wat` format, the correspondence will be even more 1:1.
2. The conversion tools do not validate by default, and attempt to convert formats where possible. This probably means more defensive coding in some places.
3. Distinguish between some notion of well-formedness (where conversion is possible or not) vs valid (e.g. type checks pass) and refuse to convert just ill-formed input.

**Comment by binji** [comment]
I have a slight preference for 1. I recall @sbc100 saying he preferred 2. Well, actually 3 I guess, because none of the tools should do anything if the binary or text is not well-formed.

In either case, it probably would be useful to have a standalone validator.

**Comment by dschuff** [comment]
I suppose 1 without 3 would mean that there'd be no flag to disable validation in the conversion tools? Or just best-effort and they might crash or assert if you disable validation (i guess that's essentially the status quo)

**Comment by binji** [comment]
Right, that seems pretty bad to me. So in either case 3 is a necessity IMO.

**Comment by sbc100** [comment]
I don't remember the context where I preferred anything of than (1), but I guess its possible :)

**Comment by binji** [comment]
`wasm2wast` now validates by default (see #516) but can be disabled with `--no-check` (same as the `wast2wasm` flag, though `--no-validate` would be better).
