### ISSUE TITLE
Move to C++

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#308]
I've been thinking about it, and pretty much everybody has said it is a hassle using C. I like it, but that's a silly reason to keep it this way, as maintainability suffers greatly when I'm the only one who wants to hack on the code :)

I'd like to start moving toward using C++ incrementally. Here are some thoughts on how it could progress:

- [x] Rename .c files to .cc files
- [x] Switch to using a C++ compiler
- [x] Use nullptr intead of NULL
- [x] Use C++ casts instead of C-style casts
- [x] Use enum classes
- [x] Use wabt namespace instead of prefix
- [x] Use function overloading
- [x] Switch init/destroy functions into constructors/destructors
- [x] Use new/delete instead of malloc/free (maybe not everywhere at first, since we use realloc)
- [x] Use std::unordered_map instead of WabtBindingHash
- [x] Use std::vector instead of WabtVector
- [x] Slowly remove some of the manual memory management (i.e. use unique_ptr instead, etc.)
- [x] Use virtual functions instead of function pointers (in binary-reader and elsewhere)
- [x] Use the C++ named headers (e.g. cstddef instead of stddef.h)
- [x] Move variables definitions into for loops (e.g. `for (int i = 0; ... )`)

**Comment by KarlSchimpf** [comment]
Sounds good! However, I also assume that you will use virtual functions
instead of a struct of function pointers?

Karl Schimpf

**Comment by binji** [comment]
Yeah, probably. This list is incomplete :)

**Comment by dschuff** [comment]
I think moving to C++ is reasonable, but we should also consider if we want to continue exporting a C API, and what that means exactly. Currently someone who wants to use WABT as a parser will need to use the various entry point functions and the AST data structures directly, which is fairly convenient but obviously would mean compromises between keeping the core data structures as C vs hiding the AST from C users.

Binaryen has a [C API](https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.h) which hides the IR, redefining core types (Type, Literal, etc) exporting constructor functions for all the IR nodes, and exposing functionality such as validation, interpretation, and optimization. But it doesn't allow e.g. traversal of the IR after it is created, which seems like something a user of wabt as a parser would want. OTOH an API which just exported a bunch of complex C structs would probably not be particularly suitable for users of C APIs from languages other than C or C++ so maybe we want to rethink that anyway (and maybe not unless/until some use case appears?)

**Comment by binji** [comment]
Yes, keeping a C API is important, I think. But it's hard to know exactly what that API should be without users.

One thought I had was related to something you asked about. The parser, as it is, currently parses to an IR, but you thought it was callback-based. I was thinking about it, and it might be worthwhile if that was more common for all of wabt. For example, one issue w/ validating the binary format (see #306) is that the validator wants an IR w/ line numbers + source lines, but the binary format doesn't have that. If the validator didn't work on an IR, but instead by a collection of functions (similar to the type-checker), then this could be more straightforward. It would also make it easier to reuse the parser without having to convert from Wabt IR.

Anyway, my point is that we might be able to get away with not having a required IR at all. Just a thought.

**Comment by dschuff** [comment]
Well, it used to be all callback-based. And now there are callbacks and an IR for different internal uses.

> Anyway, my point is that we might be able to get away with not having a required IR at all.

I guess that's what I meant by "rethinking" the IR. FWIW I did actually find it easier to use the IR from a C++ project than the callbacks because it was kind of a pain adapting a C callback interface to C++ (e.g. https://github.com/dschuff/wasm-aot-prototype/blob/bdf84471ff9cd0cd29fc80d86862bc5ffa533083/src/wasm_parser_cxx.h)

**Comment by binji** [comment]
Hm, even if we were using virtual functions instead of a bunch of function pointers?

**Comment by sbc100** [comment]
SGTM I guess.  I like the idea of doing it incrementally.   Probably a good idea to link to chromium's C++ guide to limit to reasonable usage.

**Comment by dschuff** [comment]
If we were using virtual functions, that would be a fine C++ API. but it wouldn't be a C API. then we'd have 2 different "public" APIs. Which actually, probably wouldn't be all that bad.

**Comment by binji** [comment]
Yeah, my thought is that as things transition to C++, we don't worry too much about the API boundary for C. As the C++ API solidifies, then we can make a nice wrapper C API. I'd prefer this to trying to maintain the current C API, which would be extremely tedious and brittle for C++ users.

**Comment by binji** [comment]
Updated top comment to be a GH checkbox list instead :)

**Comment by binji** [comment]
As Sam mentioned above, we should probably should pick a C++ style guide to follow. Chromium seems reasonable. Though as I said in #329, I don't really like enum classes being `EnumType::ENUM_VALUE`.

**Comment by binji** [comment]
There are just a few places left to fix:

- [ ] Use CamelCase instead of snake_case for function names
- [ ] Use class instead of `Context` in `wasm-interp.cc` and `wasm-link.cc`
- [ ] C-style callback in `BindingHash::find_duplicates`, `HostImportDelegate`, and `OptionParser`
- [ ] Use `string_view` instead of `StringSlice`
- [ ] Use member functions instead of free functions in IR (see bottom of `ir.h`)
- [ ] `WastParser` should be a class
- [ ] Change a few last `destroy_` functions into destructors

**Comment by binji** [comment]
No boxes left to check; let's call this done.
