### ISSUE TITLE
error: @0x00000004: bad magic value

### ISSUE THREAD

**Issue by jonas-db** [WebAssembly/wabt#328]
I've compiled a C++ function to Wasm by means of (latest emcc and binaryen)
`emcc fac.cpp -o file.js -s 'BINARYEN=".../binaryen/bin/asm2wasm"' -s WASM=1 -O1`

this works fine, however when trying to generate the AST with wasm2wast i get the following error:
`error: @0x00000004: bad magic value`

It seems that wasm2wast is lacking behind with the version number?
The first bytes of my wasm file are `7761 736d c9bd 0000`

How can this be solved?

**Comment by binji** [comment]
Pretty weird, AFAIK the magic value should be  `0061 736d 0100 0000` for version 1.

That says 'wasm' instead of '\0asm' and the version number is off too.

**Comment by jonas-db** [comment]
It seems that the latest SDK is not the "incoming" SDK which cause this error
