### ISSUE TITLE
'vector' file not found #include <vector>

### ISSUE THREAD

**Issue by umamichi** [WebAssembly/wabt#333]
After install LLVM+clang, cmake and binaryen, I tried this

```
$ git clone --recursive https://github.com/WebAssembly/wabt
$ cd wabt
$ make
```

then, command said this error

```
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory -C out/clang/Debug/ all
[  2%] Building CXX object CMakeFiles/hexfloat_test.dir/test/hexfloat.cc.o
/Users/my-user-name/Work/web-assembly/wabt/test/hexfloat.cc:19:10: fatal error:
      'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/hexfloat_test.dir/test/hexfloat.cc.o] Error 1
make[2]: *** [CMakeFiles/hexfloat_test.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [clang-debug] Error 2
```

sorry, if this problem is rudimentary mistake.

help me...😭

**Comment by binji** [comment]
Hm, seems like your clang installation is not working properly. Searching around, this seems to be a common problem: http://stackoverflow.com/questions/14115314/how-to-compile-c11-with-clang-3-2-on-osx-lion, http://stackoverflow.com/questions/16229297/why-is-the-c-standard-library-not-working, http://stackoverflow.com/questions/15981424/where-is-libc-on-os-x, etc.

These are all from 2013, though so maybe it's something else...?

**Comment by 3DEsprit** [comment]
I am having this same issue as well. 

Emscripten, Binaryen, as well as my Swift, Obj-C, and RN projects compile without any issue at all. Wabt gave this same error, after pulling down the submodules for the project, running make again, even after running 'make clean'. 

Using:
OSX 10.11.6
XCode 8.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Cmake 3.7.2

**Comment by binji** [comment]
Interesting, looking into it now. I just resurrected the Travis OS X build, and it seems fine. Similarly, my mac laptop is building it OK too. So I'm wondering what I'm doing that's weird in wabt that's breaking your configs. Taking a look at binaryen, it does use the `CXX_STANDARD` property on all of the executable targets, so I'll give that a shot.

**Comment by binji** [comment]
OK, landed that change in PR #336. Please take a look and see if that fixes things for you. Another thought I had is that you could try building wabt without gtest-based tests:

```
$ make clang-debug-no-tests
```

This will tell us if it's broken just for hexfloat_test, or for other files too.

**Comment by 3DEsprit** [comment]
Built like a champ! Thank you so much!

**Comment by binji** [comment]
Thanks, @3DEsprit! @umamichi can you confirm this works for you too?

**Comment by umamichi** [comment]
@binji 
Thank you!!
I tried that, Everything gone well!😊

**Comment by Fishrock123** [comment]
see also https://github.com/WebAssembly/wabt/issues/339, which is similar but more extensive in my case.

**Comment by binji** [comment]
OK, good to hear. Let's close this one.
