### ISSUE TITLE
new name section support

### ISSUE THREAD

**Issue by pipcet** [WebAssembly/wabt#334]
We should support the new extensible "name" section format, as specified in https://github.com/WebAssembly/design/commit/cd2af4d8149b23be87cc9eabbc4a97c7029178ad.

**Comment by pipcet** [comment]
https://github.com/WebAssembly/wabt/compare/master...pipcet:new-name-section?expand=1
has some code, which seems to work if I'm reading the spec correctly.

**Comment by binji** [comment]
Thanks for looking into this! Feel free to open a PR. Taking a look at what you have there, it looks pretty good. We'll want to support the other name sections for wasm2wast (binary-reader-ast) and wasmdump (binary-reader-objdump), but that seems reasonable to do in a separate PR.

**Comment by sbc100** [comment]
This is  basically done (at least for now right?) isn't it?

**Comment by binji** [comment]
I think so. There's more work to do if we add names for other types, but that isn't spec'd yet I think.
