### ISSUE TITLE
rename wast2wasm to wat2wasm?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/wabt#354]
In light of [design/#1012](https://github.com/WebAssembly/design/pull/1012) and updates to TextFormat.md.

**Comment by binji** [comment]
Hm, good idea, though currently it also parses wast.

I guess it would be good to separate those behaviors so there can be `wast2wasm` which always runs with `--spec` and generates a `.json` file with a `.wasm` file per module, and `wat2wasm` which only supports one module, no assertions, etc.

**Comment by Cellule** [comment]
Fixed by #616 and #617
