### ISSUE TITLE
.wast assert_return_canonical_nan & assert_return_arithmetic_nan

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/wabt#370]
This refers to https://github.com/WebAssembly/spec/pull/414 which was merged a few days ago.

2 new types of asserts were added `assert_return_canonical_nan` & `assert_return_arithmetic_nan` replacing `assert_return_nan`.

In order to support the current spec tests, these asserts needs to be supported in wast2wasm & wasm-interp

**Comment by binji** [comment]
I added support for this here https://github.com/WebAssembly/wabt/commit/aad6e98314bc4225dca7e12aa9795cb0ad87f21e

**Comment by Cellule** [comment]
Thanks, I didn't see it was added a few hours before I opened my issue.
