### ISSUE TITLE
Demo generation

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/wabt#371]
I was wondering how do you generate the libwabt.js in the demo.
I am trying to compile it in emscripten, but I haven't seen anything specific in this repo in order to regenerate it.
Right now I am hitting an issue with constexpr in emscripten.

**Comment by Cellule** [comment]
I found how to fix the constexpr problem by using `-std=c++11` option

**Comment by binji** [comment]
Oh, it's pretty broken at this point, I'd guess. See #369.

But the idea is that you can use "make emscripten-release" to do it; this basically just sets it up to use the emscripten compiler and cmake include. I was planning on cleaning it up, but haven't gotten around to it.

**Comment by Cellule** [comment]
Thanks!
at first I couldn't find it in the Makefile, but now I got it.
As you said it seems pretty broken, I think the `emscripten-helpers.cc` is also out of date unfortunately.

**Comment by binji** [comment]
FYI: this is fixed now.
