### ISSUE TITLE
Handling errors in custom sections

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#378]
We discussed this a bit in https://github.com/WebAssembly/wabt/pull/375.

It seems likely that we'll want to have the ability to bail out on known custom sections that are invalid, but also be able to ignore invalid custom sections too. It would be good to get specific use cases for this.

**Comment by sbc100** [comment]
Parsing old binaries with old-style names section would be one case.   Attaching an old binary that doesn't parse right now.
[debug-names-1.zip](https://github.com/WebAssembly/wabt/files/880720/debug-names-1.zip)

**Comment by binji** [comment]
Talked about this some more with @jgravelle-google. It seems like we'll want to be able to handle errors partially in some tools (e.g. wasm-objdump). We'll probably want to have an atomic unit for each section that must succeed to be displayed, but allow the section to have errors and continue gracefully.

For example, in the globals section, we would parse as many globals as possible and display them to the user, but if there is an invalid global, we would detect that, notify the user, and try to continue with other sections.

This should work OK, since most sections need to work under the assumption that other information may not be present anyway (i.e. the code section uses information from the function section, but can't assume that the function section exists).

**Comment by binji** [comment]
This is partially completed since https://github.com/WebAssembly/wabt/pull/636 landed. The only other feature would be to optionally ignore custom sections.

**Comment by binji** [comment]
Ignoring custom sections is now supported with the `--ignore-custom-section-errors` flag.
