### ISSUE TITLE
Stdin/out support

### ISSUE THREAD

**Issue by rumkin** [WebAssembly/wabt#386]
I'm converting wast on the fly from the web interface with wast2wasm. And currently I should to make redundant disk i/o. I think stdio should be supported by wabt utils.

**Comment by sbc100** [comment]
I agree.   This is commonly done by specifying '-o -'  for output and '-' for input.

**Comment by sbc100** [comment]
It should be noted that tools that require the ability to seek won't support this (e.g. as and ld can't write to stdout for this reason).

**Comment by pipcet** [comment]
I'm not sure this would be useful--it won't reduce disk I/O significantly, or at all if you keep the temporary files on a ramdisk.

**Comment by dschuff** [comment]
It might be useful in unusual ports (e.g. a build with emscripten where there's no "real" filesystem).

**Comment by sbc100** [comment]
Its also useful for chaining commands together, makes it easier to build longer commands, and when you just want to see that result on your screen.

**Comment by stianeikeland** [comment]
It would be very useful for building editor support, say you want to use wat2wasm for typechecking while working on a wast-file in your editor. In emacs this would be a simple flycheck-backend that calls wat2wasm and parse the error and linenumber.

**Comment by sbc100** [comment]
At least for input I think this should be easy enough and perhaps we could do that separately.  For output the seeking would probably make this change harder.

**Comment by tlively** [comment]
I hacked this for Binaryen in https://github.com/WebAssembly/binaryen/pull/1950. The important part was that I did not try to get the size of the input file by seeking to the end. I read into a string stream which I then converted to a string or vector of char or whatever input type was expected.

**Comment by keithw** [comment]
The stdout piece of this happened in #1902
