### ISSUE TITLE
br_table validation failure

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/wabt#389]
The following wast:
```
(module
 (table 0 anyfunc)
 (memory $0 17)
 (func $foo (param $0 i32) (result i32)
  (loop $label$1 i32
   (block $label$2
    (br_table $label$1 $label$2 $label$2
     (get_local $0)
    )
    (return
     (i32.const 0)
    )
   )
   (i32.const 1)
  )
 )
)
```
fails when ran through `wast2wasm` with the error message:
```
src/loop_br_table.wast:7:6: type mismatch in br_table, expected void but got i32.
    (br_table $label$1 $label$2 $label$2
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The problem seems to be that `br_table`'s type checking is treating loops and blocks as having the same type signature when used as a branch target. However, loops should be treated as being of type `void`, because a jump to a loop is a jump to the beginning of the loop, and clears the stack.

**Comment by jgravelle-google** [comment]
For reference, this module successfully validates in SpiderMonkey and the spec interpreter, but also fails to validate in V8 (https://bugs.chromium.org/p/v8/issues/detail?id=6204)

**Comment by binji** [comment]
Ah, good catch. It would probably be good to add a spec test for this.
