### ISSUE TITLE
Manual pages

### ISSUE THREAD

**Issue by Alhadis** [WebAssembly/wabt#417]
Hello,

After installing `wabt` through Homebrew, I noticed none of the executables had a corresponding manpage.

If assistance is needed, I'd be happy to write them for you. =) I thought I'd ask first instead of submit a PR up-front, as not all maintainers are up to maintaining manpages in addition to Markdown-based docs. Particularly when the subject is very build-centric in nature.

Let me know if there's anything I can do.

**Comment by sbc100** [comment]
Its there some nice way to produce man pages using markdown these days?  Then we can avoid duplicating the docs.

**Comment by Alhadis** [comment]
@sbc100 You might be thinking of [Ronn](https://github.com/rtomayko/ronn). Generating manpages from markdown often produces horrible or poorly-formatted results, though. A good manpage should be written by hand - in fact, it's better to generate markdown from manpages than the other way around.

It's your prerogative though.
