### ISSUE TITLE
 fatal error: 'stdarg.h' file       not found

### ISSUE THREAD

**Issue by liangzeng** [WebAssembly/wabt#419]
Scanning dependencies of target libwabt
[  1%] Building CXX object CMakeFiles/libwabt.dir/src/opcode.cc.o
In file included from /Users/liangzeng/Documents/wabt/src/opcode.cc:17:
In file included from /Users/liangzeng/Documents/wabt/src/opcode.h:20:
/Users/liangzeng/Documents/wabt/src/common.h:21:10: fatal error: 'stdarg.h' file
      not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/libwabt.dir/src/opcode.cc.o] Error 1
make[2]: *** [CMakeFiles/libwabt.dir/all] Error 2
make[1]: *** [all] Error 2

**Comment by myseemylife** [comment]
I got same error~how to solve it?Please help~T_T

**Comment by gogogous88** [comment]
same thing under debian Linux environment.

**Comment by gogogous88** [comment]
same thing under debian Linux environment.
have you got it solved? under Mac OS there was nothing wrong but under Linux I got this problem.
any solution?

**Comment by sbc100** [comment]
Can you attach the full output of `make clean` followed by `make VERBOSE=1`?

It seems like if you are missing `stdarg.h` you most likely have an issue at a deeper level.  Can you try to compile a program and just includes this header.
e.g. `echo "#include <stdarg.h>" | gcc -x c -c -`
