### ISSUE TITLE
Why is WABT_LINK_MODULE_NAME is hardwired to "__extern"?

### ISSUE THREAD

**Issue by winksaville** [WebAssembly/wabt#434]
In this [trivial test](https://github.com/winksaville/test-clang-and-wasm-merge/tree/use-wabt.myfork-wasm-link) I try compile and link two trivial C subroutines separately compiled using clang. I followed these instructions to build the [llvm trunk with wasm support](https://gist.github.com/yurydelendik/4eeff8248aeb14ce763e).

I ran into one problem, WABT_LINK_MODULE_NAME is always assumed to be "__extern" where as clang is using "env" for a "memory" section. I [change it to](https://github.com/winksaville/wabt/tree/change-WABT_LINK_MODULE_NAME-to-env) "env" and then wasm-link "worked", i.e. it created a reasonable looking wast file.

So why is WABT_LINK_MODULE_NAME hardwired to "env"?

**Comment by binji** [comment]
@sbc100 
I'm not sure why... I pulled up the PR and originally Sam had it as `linker`, then I asked him to change it to something that was less likely to conflict with user code so he chose `__extern`. I'm not a big of `env` TBH, but that seems to be what a number of tools assume at this point.

**Comment by winksaville** [comment]
Would you like a PR that made it configurable?

**Comment by binji** [comment]
I'd like to get @sbc100's input. I know he's been working on similar support for lld, so it would be best to match that.

**Comment by sbc100** [comment]
Happy to change to it 'env' for now so all the tools are in sync.  Making it easy to change and/or configurable would be even better.

**Comment by winksaville** [comment]
I'll create a PR to make it configurable and default to 'env', but ...

Reading the spec, I interpret the "module name" only has significance to identify in what module the linker should find the particular entity. So why is the linker even care about the actual name? It seems to me the module name should just be included in some internal record for resolution later.

From the [spec](https://webassembly.github.io/spec/syntax/modules.html#imports):

> Each import is identified by a two-level name space, consisting of a modulemodule name and a unique namename for an entity within that module. Importable definitions are functions, tables, memories, and globals. Each import is specified by a descriptor with a respective type that a definition provided during instantiation is required to match.

**Comment by winksaville** [comment]
[Here](https://github.com/WebAssembly/wabt/pull/437) is a PR which removes WABT_LINK_MODULE_NAME and adds module_name to ImportFunction and ImportGlobal.

**Comment by winksaville** [comment]
@sbc100, @binji  [removinng WABT_LINK_MODULE_NAME](https://github.com/WebAssembly/wabt/pull/437) seems to be working in that its passing existing tests and does resolve the problem I had with "env" as the module_name.

Is what I've done reasonable?

**Comment by sbc100** [comment]
So we would not mandate any naming scheme for the module name in wabt?  Seems like a reasonable approach.

**Comment by binji** [comment]
Sounds fine to me. @winksaville Feel free to clean up the patch you have and submit a PR, if you like!

**Comment by winksaville** [comment]
Will do tomorrow.

**Comment by winksaville** [comment]
Created "Allow any module name" #440

**Comment by winksaville** [comment]
Closing, resolved with #440
