### ISSUE TITLE
wast text code can be easier?

### ISSUE THREAD

**Issue by liangzeng** [WebAssembly/wabt#435]
I am javascript programmers. wast text code can be easier? similar to what I found in the early wast code. 

see:

https://github.com/ncbray/wassembler/blob/master/demos/simple.wasm

**Comment by binji** [comment]
I agree that the WebAssembly text format is verbose and hard to write. But the format was designed primarily for having a straightforward mapping to the binary format, not for being written be people. I think it would be worthwhile for someone to develop a high-level assembler for WebAssembly that is easier to write by hand (I'd like to work on it myself, but don't currently have the time), but I don't think wabt is the place for it.

**Comment by binji** [comment]
This is being discussed somewhat in https://github.com/WebAssembly/tool-conventions/issues/17. Closing here for now.
