### ISSUE TITLE
Add options to wat-writer

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#436]
@kanaka mentions [here](https://github.com/WebAssembly/spec/pull/471#issuecomment-301565835) that having some of the sugar makes for easier debugging. It shouldn't be too much work to add options to the wat-writer to support this:

- [ ] ~~inline function types for imported functions~~ (not valid in text format)
- [x] inline imports
- [x] inline exports
- [x] mnemonic labeling of variables (you can do this currently with the `--generate-names` flag, perhaps should be done by default?)
- [x] optional expression folding
- [x] use import/export name as debug name if no other debug name is supplied

**Comment by kanaka** [comment]
@binji yes, function types is what I was referring to.

**Comment by binji** [comment]
OK, thanks. `wasm2wast` already displays the inline function type for defined functions, but doesn't display them for imported functions.

**Comment by binji** [comment]
I realized it's not too hard to do expression folding, and fall back to stacky format when it's not possible: https://github.com/WebAssembly/wabt/pull/460

**Comment by binji** [comment]
Added last feature (inline imports) [here](7fcc96d15444346b244500fc205a677ca2d745d0). Closing.
