### ISSUE TITLE
Supporting exported memory for wasm-link

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/wabt#439]
When linking two WASM binaries with exported memories, the operation fails with message `unsupport export type: 2`.

s2wasm exports the memory by default, so this would be a useful feature to have to be able to link these files.

An adjustment like https://github.com/WebAssembly/wabt/compare/master...guybedford:memory-export may work here?

**Comment by sbc100** [comment]
Sounds good.  Do you fancy sending a pull request?  (Have you signed the CLA?)  If not I'm happy to take a look.

**Comment by guybedford** [comment]
Thanks that would be great. I fixed up the code there to cover the cases as
far as I can tell. I haven't signed a CLA, as far as I could tell that
requires joining the community group? Otherwise please feel free to take a
look at it further.

**Comment by jfbastien** [comment]
Yes, joining w3.org/community/webassembly/

**Comment by robzon** [comment]
Any progress on this issue?

**Comment by dschuff** [comment]
lld (https://lld.llvm.org/) now supports linking WebAssembly binaries; it should replace wasm-link. The question of course, is does lld support this use case; it might not, but it should be straightforward to fix.

**Comment by sbc100** [comment]
Yes, lld will export the memory by default (unless you pass --import-memory)

**Comment by sbc100** [comment]
I wonder if we should perhaps remove wasm-link completely soon?

**Comment by robzon** [comment]
Sorry for going slightly offtopic, but are there any examples on how to use lld with wasm? All I can find is very generic info. I compiled lld with WebAssembly support and still all I get is:

```
$ ld.lld app.wasm lib.wasm
ld.lld: error: app.wasm: invalid data encoding
```

`wasm-link` works fine with these files.

**Comment by sbc100** [comment]
You need to invoke it as `wasm-ld` (or pass -flavor=wasm) otherwise it lld will try to link for your host system.

**Comment by robzon** [comment]
Thank you! Now I get `wasm-ld: error: app.wasm: not a relocatable wasm file` even though the file is relocatable (compiled with `wat2wasm -r`).

Is there some better place I can ask these questions? /r/WebAssembly seems to be dead and I hate spamming issues on GitHub :-)

**Comment by sbc100** [comment]
We have an IRC channel on w3.org if you prefer. 

lld is expecting objects produced by clang, but I don't see why it shouldn't work with wat2wasm objects too.  Its doing a simple check on the linking metadata section.  I'll take a look at why its not working.    In fact you could open an issue for that perhaps?

**Comment by binji** [comment]
(I respond to stuff on /r/WebAssembly, but you're right it's pretty quiet there)

**Comment by robzon** [comment]
@sbc100 ok, I gotta run now, but tomorrow I'll investigate a bit more and open an issue for this.

@binji I'll keep subscribed and try to help whenever I can then. Maybe we can get that place going!

**Comment by binji** [comment]
Closing, as wasm-link has been removed (in favor of lld).
