### ISSUE TITLE
Update Homebrew Formula

### ISSUE THREAD

**Issue by domrein** [WebAssembly/wabt#459]
Using wast2wasm installed from homebrew produces wasm binaries that don't load ("expected version 01 00 00 00, found 0d 00 00 00") in Chrome 58.

**Comment by binji** [comment]
Yeah, that should be updated. :-) Not sure who did it originally, though.

**Comment by binji** [comment]
FYI: this seems to be the file to update. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wabt.rb

I don't have a mac hand to fix this, but it looks like it shouldn't be too hard to do.

**Comment by dasa** [comment]
A new release may need to be tagged first since Homebrew is already using the `0xd` version.

**Comment by binji** [comment]
Ah, I see. Well, the previous versions are tagged WRT the pre-release wasm version, not the wabt version. But I guess I can tag wabt HEAD at 1.0.0 for now.

**Comment by dasa** [comment]
Thanks, PR submitted at: https://github.com/Homebrew/homebrew-core/pull/16368

**Comment by binji** [comment]
Thanks, looks like this landed.
