### ISSUE TITLE
Add functionality to the JS build

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/wabt#470]
it would be nice to expose a few more features to libwabt.js. most useful will would probably be
- wasm2wast
- wast-desugar

**Comment by binji** [comment]
This PR adds some of that: https://github.com/WebAssembly/wabt/pull/491

There's no API to explore a loaded module yet, but that would probably be nice too.

**Comment by binji** [comment]
Gonna close for now, feel free to open new issues for additional feature requests.
