### ISSUE TITLE
Shift left in test suite

### ISSUE THREAD

**Issue by NikVolf** [WebAssembly/wabt#477]
Hi, just wanted to clarify about this line in i32.wast of the testsuite:

https://github.com/WebAssembly/testsuite/blob/c4ec0044b99feb322fc63708907d0be0a3088ed3/i32.wast#L173

`
(assert_return (invoke "shl" (i32.const 1) (i32.const 32)) (i32.const 1))
`

so it is asserting that 1 << 32 = 1

how is that true and what spec describes such behaviour?

**Comment by sunfishcode** [comment]
Shift instructions interpret the shift count as an [unsigned value modulo the bitwidth of the shift](https://github.com/sunfishcode/wasm-reference-manual/blob/master/WebAssembly.md#shift-count). `1 << 32` is effectively evaluated as `1 << (32 % 32)`, or equivalently `1 << (32 & 31)`.

**Comment by NikVolf** [comment]
Nice, thank you for pointing it out! 
Not sure why intel optimisations of shift instructions have made all the way to the webassembly, but great it is well-defined :)
