### ISSUE TITLE
Forward.wast

### ISSUE THREAD

**Issue by NikVolf** [WebAssembly/wabt#478]
wast2wasm (master) fails on the `forward.wast` from the testsuite (master):

wast2wasm --spec forward.wast
```
wasm2wast stdout:
wasm2wast stderr: ./testsuite/forward.wast:3:10: syntax error, unexpected RESULT
    (if (result i32) (i32.eq (get_local $n) (i32.const 0))
```

Probably this is a version mismatch issue between tests and wabt? If this is the case, what is the recommended stable combination of wabt (this repo) and testsuite (https://github.com/WebAssembly/testsuite) versions?

**Comment by binji** [comment]
The testsuite was recently updated to change the syntax from:
```
(if i32 ...)
```
to
```
(if (result i32) ...)
```

I have an in-progress PR to update to the newest format.

> If this is the case, what is the recommended stable combination of wabt (this repo) and testsuite (https://github.com/WebAssembly/testsuite) versions?

wabt has a pinned testsuite submodule in `third_party/testsuite`, that revision is the one that's tested against.
