### ISSUE TITLE
Install gcc build

### ISSUE THREAD

**Issue by skaffen2** [WebAssembly/wabt#495]
Hi,

I have built wabt successfully using the command `make gcc-release`, but there seems no installation support for it.  make install seems to assume I have clang installed.  Is there a way to run the make install target when using the gcc target?

**Comment by skaffen2** [comment]
I see now that the following installs into the bin subdirectory of wabt:

make install-gcc-release.

I imagine there's a way to specify where to copy the binaries to.

**Comment by binji** [comment]
Currently I don't think this is configurable w/ the makefile build. You can always run CMake directly to do this, and set the `CMAKE_INSTALL_PREFIX` to point to the proper directory.

But you're right, it probably would be best to have an environment variable or something to configure this.
