### ISSUE TITLE
Add documentation to README.md for the MSVC build

### ISSUE THREAD

**Issue by tneward** [WebAssembly/wabt#496]
Building CXX object ... test-string-view.cc eventually tries to include c++/type_traits, where "struct __is_floating_point_helper<__float128>" fails to compile.  

This is 64-bit Cygwin running on Windows7. Git-cloned just today.

**Comment by binji** [comment]
Not sure what's going on here... but we only test with mingw and msvc builds, so it's possible that cygwin is just broken.

**Comment by tneward** [comment]
Interesting! For some reason I thought I saw instructions for building wabt
using Cygwin. I'll give it a spin using mingw and see what comes out of it.

However, I don't see any instructions in the Git repo for building with
msvc. Can you share a link?

Ted Neward | Smartsheet
Director of Developer Relations
E: Ted.Neward@Smartsheet.com

**Comment by binji** [comment]
> However, I don't see any instructions in the Git repo for building with msvc.

Hm, good point. Probably should add some info for that! It does work, though, since we have an appveyor build. That's your best bet for now: https://github.com/WebAssembly/wabt/blob/master/appveyor.yml#L33

**Comment by tneward** [comment]
Once I got CMake and Python installed, everything worked flawlessly.
Thanks! (And just as an added bonus, I learned about something new
today--Appveyor. Good stuff!)

Ted Neward | Smartsheet
Director of Developer Relations
E: Ted.Neward@Smartsheet.com

**Comment by binji** [comment]
Cool! I'll leave this open for now to add some documentation about the msvc build.
