### ISSUE TITLE
What's the plan for supporting memory sections in wasm-link?

### ISSUE THREAD

**Issue by winksaville** [WebAssembly/wabt#507]
I'm  working around the issue by not using wasm-link and just including the [c files into a single source](https://github.com/winksaville/test-nn-wasm/blob/master/lib/libwasm.c). What is the time frame for adding memory section support?

**Comment by sbc100** [comment]
The memory segments of the various inputs should be combined by wasm link.   I'm also working on a port of lld which should have similar behavior.    The expectation is that each input object defines a memory and a segment for itself and these get combined into one large memory in the output. 

I would say that if you are looking for a real linker then lld is going to be what you want, once its ready.  My initial work is here: https://github.com/sbc100/lld/tree/add_wasm_linker_skeleton.  I'm hoping its not to far from being ready to land (although its far from complete).

**Comment by winksaville** [comment]
lld seems like the "right" solution, so I'll be watching that. Let me know if there is anything I can do to help. At a minimum I'd be glad to test it on [my little program](https://github.com/winksaville/test-nn-wasm) when it can link several C modules compiled with clang/llc/s2wasm/wast2wasm tool chain. The program has no standard library dependencies so its self-contained.

**Comment by sbc100** [comment]
Did you know that clang can already produce wasm binaries directly (no need for any of the llc/s2wasm/wast2wasm stuff!).   Its supported via the wasm32-unknown-unknown-wasm target (as opposed to the default which is wasm32-unknown-unknown-elf).   Those inputs are that ones that lld will be expecting.

**Comment by winksaville** [comment]
@sbc100 , using --target=wasm32-unknown-unknown-wasm worked great, thanks for the tip.

**Comment by binji** [comment]
Closing as wasm-link has been removed (in favor of lld).
