### ISSUE TITLE
Reorganize tools

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#543]
We should change the tools to the following (adding on to #354):

- [x] `wat2wasm`: converts .wat text files only to .wasm binary files, and optionally validates
- [x] `wast2json`: converts .wast spec test files to .json and .wasm files
- ~~`wat-validate`: standalone .wat file validation, no conversion~~
- [x] `wasm2wat`: converts .wasm files to .wat text files, and optionally validates (rename of `wasm2wast`)
- [x] `wasm-validate`: standalone .wasm file validation, no conversion
- [x] `spectest-interp`: (better name?) run the spec tests in interpreter (current `wasm-interp` functionality)
- [x] `wasm-interp`: only run a single .wasm file, later adding passing arguments (see #198)

All of the functionality is available currently, this is just splitting it out. Thoughts?

**Comment by sbc100** [comment]
I think maybe we can live with just one validate tool.  I would suggest you drop wat-validate.   If you want to validate a wat you can try to compile it with wat2wasm (which should validate by default), just like you would with a C++ source file.

**Comment by binji** [comment]
Sounds good.
