### ISSUE TITLE
wasm2wast error message have strange locations

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#557]
```
$ wasm2wast /tmp/emscripten_temp/emcc-lld-output.wasm 
(null):0: mutable globals cannot be exported
```
This happens whether of not I specify a -o file.

**Comment by binji** [comment]
Oh, weird. Probably a bug introduced from a5066278b34021de22b150442cb7a94d62e22102, but it shouldn't be displaying the filename if it is null.

**Comment by binji** [comment]
Should be fixed.
