### ISSUE TITLE
wasm-link: unhandled relocation type: R_GLOBAL_ADDR_LEB

### ISSUE THREAD

**Issue by meta221** [WebAssembly/wabt#565]
I'm getting this error when running wasm-link on a wasm module generated by llc.

The wasm module (as printed by wasm2wast):
```
(module
  (type (;0;) (func))
  (func $function (type 0)
    i32.const 0
    i32.const 1
    i32.store8)
  (table (;0;) 0 anyfunc)
  (memory (;0;) 1)
  (global (;0;) i32 (i32.const 0))
  (export "function" (func $function))
  (data (i32.const 0) "\00"))
```

## Steps to reproduce

Given this LLVM IR file:
```
target triple = "wasm32-unknown-unknown-wasm"

@global_boolean = internal global i1 false

define void @function() {
entry:
  store i1 true, i1* @global_boolean
  ret void
}
```

* Run `llc -filetype=obj -o function.wasm ir.ll`
* Run `wasm-link --output linked.wasm function.wasm`

Output: `unhandled relocation type: R_GLOBAL_ADDR_LEB`

**Comment by meta221** [comment]
Is this a bug in LLVM or WABT? Or am I just not using wasm-link correctly?

**Comment by sbc100** [comment]
Its a bug in wasm-link (wabt).   Having said that wasm-link is not really fully fledged linker so you will probably find more bugs like this going forward.  Once lld is ready we may remove wasm-link completely to avoid the maintenance burden of two linkers.

**Comment by jdh8** [comment]
This bug also occurred when I was testing `sbrk()` of my C implementation at jdh8/metallic@ebf9c9130b5e64a06cae9bcf6acef21faf4f8bb4. I'm really looking forward to a supporting `lld` to ease build automation.

By the way, I'd like to join @WebAssembly with this developing C/C++ implementation, but I'm not sure where to contact. I'm okay with renaming or relicensing my project.

**Comment by binji** [comment]
@jdh8 You can join the WebAssembly Community Group here:  https://www.w3.org/community/webassembly/. You may also want to take a look at https://github.com/dcodeIO/webassembly which seems to have similar goals.

**Comment by sbc100** [comment]
Taking a look at this now.

**Comment by binji** [comment]
Closing as wasm-link has been removed (in favor of lld).
