### ISSUE TITLE
Expected version is 0xd

### ISSUE THREAD

**Issue by kripken** [WebAssembly/wabt#585]
Shouldn't it be 0x1? When I try to view a 0x1 binary, I get
````
error reading binary:
  error: @0x00000008: bad wasm file version: 0x1 (expected 0xd)
````

**Comment by binji** [comment]
Weird, maybe your binary is really old? There are explicit spec tests for this in `binary.wast`, and they pass.

**Comment by kripken** [comment]
Ah yes. I had old binaries in the root dir, where I guess they used to go. The new ones are now put in `bin/`, I see. Thanks!
