### ISSUE TITLE
i32.const not working on Chrome 61 Linux

### ISSUE THREAD

**Issue by jamen** [WebAssembly/wabt#620]
Hello, new to WASM here.

I'm using WABT's `wat2wasm` tool (at caf98190ca5267a0864ef019889b31ed16d95f77) to compile this:

```wat
(module
  (func $test (result i32) (i32.const 64))
)
```

But in Chromium 61 on Linux I am getting an error:

```yml
CompileError: AsyncCompile: Wasm decoding failed: expected 11 bytes, fell off end @+30
```

So far I have discovered the error is related to the `i32.const` instruction.  If I put any number above `63` I get these decoding errors.  So this program is decoding in chromium fine:

```wat
(module
  (func $test (result i32) (i32.const 10))
)
```

Another interesting effect, the more `i32.const` instructions I have that are over `63`, it seems to break more.  In some cases the "expected x bytes" would grow in large numbers, or I would receive a different error.

**Comment by binji** [comment]
This may be a Chrome bug -- I checked wabt's output for this program and it looks correct to me. I also tried using the spec interpreter to generate wasm and it generated similar code. It wasn't identical because wabt writes canonical LEB128 section sizes by default, but the spec interpreter doesn't. You can pass `--no-canonicalize-leb128s` (it can also be abbreviated to anything non-ambiguous) to `wat2wasm` to mimic this behavior and it produces identical output to the spec interpreter.

By the way, 64 is perhaps special because it is the point at which the stream gets one byte longer. Since `i32.const` is encoded as a [signed LEB128](https://en.wikipedia.org/wiki/LEB128#Signed_LEB128) 63 takes just one byte (`0x3f`) but 64 takes two bytes (0xc0 0x00).

**Comment by binji** [comment]
I'm trying to repro this bug on Chrome Linux (version `61.0.3163.79 (Official Build) (64-bit)`).

I'm not seeing the bug, can you provide the code loading code you're using?
Here's what I have:
```html
<!DOCTYPE html>
<body>
  <script>
    fetch('i32.const.wasm').then(
        response => response.arrayBuffer()
      ).then(
        buffer => WebAssembly.instantiate(buffer)
      ).then(
        ({instance}) => {
          console.log(instance.exports);
        });
  </script>
</body>
```

And this is the contents of `i32.const.wasm` (passed through xxd):

```
00000000: 0061 736d 0100 0000 0105 0160 0001 7f03  .asm.......`....
00000010: 0201 000a 0701 0500 41c0 000b            ........A...
```

**Comment by jamen** [comment]
Ok..  Seems this was a problem of my own doing.  It is how I was loading the code.

My original WASM file matches the output of your file:

```
00000000: 0061 736d 0100 0000 0105 0160 0001 7f03  .asm.......`....
00000010: 0201 000a 0701 0500 41c1 000b            ........A...
```

But, I exported the port of WASM I was embedding into my JS, and the LEB must have got malformed somehow:

```
00000000: 0061 736d 0100 0000 0105 0160 0001 7f03  .asm.......`....
00000010: 0201 000a 0701 0500 41ef bfbd 000b       ........A.....
```

Here is a diff:

```
< 00000010: 0201 000a 0701 0500 41c1 000b            ........A...
---
> 00000010: 0201 000a 0701 0500 41ef bfbd 000b       ........A.....
```

I'll close this, but if you have any suggestions as to embedding WASM inside JS that would be cool.  So far I've tried base64 and a typedarray of a bunch of number literals.  I'm working on & using [`wasmify`](https://github.com/jamen/wasmify)

**Comment by binji** [comment]
Interesting, the LEB is changing from `0xc1 0x00` into `0xef bf bd` somehow.

I don't really understand the `browserify` stuff very much, but it looks like you're encoding as base64, but then just using `str2ab` to convert back. Is there somewhere else where the base64 decode happens?

It is interesting that `0xc1` is the first byte in the module that is >= `0x80` (i.e. has the top bit set). This seems like it could be a clue.

**Comment by jamen** [comment]
@binji For encoding I am using `buf.toString('base64')` in node, then embed the results into browser JS code which decodes it & initializes the module.  It's turning all WASM files into tiny JS modules that load themselves.

For decoding I'm using [`str2ab`](https://npmjs.com/string-to-arraybuffer) like you mention, which is `window.atob` + [doing `str.charCodeAt` and putting returns into a typed array](https://github.com/dfcreative/string-to-arraybuffer/blob/master/index.js#L23-L29).  

But also, I tried some method using arrays instead of base64 and it gave me `i32.const` errors too.  So I am not sure this is specific to base64 decoding.

**Comment by binji** [comment]
Ah, OK I see the `atob` now.

I wonder if the `contents` you're getting when reading the file is being decoded as utf8? When I ran a quick test in node (which I don't know very well), I got what appeared to be strange results:

```
> a = Buffer.from('\xc0')
<Buffer c3 80>
```

It seems that buffers decode the string as 'utf8' by default, so this fixes it:

```
> a = Buffer.from('\xc0', 'binary')
<Buffer c0>
```

Not sure how browserify loads the file, but maybe there's a parameter you need to pass to specify binary encoding. (Sorry if you already tried this)

**Comment by jamen** [comment]
@binji I think you're right, I got the same results just now by exporting the WASM Node is reading straight away, and I get that malformed code.  The read streams default to `utf8` so this is likely.

I'm not sure how to set the encoding for browserify, but that is a new thing to explore, so thanks for your help!
