### ISSUE TITLE
wat2wasm silently swallows trailing modules

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wabt#621]
Given a .wat file with multiple modules (as if a .wast file containing multiple modules were naively renamed as .wat), wabt's wat2wasm seems to silently ignore trailing modules.
```
$ cat t.wat
(module (func $foo (result i32) (i32.const 77)))
(module (func $bar (result i32) (i32.const 88)))
$ wat2wasm t.wat -o t.wasm
$ wasm2wat t.wasm -o s.wat
$ cat s.wat
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const 77))
$ 
```

As a related question, wat2wasm seems ok if the surrounding `(module` ... `)` isn't present, but doesn't seem to mind if it's present either. Is it intended that both forms are valid?

**Comment by binji** [comment]
> wabt's wat2wasm seems to silently ignore trailing modules.

Yeah, `wat2wasm` currently just does the same parsing as `wast2wasm` did, but just grabs the first module. Should be much easier to fix now that the parser is no longer using bison.


> As a related question, wat2wasm seems ok if the surrounding (module ... ) isn't present, but doesn't seem to mind if it's present either. Is it intended that both forms are valid?

Yeah, that was a relatively late addition to the text format spec.
