### ISSUE TITLE
wasm-objdump errors out on bad opcodes even when just printing section headers

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#627]
I have a bogus wasm file that apparently has a bad opcode somewhere in the code section (0xb531). I just wanted to see the section headers but I'm still getting an error:

$ bin/wasm-objdump --enable-threads -h pthread_create.wasm 

pthread_create.wasm:	file format wasm 0x1
*ERROR*: @0x0000b531: unexpected opcode: 0 (0x0)

Should this work?

**Comment by dschuff** [comment]
Also it seems odd that I have to use --enable-threads to make it even parse thread opcodes. This isn't how disassemblers on other platforms work (i.e. they always print instructions they know about). I guess this goes along with the idea that wasm-objdump is not a validator.

**Comment by sbc100** [comment]
I'm trying to repro but having trouble.  Seems like 0x0 is a valid opcode (unreachable) so not sure how you are getting this error.

**Comment by sbc100** [comment]
Ah.. found a separate bug that was always reporting invalid opcodes as 0

**Comment by binji** [comment]
I think this should work now. With Sam's fix and my fix. Can you verify, Derek?

**Comment by dschuff** [comment]
I'm getting a correct opcode, but still no headers:
```
wasm-objdump -h  cmpxchg2.wasm

cmpxchg2.wasm:	file format wasm 0x1
*ERROR*: @0x00000027: unexpected opcode: 254 72 (0xfe 0x48)
```

**Comment by binji** [comment]
Ah, right. This is the same issue I mentioned in https://github.com/WebAssembly/wabt/issues/378#issuecomment-328206980. We need to allow the binary reader to be more lenient when used with `wasm-objdump`.

**Comment by binji** [comment]
Should be fixed by https://github.com/WebAssembly/wabt/pull/636, please reopen if not.
