### ISSUE TITLE
ModuleField assertion

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/wabt#637]
The following wat code triggers an assertion
```wat
(module (test))
```
`Assertion failed: !"ParseModuleField should only be called if IsModuleField() is true", file E:\Projects\wabt\src\wast-parser.cc, line 734`

`ParseModuleFieldList` tries to `ParseModuleField` then on error validate with `IsModuleField`.
Either it should check beforehand, like the assert mentions, or remove the assertion.

This doesn't seem to have any effect on release build since the error case is correctly handled.

**Comment by binji** [comment]
Thanks, fixed in #638. I should run a fuzzer over the parser again now that I've rewritten it. Probably will find all sorts of bugs like this. :-}
