### ISSUE TITLE
Support for host exported functions in wasm-link.

### ISSUE THREAD

**Issue by TreyBoudreau** [WebAssembly/wabt#651]
I'd like to use wasm-link create objects for use with an embedded interpreter, where the host provides implementations of some functions, but I don't see how to accomplish this. The linker refuses to create files with unresolved function imports, and while the WABT interpreter has a notion of "host functions" and even has a fake opcode to support this, I don't see a way to satisfy wasm-link.  Just leaving the import unresolved and specifying "-r" results in a fatal error:
> unsupport export type: 3

Without "-r", it reports:
> undefined symbol: host_symbol

Have I missed something, or have we not yet considered this use case?

**Comment by binji** [comment]
This is a better question for @sbc100. My guess is that it's just missing functionality.

**Comment by binji** [comment]
Closing as wasm-link has been removed (in favor of lld)
