### ISSUE TITLE
SIMD support in WABT

### ISSUE THREAD

**Issue by arunetm** [WebAssembly/wabt#663]
Any ongoing efforts to support SIMD opcodes in WABT? We have an implementation in progress and will be happy to contribute.

**Comment by binji** [comment]
I haven't started on it yet, and I'm not sure than anyone else has either. Feel free to send a PR! There are a lot of opcodes though, might be nice to break them up into a few PRs for easy reviewing.

**Comment by lizhengxing** [comment]
@binji:
Hi, I’m working on supporting SIMD opcodes in WABT. I am close to putting together an initial PR for review and had a question. Has there been any decisions made on representing v128 consts in WAT or WAST file? If not do you, have a preference / thoughts?
Our Suggestions:
1.	V128.const ( (i32.const 0x00), ….. , (i32.const 0x00)  )  (16 i32.consts)
2.	V128.const 0x00000000000000000000000000000000  (16 bytes)

fyi @arunetm

**Comment by binji** [comment]
I'm not certain, maybe @stoklund has some thoughts/ideas?

**Comment by arunetm** [comment]
"V128.const ( (i32.const 0x00), ….. , (i32.const 0x00) ) (16 i32.consts)" looks easier to read to me. :)

**Comment by sunfishcode** [comment]
I find it a little confusing to say "i32.const" for things which are effectively 8-bit constants. Also, there were issues in the past using parens for things that don't directly map to wasm opcodes.

How about:
```wasm
     (v128.const i32 0x00000000 0x11111111 0x22222222 0x33333333)
     (v128.const i8 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0a 0x0b 0x0c 0x0d 0x0e)
     (v128.const f64 0x1.921fb54442d18p+2 -0x1.921fb54442d18p+2)
```
etc.

A downside is that this allows multiple ways to encode the same value, but it'd be much nicer to write tests if we can just list the scalar values we want.

**Comment by arunetm** [comment]
This makes life easier while writing tests. however we might have to pick canonical type format for wasm2wat conversions and text interpretations of binaries during debugging.

**Comment by binji** [comment]
We have a similar issue with converting int and float values to text; we could try and be clever and generate nice signed numbers and floats, but IIRC, wasm2wat always uses unsigned numbers and hex floats. I think it would be reasonable to just pick a format (`v128.const i32` seems nice and concise from @sunfishcode's examples) and come up with heuristics to print pretty numbers later if desired.

**Comment by arunetm** [comment]
@binji , WABT should be compliant with the latest simd spec. Shall we close this issue? :)

**Comment by binji** [comment]
Sounds good @arunetm. Thanks for helping out @lizhengxing!
