### ISSUE TITLE
Enable "write_debug_names" option in WAT2WASM online demo

### ISSUE THREAD

**Issue by mirkosertic** [WebAssembly/wabt#675]
The "write_debug_names" option should be enabled in the WAT2WASM online demo. This will add the debug names section to the generated WASM binary and will in consequence allow better debugging in latest Chrome and Firefox.

I'd be happy to provide a pull request.

**Comment by binji** [comment]
Sounds good, feel free to send a PR.

**Comment by mirkosertic** [comment]
Issue closed, as PR is merged. Thanks for the quick response :-)
