### ISSUE TITLE
Remove wasm-link?

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#679]
Since we can link with lld, perhaps it makes sense to remove `wasm-link` so to reduce confusion. It'd be nice to have an alternate linker, but since `wasm-link` isn't quite there, it may be creating more harm than good. @sbc100 wdyt?

**Comment by sbc100** [comment]
I tend to agree.. I found wasm-link useful for early prototyping but I don't think it has a future.   Lets first make sure that any users it does have can switch to lld.. although I'm not sure how find them (maybe deleting it is actually the easiest way to do that :)

**Comment by robzon** [comment]
I'd go with a deprecation warning for a couple of months first just to give people time to move to an alternative. Unfortunately lld is not a drop-in replacement yet, so abruptly removing wasm-link could cause issues for some people.

**Comment by binji** [comment]
This was removed in https://github.com/WebAssembly/wabt/commit/4d6106c3a510c7e2986324cd3493c6694d3ace3a.
