### ISSUE TITLE
initializer expression can only reference an imported global

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#680]
When I'm trying wast2wasm the following code:

```WebAssembly
(module
  (global i32 (i32.const 0))
  (global i32 (get_global 0))
)
```

error message is printed:

```
init_with_internal_global.wast:3:3: initializer expression can only reference an imported global
```

[Spec states that](https://webassembly.github.io/spec/valid/modules.html#globals):

> `expr` should be constant,

and then, [spec states](https://webassembly.github.io/spec/valid/instructions.html#constant-expressions) that constant exprs can be either in form of `t.const`, or

> of the form get_global 𝑥, in which case 𝐶.globals[𝑥] must be a global type of the form const 𝑡.

But I can't see anything about that `x` should be imported. Binaryen's `wasm-as` seems like to accept this code.

Is it a bug, error in the spec or am I get something wrong?

**Comment by binji** [comment]
It's specified, but not there: https://webassembly.github.io/spec/valid/modules.html#valid-module

See the note at the bottom, in particular:

> Globals, however, are not recursive. The effect of defining the limited context C′ for validating the module’s globals is that their initialization expressions can only access imported globals and nothing else.

**Comment by pepyakin** [comment]
Oh, I see. This is a really important note!
Thanks!

**Comment by binji** [comment]
The note makes it much clearer, but it is specified above as well. That's why most of the values access from context `C`, but globals access from context `C'`.
