### ISSUE TITLE
wasm-link deprecated but cannot get suggested replacement lld to work

### ISSUE THREAD

**Issue by nolash** [WebAssembly/wabt#745]
I've used `wat2wasm` a minimal implementation divided on two files and want to link them. When I invoke `wasm-link` it says the tool is deprecated, and I should use `lld` instead.

However, `lld` fails with error `invalid data format`. I've tried with `5.0.0` `5.0.1` and `6.0.0`, all built from source with `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD"

Although this is an error maybe more related to `llvm` toolchain, I'm raising it here because the tool is explicitly mentioned in `wasm-link`.

**Comment by sbc100** [comment]
Actually lld support doesn't require any experimental targets.   But you do need to run with `-flavor wasm` (or run it via its `wasm-ld` alias).

If that doesn't work can you post more details of your command line the lld output (with `--verbose` and/or` -mllvm -debug` flags too).

**Comment by nolash** [comment]
`--flavor wasm` did the trick. Thanks.
