### ISSUE TITLE
Seems like wabt don't pass testsuite?

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#749]
https://github.com/WebAssembly/spec/blob/4f078ff69de51d07c1c265273e396f42b2fb2dd3/test/core/unreached-invalid.wast#L507

I expect `wat2wasm` will successfuly serialize the following module:

```WebAssembly
(module (func (export "test") (result i32)
    (block (result i32)
      (unreachable) (br_if 0 (i32.const 0) (i32.const 0)) (i32.const 0)
    )
  )
)
```

however, `wat2wasm` reports an error:

```
Error: validate failed:
test.wast:3:60: error: type mismatch in block, expected [] but got [i32]
      (unreachable) (br_if 0 (i32.const 0) (i32.const 0)) (i32.const 0)
                                                           ^^^^^^^^^
```

I've checked there https://cdn.rawgit.com/WebAssembly/wabt/aae5a4b7/demo/wat2wasm/ and on a74072b2163ca20645e4a313636507cb3984f5fb (`master`, at the moment of writing)

**Comment by pepyakin** [comment]
Ah, sorry, this is indeed `assert_invalid` test!

**Comment by binji** [comment]
Yes, I found it difficult to come up with a good message for these "errors". Sorry about the confusion!
