### ISSUE TITLE
wabt validates memory with `shared` flag with default options.

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#754]
It seems that wabt by default (i.e. without any options) successfully validates modules that have non MVP features, e.g. this one:

```WebAssembly
(module
  (memory 1 1 shared)
)
```

However, features (at least in wabt options) are looks like opt-in:

```
      --enable-exceptions                     Experimental exception handling
      --enable-saturating-float-to-int        Saturating float-to-int operators
      --enable-threads                        Threading support
      --enable-simd                           SIMD support
```

So, I'm wondering is it intended?

**Comment by binji** [comment]
Oops, that's not intended. Fix here: https://github.com/WebAssembly/wabt/pull/756.
