### ISSUE TITLE
wast2wasm not found

### ISSUE THREAD

**Issue by stefan-reich** [WebAssembly/wabt#777]
Hi, I believe wast2wasm should be part of wabt? https://github.com/Hanks10100/wasm-examples/tree/master/simple uses it, but wast2wasm doesn't exist in the wabt I built (latest GitHub)...

(new to WebAssembly)

**Comment by binji** [comment]
Sorry for the confusion! The extension of the text format for a module is ".wat", and the extension that the WebAssembly spec testsuite uses is ".wast". A lot of tools still use the ".wast" extension (including wabt originally).

Anyway, wast2wasm is now called wat2wasm if you are converting a module. You can also use wast2json if you are converting a spec test.

**Comment by binji** [comment]
Closing, please reopen if you have further questions.
