### ISSUE TITLE
How to run/test exported function of WASM binary using wasm-interp?

### ISSUE THREAD

**Issue by karthikrish9** [WebAssembly/wabt#798]
Hello,

I am trying to run an exported function of WASM binary and following is the 
error I am getting. What am I doing wrong? Any help appreciated. 
```

$wasm-interp ../../hello.wasm                           
  error: unknown import module "env"
  0000083: error: OnImportMemory callback failed

$wasm-interp ../../hello.wasm --run-all-exports --trace
  error: unknown import module "env"
  0000083: error: OnImportMemory callback failed


```

**Comment by binji** [comment]
`wasm-interp` is pretty limited in what it can interpret currently, it is mostly meant to be used to run the WebAssembly spec tests. So it doesn't provide the `env` module, which is why your example is failing.

You could add support for it, in the same way that the `spectest` module is supported, but that would require making changes to the `wasm-interp` executable.

**Comment by karthikrish9** [comment]
Hi @binji ,

Can you expand a bit more on how  I can add support for `env` module in `wasm-interp`? 

thanks a lot.

**Comment by binji** [comment]
Take a look at the example code for the `spectest` module here: https://github.com/WebAssembly/wabt/blob/master/src/tools/spectest-interp.cc#L844-L933

Basically, you call `AppendHostModule`, then set its `HostImportDelegate` to handle importing functions, tables, memories, or globals.

**Comment by karthikrish9** [comment]
thank you, that make sense :) 

I see that the `spectest` module supports following imports:

```
table (ImportTable)
memory (ImportMemory)
global (ImportGlobal)
```

But the wasm binary I am working on also have following imports. 
How do I add support these imports in the wasm-interp?
 
```
  (import "env" "DYNAMICTOP_PTR" (global $env.DYNAMICTOP_PTR i32))
  (import "env" "STACKTOP" (global $env.STACKTOP i32))
  (import "env" "STACK_MAX" (global $env.STACK_MAX i32))
  (import "env" "abort" (func $env.abort (type $t1)))
  (import "env" "enlargeMemory" (func $env.enlargeMemory (type $t2)))
  (import "env" "getTotalMemory" (func $env.getTotalMemory (type $t2)))
  (import "env" "abortOnCannotGrowMemory" (func $env.abortOnCannotGrowMemory (type $t2)))
  (import "env" "_gmtime" (func $env._gmtime (type $t3)))
  (import "env" "___setErrNo" (func $env.___setErrNo (type $t1)))
  (import "env" "_emscripten_memcpy_big" (func $env._emscripten_memcpy_big (type $t4)))
  (import "env" "___syscall20" (func $env.___syscall20 (type $t5)))
  (import "env" "_ftime" (func $env._ftime (type $t3)))
  (import "env" "memory" (memory $env.memory 256 256))
  (import "env" "table" (table $env.table 8 8 anyfunc))
  (import "env" "memoryBase" (global $env.memoryBase i32))
  (import "env" "tableBase" (global $env.tableBase i32))```

**Comment by binji** [comment]
You would have to implement them manually in C++, with knowledge of what the various imports are meant to do. This isn't obvious, as the implementations are emscripten-specific internals. If you look at the JavaScript file that was generated when you compiled your .wasm file with Emscripten, you'll see implementations of these functions. You'd have to reimplement them in C++.

It's doable, but `wasm-interp` isn't really set up to make it easy to do this, sorry!

**Comment by esnible** [comment]
Would it be awesome if there was a way to provide the imports via another .wasm file's exports, or if I could supply a flag, e.g. `--export-as-no-op env_proxy_log(a:int, b:int, c:int):int` that would let the program start, but no-op or log any calls to `env_proxy_log()`.

I am coming at this using [WebAssembly for Proxies](https://github.com/proxy-wasm/spec).  I want to write my own tests for my .wasm, tests that don't require an actual proxy running locally.

**Comment by binji** [comment]
@esnible I assume you've resolved your issue, but maybe the `--dummy-import-func` flag does what you want?
