### ISSUE TITLE
i64.const value couldn't read

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#799]
```
AGFzbQEAAAABBAFgAAADAgEAChABDgBCgICAgICAgID/fhoL
```

This file is successfully loaded by the spec interpreter and binaryen.

But wasm2wat reports an error:

```
0000018: error: unable to read i64 leb128: i64.const value
```

**Comment by binji** [comment]
I believe wabt is correct here (though the error message could be clearer), the value that is being parsed is `0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x7e`. The encoding uses 7 bits per byte, so the first 9 bytes encode 63 bits. The least-significant bit of the 10th byte encodes the sign bit of the 64-bit value, and it is required that the 7 more-significant bits are a sign-extension of this bit (i.e. they match). In this case, 0x7e has the sign-bit cleared, but the following bits set, which is invalid.

As confirmation, also fails to load this module with a clearer error message:
```
CompileError: WebAssembly.Module(): Compiling wasm function #0 failed: extra bits in varint @+33 
```

**Comment by pepyakin** [comment]
Oh, I see! I see that you created issue in the spec repo, thanks for that!

Also I seen such behavior in wasm-dis, so cc @kripken

**Comment by kripken** [comment]
Thanks @pepyakin , I opened https://github.com/WebAssembly/binaryen/issues/1469

**Comment by binji** [comment]
OK, spec interpreter bug was fixed and binaryen has a bug filed, so closing here.
