### ISSUE TITLE
windows 10 VS2017 wabt installation

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/wabt#804]
Hi all,
how to install wabt on windows 10 ?

i tried following

git clone --recursive https://github.com/WebAssembly/wabt

mkdir build

cd build

c:\users\myusername\wabt -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=c:\users\myusername\build\bin -G "Visual Studio 15 2017"

cmake --build c:\users\myusername\wabt --config RELEASE --target install
Error: could not load cache

need help, thank you

**Comment by ldm0** [comment]
Same issue, have you fix it?

**Comment by extremety1989** [comment]
yes i fixed it ,thank you for reply
