### ISSUE TITLE
fatal error: 'string' file not found

### ISSUE THREAD

**Issue by abdulgalimov** [WebAssembly/wabt#805]
```
$ make

.....
Scanning dependencies of target libwabt
[  1%] Building CXX object CMakeFiles/libwabt.dir/src/token.cc.o
In file included from /Users/sam/wasm/wabt/src/token.cc:17:
/Users/sam/itt/wasm/wabt/src/token.h:20:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/libwabt.dir/src/token.cc.o] Error 1
make[2]: *** [CMakeFiles/libwabt.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [clang-debug] Error 2
```

How to fix it?

cmake version: 3.8.0
mac version: 10.13.3 High Sierra

**Comment by binji** [comment]
This seems to be a common issue, see https://github.com/WebAssembly/wabt/issues/716#issuecomment-362934981. Some were able to solve with `xcode-select --install`, try that.

**Comment by abdulgalimov** [comment]
It did not fix:
```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by pepyakin** [comment]
So I believe you need to go to the AppStore and update Xcode tools and in particular "Command Line Tools ".

**Comment by artdias90** [comment]
I'm having the same problem.
`$ xcode-select --version `
`xcode-select version 2349.`

`$ make`
` token.h:20:10: fatal error: 'string' file not found`

**Comment by shlomi-schwartz** [comment]
I'm having the same issue, @artdias90 I tried removing the out folder than make, and still having same issue. Am I missing something?

**Comment by jingweno** [comment]
Any updates on this? Had the same issue on OSX:

```
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make --no-print-directory -C out/clang/Debug/ all
-- Using prebuilt re2c lexer
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jou/gocode/src/github.com/jingweno/wabt/out/clang/Debug
Scanning dependencies of target libwabt
[  1%] Building CXX object CMakeFiles/libwabt.dir/src/token.cc.o
In file included from /Users/jou/gocode/src/github.com/jingweno/wabt/src/token.cc:17:
/Users/jou/gocode/src/github.com/jingweno/wabt/src/token.h:20:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/libwabt.dir/src/token.cc.o] Error 1
make[2]: *** [CMakeFiles/libwabt.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [clang-debug] Error 2

$ xcode-select --version
xcode-select version 2349.

$ cmake --version
cmake version 3.12.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by binji** [comment]
@jingweno Have you installed the XCode "Command Line Tools" as [described above](https://github.com/WebAssembly/wabt/issues/805#issuecomment-372434964)? If so, did you remove the `out` directory before compiling again?

If your command line tools are installed correctly, you should be able to run the following command without error:
```
echo "#include <string>" | clang++ -E -x c++ - | grep "/string" | head -n 1
```

On my Mac this produces:
```
# 1 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string" 1 3
```

On my Linux laptop it produces:
```
# 1 "/usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../include/c++/8.2.0/string" 1 3
```

**Comment by clayheaton** [comment]
FWIW, on a new Mac, you need to actually launch Xcode before trying to install something that depends on the command line tools. Otherwise, all of the various components are not yet installed. I ran into this issue on a new headless Mac Mini.

**Comment by sarkispeha** [comment]
What is this 'out' directory that everyone has referenced? Where can I find it?

I get the same output as binji

**Comment by gdorion** [comment]
It's the build folder containing your built files.

**Comment by sbc100** [comment]
Its kind of annoying how the default cmake configuration doesn't print the command line that failed, only its output.

I think this is another good reason to switch to the ninja cmake generator by default (in the top level Makefile).  It will make these kind of but reports a lot more useful.

**Comment by penzn** [comment]
try `make VERBOSE=1`

**Comment by sbc100** [comment]
Right.. I'm just not sure the top level make passes that argument on generated makefile (does it?).    And its kind of annoying to say "thanks for the bug report, please go back and run you failing build again with this other argument", when using ninja just makes it work.

**Comment by sbc100** [comment]
Ah yes that does work.. thanks `+$(MAKE)`

**Comment by penzn** [comment]
Sorry, I lost the conversation in my inbox. Yes, that is relatively annoying for the reporter. I tend to use `make` if I need to debug the build, specifically because of the verbosity setting, but that might not be the best default.
