### ISSUE TITLE
Consider a separate repo for libwabt.js?

### ISSUE THREAD

**Issue by EricForgy** [WebAssembly/wabt#818]
Hi,

I understand libwabt.js is essentially wabt run through Emscripten, but it looks like a pretty handy little JS lib itself. I can see myself using it for some things and I suspect I'm not alone. I think it would be kind of great if libwabt.js was a separate repo (or CDN even) people can use to play around with.

Just a thought. Cool stuff 👍 

PS: This thought is motivated by some experimental work compiling Julia to wasm https://github.com/MikeInnes/Charlotte.jl and I'm thinking about how to make it interactive, e.g. via WebSockets or something, e.g. generate .wat files and send them to a browser. Better solution is to write a wabt wrapper in Julia and that will happen eventually 😊 I can think of many other educational purposes for libwabt.js as well like the existing demos.

**Comment by binji** [comment]
Yeah, it would be easy enough to just mirror the output in another repo. Not sure whether we can (or would) do that under github.com/WebAssembly, though. I imagine it would be fine to do that from any user, too. (Anyone who knows better, please correct me if I'm wrong!)

**Comment by xtuc** [comment]
I guess that's what https://github.com/AssemblyScript/wabt.js is for. CDN is available at https://unpkg.com/wabt@1.0.0/index.js

**Comment by EricForgy** [comment]
Awesome. I didn't see that. Thank you so much 😊
