### ISSUE TITLE
wasm2c: Type Mangling does not support V128, causing SEGFAULT

### ISSUE THREAD

**Issue by opticaliqlusion** [WebAssembly/wabt#823]
The type mangling map in c-writer.cc does not support the V128 type in the following code:

```
static char CWriter::MangleType(Type type) {
  switch (type) {
    case Type::I32: return 'i';
    case Type::I64: return 'j';
    case Type::F32: return 'f';
    case Type::F64: return 'd';
    default: WABT_UNREACHABLE;
  }
}
```

However, the binary reader considers the V128 type valid and will parse it just fine (passes the `is_concrete_type` check with a value of `-0x5`).

```
static bool is_concrete_type(Type type) {
  switch (type) {
    case Type::I32:
    case Type::I64:
    case Type::F32:
    case Type::F64:
    case Type::V128:
      return true;

    default:
      return false;
  }
}
```

This causes wasm2c to SEGFAULT when attempting to append `__builtin_unreachable()` to a `std::string`. If the code does not fault (not debug, no stack checks, etc) undefined behavior occurs, usually still resulting in a SEGFAULT, but much more dangerously.

The small wasm file attached exercises this problem and crashes wasm2c.

[wasm2c-crash-v128.zip](https://github.com/WebAssembly/wabt/files/1878400/wasm2c-crash-v128.zip)

**Comment by opticaliqlusion** [comment]
@binji making the changes while im still editing the ticket! very fast on the draw

**Comment by binji** [comment]
Good catch, thanks! `wasm2c` doesn't currently support any of the non-MVP features, so it's not surprising it breaks. But at the very least, you shouldn't be able to parse the `v128` type.

I think I'll do a follow up to fail if you try to use `--enable-*` flags with `wasm2c`...

**Comment by opticaliqlusion** [comment]
Tested against my test binaries and it looks like it's fixed (error / `--enable-simd` works): great work!
