### ISSUE TITLE
wasm2wat not work with rust

### ISSUE THREAD

**Issue by quininer** [WebAssembly/wabt#836]
![screenshot_20180512_020702](https://user-images.githubusercontent.com/6286761/39939521-208786cc-5589-11e8-8798-d837e20c329d.png)

wasm2wat works before [1.0.1](https://github.com/WebAssembly/wabt/releases/tag/1.0.1).

**Comment by binji** [comment]
I think this is the same bug mentioned in https://github.com/WebAssembly/wabt/pull/830, does it work if you pass `--ignore-custom-section-errors`?

**Comment by quininer** [comment]
No, it doesn't work.

![screenshot_20180512_022703](https://user-images.githubusercontent.com/6286761/39940416-d35515f6-558b-11e8-8254-f0e906d4a60d.png)

**Comment by binji** [comment]
Can you upload the wasm file somewhere so I can take a look?

**Comment by quininer** [comment]
It's the hello-world example of wasm-bindgen.

[hello_world.wasm.zip](https://github.com/WebAssembly/wabt/files/1996454/hello_world.wasm.zip)
