### ISSUE TITLE
"error: imports must occur before all non-import definitions" is not spec compliant

### ISSUE THREAD

**Issue by ColinEberhardt** [WebAssembly/wabt#847]
wat2wasm enforces that imports are the first fields within a module. However the [specification states that](http://webassembly.github.io/spec/core/text/modules.html#text-module):

> A module consists of a sequence of fields that can occur in any order.

**Comment by binji** [comment]
That section also states restrictions that require imports to come first. The note makes it clear:
```
The second condition enforces that all imports must occur before any regular definition of a function, table, memory, or global, thereby maintaining the ordering of the respective index spaces.
```

**Comment by ColinEberhardt** [comment]
Ah, thanks for pointing that out - I didn’t spot that caveat. Is it worth updating the text I quoted above, strictly speaking it is incorrect.

**Comment by binji** [comment]
Yes, I think if something is unclear in the spec it is worth filing a bug at least suggesting that we clarify it.
