### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by crazyhtm** [WebAssembly/wabt#859]
I have tried to compile WABT tools, but no luck until now.
I have cloned git repo, then cmake and make 

after cmake seems to be ok, but it stops on wasm2c with below error 

[ 89%] Linking CXX executable wasm2c
/usr/bin/ld: cannot open output file wasm2c: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/wasm2c.dir/build.make:121: recipe for target 'wasm2c' failed
make[2]: *** [wasm2c] Error 1
CMakeFiles/Makefile2:930: recipe for target 'CMakeFiles/wasm2c.dir/all' failed
make[1]: *** [CMakeFiles/wasm2c.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I am on Linux 4.13.0-39-generic #44-Ubuntu x86_64 GNU/Linux
cmake version 3.9.1
clang version 5.0.0  (emscripten 1.37.36 : 1.37.36)
GNU Make 4.1

Any help please?

**Comment by binji** [comment]
Oh, I see. I don't usually build in-tree, so I haven't seen this issue. One workaround is to build in a separate directory (which I normally do):

```
$ mkdir out
$ cd out
$ cmake ..
$ make
```

Also, the top-level `Makefile` does this for you automatically:

```
$ make gcc-release
```

**Comment by crazyhtm** [comment]
$ mkdir out
$ cd out
$ cmake ..
$ make
works perfect, many thanks for super fast support
