### ISSUE TITLE
wasm2wat issue

### ISSUE THREAD

**Issue by nrllh** [WebAssembly/wabt#863]
I'm tring to convert wasm to wat, but i get following error:

**ReferenceError: module is not defined**

My function is:

`function wasm2wat2(wasmLink) {
    if (wasmLink == null) {
        return null;
    }

    var Module = {};
    var wasmBinary;
    let finalResult;;
    fetch(wasmLink)
        .then(buffer => {
            console.log(buffer);
            try {
                let contents = Uint8Array.from(buffer, (x) => x.charCodeAt(0));
                log(contents);

                var module = wabt.readWasm(contents, {
                    readDebugNames: true
                });
                module.generateNames();
                module.applyNames();
                let result =
                    module.toText({
                        foldExprs: true,
                        inlineExport: true
                    });
                console.log("!!!!!!!!!!!!!!!!!!!!!!!!!:" + result.length);
                finalResult = result;
            } catch (e) {
                console.log(e.toString());
            } finally {
                if (module) module.destroy();
            }
            log(finalResult);
            return finalResult;
        })
        .catch(err => console.error(err)); // Never forget the final catch!

    return finalResult;
    /* var wat = getContent("https://example.com/dev/wasm/web.wat");
     return wat;*/
}`

can you please tell me, what i am doing false?

**Comment by binji** [comment]
It's hard to tell from looking at this snippet. Do you know the line number where the error occurs?

If I had to guess, it's because you are using `module` in the finally block, but since it is defined using let in the try block, it isn't available. You could change that definition from `let` to `var` to test.

**Comment by NurullahDe** [comment]
i changed it to var, but it didn't work. I did some another changes, but it still doens't return the wat content.
