### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by tongyongliang** [WebAssembly/wabt#870]
error:

`CMake Warning at CMakeLists.txt:151 (message):
  Error running file on dummy executable`

commond:

`cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=..\bin  -G "MinGW Makefiles"`

why?

**Comment by binji** [comment]
The build script expects to have the `file` tool in the path. Does your mingw setup not have this tool?

**Comment by tongyongliang** [comment]
how to setup?

**Comment by binji** [comment]
I don't know much about mingw installations, sorry. In the past I've used [msys2](https://www.msys2.org/) for this, perhaps that will help.

**Comment by tongyongliang** [comment]
Thank you ,this error does not affect the installation，I used `git submodule update --init` complete the installation

**Comment by camilstaps** [comment]
Perhaps the message can be clarified to explain that the executable `file` is needed in the path. I first misunderstood and thought it meant that some generated file could not be executed. Perhaps a message like `Error while running "file xyz.txt"` would be more easy to understand.

**Comment by binji** [comment]
@camilstaps good idea, I opened https://github.com/WebAssembly/wabt/pull/1050 to clarify.

**Comment by dubiousjim** [comment]
Looks like this can be closed.
