### ISSUE TITLE
The option -h of wasm-objdump is ambiguous

### ISSUE THREAD

**Issue by rrrapha** [WebAssembly/wabt#872]
<pre>
options:
  -h, --headers                Print headers
  -j, --section=SECTION        Select just one section
  -s, --full-contents          Print raw section contents
  -d, --disassemble            Disassemble function bodies
      --debug                  Print extra debug information
  -x, --details                Show section details
  -r, --reloc                  Show relocations inline with disassembly
  -h, --help                   Print this help message
</pre>

**Comment by binji** [comment]
@sbc100 
It's meant to match the options for [objdump](https://linux.die.net/man/1/objdump), I believe.

Maybe would be better to rename the short option for headers to '-H' or remove the short option for help?

**Comment by sbc100** [comment]
Looks like objdump uses -h for headers and -H/--help for help.  Lets match them.

**Comment by sbc100** [comment]
I don't think that has to follow.  If we look at binutils for example, nm (also part of binutils) doesn't use -H.  I propose we just update objdump for now.  Honestly, I'm surprised argparse even allows this in the first place.

**Comment by binji** [comment]
That's what I get for writing my own argument parser :-)

**Comment by rrrapha** [comment]
@sbc100
Doing this change for wasm-objdump only means duplicating code from the OptionParser. 
IMO it would be more consistent to just remove -h in AddHelpOption() (affects all tools).
