### ISSUE TITLE
Mutable global variables

### ISSUE THREAD

**Issue by briantbutton** [WebAssembly/wabt#874]
I have been unable to find (or guess) how to declare a mutable global variable.  Is it really supported?  If so, what is the syntax?

Apologies in advance if this is a dense question.

FWIW I could find no examples of syntax for global variables (not imported) at all.  I finally guessed it.  This works for me.  
                         (global $firstPrime      i32 (i32.const 2))

**Comment by binji** [comment]
The text format is described in the spec, though that's probably not the easiest way to read it: http://webassembly.github.io/spec/core/text/types.html#global-types

It's also described more compactly here: https://github.com/WebAssembly/spec/tree/master/interpreter#s-expression-syntax

You can also look at the wabt tests for clues:
https://github.com/WebAssembly/wabt/blob/master/test/parse/module/global.txt

hope that helps!

**Comment by briantbutton** [comment]
Thank you.  I am rolling.  The second link you provided gave me the clues I needed.
BTW the wat2wasm page is the bomb!  It's my main development platform.
