### ISSUE TITLE
error: OnImportFunc callback failed

### ISSUE THREAD

**Issue by xyproto** [WebAssembly/wabt#883]
When executing [this](https://github.com/andoma/vmir/blob/master/examples/prebuilt/sha1sum.wasm) wasm file from the [vmir](https://github.com/andoma/vmir) project, `wasm-interp` fails with:

```
error: unknown import module "env"
000003b: error: OnImportFunc callback failed
```

I'm using [this](https://aur.archlinux.org/packages/wabt/) user-submitted Arch Linux package. Could this be a bug with the package, are any files missing at install-time? Here is a list of the installed files:

```
/usr/bin/spectest-interp
/usr/bin/wabt-unittests
/usr/bin/wasm-interp
/usr/bin/wasm-objdump
/usr/bin/wasm-opcodecnt
/usr/bin/wasm-validate
/usr/bin/wasm2c
/usr/bin/wasm2wat
/usr/bin/wast2json
/usr/bin/wat-desugar
/usr/bin/wat2wasm
```

**Comment by binji** [comment]
`wabt-interp` doesn't provide any default modules, so "env" won't work out of the box. You could make a separate tool that provides it, but I don't know if anyone has done this.
