### ISSUE TITLE
Using wabt tools as a parser

### ISSUE THREAD

**Issue by sudosalim** [WebAssembly/wabt#897]
Referring to https://github.com/WebAssembly/wabt/issues/308#issuecomment-280735411, has there been recommended way for getting (walking) though the parsed result? And what would be the best entry point to wrap in order to use the tool in other languages such as Java?

**Comment by binji** [comment]
I haven't spent much time on providing a real API for this, sorry. You can probably use [`ReadBinaryIr`](https://github.com/WebAssembly/wabt/blob/master/src/binary-reader-ir.h#L28) as an entrypoint to convert the text into a `Module`, but you'll have to walk the structure manually. You might want to look at [`ValidateModule`](https://github.com/WebAssembly/wabt/blob/master/src/validator.cc#L1455) for how that's done.

**Comment by sudosalim** [comment]
Thank you very much @binji. I have been testing different tools provided by the WebAssembly community, and I think I will go with Binaryen since it has a C API. Which I think make more sense to start from there, as it will be more easy to wrap the API for my uses...

**Comment by binji** [comment]
Seems to be resolved, closing.
