### ISSUE TITLE
Do we have any tool which can give me size of functions which are in .wasm file

### ISSUE THREAD

**Issue by Praveer1981** [WebAssembly/wabt#917]
I have a .wasm file which has lots of mangled functions[which I Knew after converting it into .txt file using wasm-dis.ex]. How can I know the size of each function? Do we have any tool which can help me to achieve this?

**Comment by binji** [comment]
You may want to take a look at [twiggy](https://github.com/rustwasm/twiggy), it's a code size profiler for wasm files.

In wabt, `wasm-objdump` would probably be the best tool to add this functionality, but it doesn't exist yet.

**Comment by jgravelle-google** [comment]
[Bloaty McBloatface](https://github.com/google/bloaty) also has wasm support, I've used that and twiggy for size profiling, IIRC they both present data somewhat differently and it can be useful to check both.

**Comment by Praveer1981** [comment]
@jgravelle-google:
what was the size of the .wasm file which you used? I am using twiggy and not able to use the 3+MB file. However, it works well if the file size in KB

**Comment by jgravelle-google** [comment]
It's been a while, I think in the 500KB-1MB range?

**Comment by binji** [comment]
[In this PR](https://github.com/WebAssembly/wabt/pull/975), I added some basic functionality to `wasm-objdump` to display the size of functions:

```
$ wasm-objdump -j code -x test.wasm

test.wasm:    file format wasm 0x1

Section Details:

Code[111]:
 - func[12] size=30
 - func[13] size=4
 - func[14] size=6
 - func[15] size=13
 - func[16] size=16
 - func[17] size=6
 - func[18] size=4
 - func[19] size=430
 - func[20] size=2885
...
```
