### ISSUE TITLE
How to pass parameters to libwabt.js?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#920]
I want to set the flag "--enable-saturating-float-to-int" to libwabt.js bevor calling parseWat() How can I do this?

**Comment by binji** [comment]
It's not currently possible. I've added support for it here: https://github.com/WebAssembly/wabt/pull/921

**Comment by Horcrux7** [comment]
I use now:
```
var features = {'sat_float_to_int':true, 'sign_extension':true};
var ret = wabt.parseWat(filename, text, features);

```
and it works. Thanks.
