### ISSUE TITLE
Implement further segment validation checks for bulk memory operations

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#928]
First added in https://github.com/WebAssembly/wabt/pull/927 the bulk memory operations aren't fully validated yet. Right now they don't verify that the immediate indexes passed to `{table,memory}.{init,drop}` are valid segments for the table/memory sections. For validation to be complete we'll need to validate that the index is indeed in bounds ~~and it's also a passive segment~~ (not needed any more!).

**Comment by conrad-watt** [comment]
We decided recently not to validate whether the index is a passive segment ahead of time (https://github.com/WebAssembly/bulk-memory-operations/issues/27, https://github.com/WebAssembly/bulk-memory-operations/pull/31).

**Comment by alexcrichton** [comment]
Oh sorry, my bad! I've updated the description

**Comment by binji** [comment]
I think these are all fixed now.
