### ISSUE TITLE
Fails to warn about malformed wat

### ISSUE THREAD

**Issue by blackhole12** [WebAssembly/wabt#936]
While I was testing my own webassembly compiler against the official interpreter tests, I was trying to verify the results against wabt, but accidentally discovered that the wat compiler fails part of `call_indirect.wast`. Namely, it is not verifying that the inline type declarations match the explicit type reference. Instead, the inline type declarations override the explicit type reference, which is very unexpected.

This `.wat` module currently compiles in [wat2wasm](https://webassembly.github.io/wabt/demo/wat2wasm/):

```
(module
    (type $sig (func (param i32) (result i32)))
    (table 0 anyfunc)
    (func (result i32)
      (call_indirect (type $sig) (result i32) (i32.const 0))
    )
)
```

This code is malformed, because there exists an inline type declaration in addition to the explicit type reference. The inline type declaration forms a function that takes no parameters and returns `i32`. The referenced type, however, is a function that takes `i32` and returns `i32`. This is expected to throw an "inline function type" error in [`call_indirect.wast`](https://github.com/WebAssembly/spec/blob/b3de271e8da3f8aa29a9ea3455665f88b1a4c3d2/test/core/call_indirect.wast#L359).

Instead, wat2wasm discards the referenced type and uses the inline type to compile the function. If the situation is reversed, the code does not compile, but only because the type is now expecting a parameter that is not provided, not because of a signature mismatch.

```
(module
    (type $sig (func (result i32)))
    (table 0 anyfunc)
    (func (result i32)
      (call_indirect (type $sig) (param i32) (result i32) (i32.const 0))
    )
)
```

Yields: 
```
test.wast:5:8: error: type mismatch in call_indirect, expected [i32] but got []
(call_indirect (type $sig) (param i32) (result i32) (i32.const 0))
```

**Comment by binji** [comment]
Thanks! I was pretty sure wabt checked this, but it turns out that it only checked it when running the spec tests, not when running `wat2wasm`.
