### ISSUE TITLE
Improvement of the interpretator traces

### ISSUE THREAD

**Issue by mikevoronov** [WebAssembly/wabt#943]
I have spent some time using wasm-interp to investigate some issues in compiled wasm code and think that It would be better to change the trace formatting scheme. In particular, I suggest to use `$` only for representing local variables of functions. I understand the current rule of `$` using but traces traces like this one
```
get_local $1
i32.const $1
```
is still a little bit confusing for me. After the first look It is intuitively expected that `i32.const` also operates with local variable and `$1` doesn't a simply numerical constant.

**Comment by binji** [comment]
Yes, I see what you mean. I agree that the format could be improved; I wrote the tracing format a long time ago and didn't really think about it much. Any thoughts on how to make it more clear?

**Comment by keithw** [comment]
Fixed in #954
