### ISSUE TITLE
did Thread::ReadMemory have implicit bugs?

### ISSUE THREAD

**Issue by yaozhongxiao** [WebAssembly/wabt#944]
According to the "Memory Instructions of WebAssembly Core Specification"
https://webassembly.github.io/spec/core/bikeshed/index.html#syntax-instr-memory

linear memory in wasm will access with load or store.
loads and stores are followed by the encoding of their memory-immediate {align:u32, offset:u32}

however, we I read the source code in wabt/src/interp/interp.cc, I was confused with the ReadMemory. did i miss some important clues?

`
template <typename MemType, typename ResultType>
Result Thread::Load(const uint8_t** pc) {
    typedef typename ExtendMemType<ResultType, MemType>::type ExtendedType;
    void* src;
    CHECK_TRAP(GetAccessAddress<MemType>(pc, &src));
    MemType value;
    LoadFromMemory<MemType>(&value, src);
    return Push<ResultType>(static_cast<ExtendedType>(value));
}

template <typename MemType, typename ResultType>
Result Thread::Store(const uint8_t** pc) {
    typedef typename WrapMemType<ResultType, MemType>::type WrappedType;
    WrappedType value = PopRep<ResultType>();
    void* dst;
    CHECK_TRAP(GetAccessAddress<MemType>(pc, &dst));
    StoreToMemory<WrappedType>(dst, value);
    return Result::Ok;
}

Memory* Thread::ReadMemory(const uint8_t** pc) {
  Index memory_index = ReadU32(pc);
  return &env_->memories_[memory_index];
}

template <typename MemType>
Result Thread::GetAccessAddress(const uint8_t** pc, void** out_address) {
  Memory* memory = ReadMemory(pc);
  uint64_t addr = static_cast<uint64_t>(Pop<uint32_t>()) + ReadU32(pc);
  TRAP_IF(addr + sizeof(MemType) > memory->data.size(),
          MemoryAccessOutOfBounds);
  *out_address = memory->data.data() + static_cast<IstreamOffset>(addr);
  return Result::Ok;
}
`

**Comment by yaozhongxiao** [comment]
hi @binji,  I found some TODO() or FIXME()  from you, thus , I try to at you firstly.

**Comment by binji** [comment]
> linear memory in wasm will access with load or store.
loads and stores are followed by the encoding of their memory-immediate {align:u32, offset:u32}

Yes, in the binary format it's stored this way. But in the interpreter, it's already been converted to a different format that's faster to read (i.e. removing all LEB128 values and encoding them as u32 instead). Also the interpreter doesn't care about alignment (it always uses memcpy for loads/stores) so the alignment value is removed.

**Comment by yaozhongxiao** [comment]
> > linear memory in wasm will access with load or store.
> > loads and stores are followed by the encoding of their memory-immediate {align:u32, offset:u32}
> 
> Yes, in the binary format it's stored this way. But in the interpreter, it's already been converted to a different format that's faster to read (i.e. removing all LEB128 values and encoding them as u32 instead). Also the interpreter doesn't care about alignment (it always uses memcpy for loads/stores) so the alignment value is removed.

OK, I see.
I will read the code further, thanks so much!
