### ISSUE TITLE
Creating wasm object file with wat2wasm

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#965]
I'm trying to create a module which I'm intending to compile in into my program. The module looks like the following:

```WebAssembly
(module
    (import "env" "__stack_pointer" (global $sp (mut i32)))

    (func (export "reserve_stack") (param $size i32)
        get_global $sp
        get_local $size
        i32.sub
        set_global $sp
    )
)
```

When I'm trying to compile it I'm getting the following error:

```
wat2wasm -r -o linkme.wasm linkme.wat
~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld \
    -flavor wasm \
    --relocatable \
    -o liblinkme.a \
    --export "reserve_stack" \
    linkme.wasm

rust-lld: error: symbol exported via --export not found: reserve_stack
```

is this supported use-case at all?

cc @sbc100

**Comment by sbc100** [comment]
No, this is not really supported, because its not possible to express relocactions and symbol table custom sections in the wat format.

The only way to get a wasm object file that I know of today is to have llvm create it for you using the `wasm32-unknown-unknown` target.

**Comment by sbc100** [comment]
Do do the above you proably want to write a `.s` file and pass it clang, or a `.ll` file and pass it to `llc`

**Comment by binji** [comment]
We really should add the [custom annotations](https://github.com/WebAssembly/annotations) support, so we can handle things like this though.

**Comment by pepyakin** [comment]
ah, that's really unfortunate. I was hoping that either lld can just pick-up exported functions or wat2wasm can emit relocation information for me.

What I'm trying to do is to implement segmented stack functionality (similar to `__morestack`), and now I'm think I'm out of options...

**Comment by pepyakin** [comment]
I wanted to do that in a general purpose library and I can't assume that users who compile this library have `llc` installed (I can use wabt though). 

I think I can produce a wasm module that implements this functionality and just put the binary along with the library though. 

But there some other problems: I had an impression that there is no way to hook up to `__stack_pointer` in the `.ll` and for `.s` I just haven't found any documentation, examples or test files and don't know how to write it : )

**Comment by sbc100** [comment]
With .s files you can certainly do __stack_point manipulation.    Just compile any .c file with `--target=wasm32 -S` to see the syntax for get/set global. e.g.

```
main:                                   # @main
	.functype	main () -> (i32)
	.local  	i32, i32, i32, i32, i32, i32, i32, i32, i32
# %bb.0:                                # %entry
	get_global	__stack_pointer@GLOBAL
	set_local	0
	i32.const	16
	set_local	1
	get_local	0
	get_local	1
	i32.sub 
	set_local	2
	get_local	2
	set_global	__stack_pointer@GLOBAL
```

With .ll you would need to use intrinsics, but I actually don't know if thats possible today.

**Comment by pepyakin** [comment]
Yes, thank you @sbc100 this is really helpful.
