### ISSUE TITLE
Different behavior when using wat2wasm online demo vs local binary

### ISSUE THREAD

**Issue by paulyoung** [WebAssembly/wabt#967]
If I provide a module name, eg. `(module $foo)` in the [wat2wasm demo](https://webassembly.github.io/wabt/demo/wat2wasm/index.html), I see the custom "name" section in the build log.

However, if I run `wat2wasm` on the same source and then do `wasm-objdump --details` on the binary it produces, the "name" section isn't present.

Is the online demo using a version newer than `wabt-1.0.6`, or does the online demo just behave differently?

**Comment by binji** [comment]
Yes, the wat2wasm demo writes the `names` section by default, but with the `wat2wasm` command-line tool you have to pass the `--debug-names` flag.

**Comment by paulyoung** [comment]
Good to know, thanks!

**Comment by paulyoung** [comment]
Perhaps it's an (over-)optimization, but `wat2wasm` on `(module $foo)` produces a binary that is 0 bytes, both with and without the `--debug-names` flag.

**Comment by binji** [comment]
> Perhaps it's an (over-)optimization, but wat2wasm on (module $foo) produces a binary that is 0 bytes, both with and without the --debug-names flag.

Hm, I don't see that behavior locally:

```sh
$ cat test.wat
(module $foo)
$ wat2wasm test.wat -v
0000000: 0061 736d                                 ; WASM_BINARY_MAGIC
0000004: 0100 0000                                 ; WASM_BINARY_VERSION
$ wat2wasm test.wat -v --debug-names
0000000: 0061 736d                                 ; WASM_BINARY_MAGIC
0000004: 0100 0000                                 ; WASM_BINARY_VERSION
; section "name"
0000008: 00                                        ; section code
0000009: 00                                        ; section size (guess)
000000a: 04                                        ; string length
000000b: 6e61 6d65                                name  ; custom section name
000000f: 00                                        ; module name type
0000010: 00                                        ; subsection size (guess)
0000011: 03                                        ; string length
0000012: 666f 6f                                  foo  ; module name
0000010: 04                                        ; FIXUP subsection size
0000015: 02                                        ; local name type
0000016: 00                                        ; subsection size (guess)
0000017: 00                                        ; num functions
0000016: 01                                        ; FIXUP subsection size
0000009: 0e                                        ; FIXUP section size
```
