### ISSUE TITLE
Cannot build project with wabt on windows

### ISSUE THREAD

**Issue by xmclark** [WebAssembly/wabt#972]
I found this while using another project that depends on `wabt`. I could not build the project on windows. I narrowed the issue down to `wabt`. I may not understand something about building `wabt` on windows (which is very likely). It appears to fail on linking a static library.

Dev environment:
Windows 10
Git Bash terminal or command prompt
stable-x86_64-pc-windows-msvc

Steps to reproduce:
1. Make a rust library project with cargo
```
[package]
name = "test-install-wabt"
version = "0.1.0"
authors = ["author"]
edition = "2018"

[dependencies]
wabt = "0.7"
```
2. Run `cargo build --verbose`

Output from `cargo build`:
```
error: could not find native static library `wabt`, perhaps an -L flag is missing?

error: aborting due to previous error

The following warnings were emitted during compilation:

warning: cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
warning: cl : Command line warning D9002 : ignoring unknown option '-std=c++11'

error: Could not compile `wabt-sys`.

Caused by:
  process didn't exit successfully: `rustc --crate-name wabt_sys C:\Users\Mac\.cargo\registry\src\github.com-1ecc6299db9ec823\wabt-sys-0.5.1\src\lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=30eaec991ef17094 -C extra-filename=-30eaec991ef17094 --out-dir C:\Users\Mac\CLionProjects\test-install-wabt\target\debug\deps -L dependency=C:\Users\Mac\CLionProjects\test-install-wabt\target\debug\deps --cap-lints allow -L native=C:\Users\Mac\CLionProjects\test-install-wabt\target\debug\build\wabt-sys-e96e7bad3e0ee4c3\out\build -L native=C:\Users\Mac\CLionProjects\test-install-wabt\target\debug\build\wabt-sys-e96e7bad3e0ee4c3\out -l static=wabt -l static=wabt_shim` (exit code: 1)
```

I expected this to build without issue.

**Comment by binji** [comment]
It seems this is a known issue with the wabt-rs crate on Windows: https://github.com/pepyakin/wabt-rs/issues/20

**Comment by xmclark** [comment]
@binji oops look like I posted in the wrong repo. No wonder I didn’t find anything in the issues. Thanks! I will close this unless there are objections.

**Comment by binji** [comment]
No problem, I should probably make it clearer on this repo that issues for wabt-rs should be redirected there.
