### ISSUE TITLE
sha256 files for Windows releases?

### ISSUE THREAD

**Issue by kpine** [WebAssembly/wabt#995]
Would it be possible to include sha256 files for the Windows zip files? Specifically, this would make it easier to integrate with the [Scoop](https://github.com/lukesampson/scoop) package manager.

**Comment by binji** [comment]
It should work, just need to do a little appveyor wrangling :-)

First try here: https://github.com/WebAssembly/wabt/commit/4d5b0ba9e6a0ca36a094ec520ada45f5db7104ad

**Comment by binji** [comment]
Looks like it somehow worked! Closing for now, please reopen if you see any issues.
